### ISSUE TITLE
Unequivocally retain XDG Extended Attributes in every operation.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [samschott/maestral#1002]
0.	**Is your feature request related to a problem? Please describe.**
	
	I suggest the opposite of https://github.com/samschott/maestral/issues/361#issue-835966433 due to

	> The official Dropbox client uses extended attributes (xattr) to associate sync metadata with files. Maestral will under some circumstances overwrite and delete such metadata.

	because I use standard XDG Extended Attributes in my files.
	
0.	**Describe the solution you'd like**
	
	Never delete such information unless the user requests it be performed, as the aforementioned https://github.com/samschott/maestral/issues/361#issue-835966433 describes.
	
0.	**Describe alternatives you've considered**
	
	https://en.wikipedia.org/wiki/TagSpaces#File_names_and_file_formats

**Comment by samschott** [comment]
Good point! It looks like GH action test runners provide systems with support for Xattr on Linux, so automated testing for now limited to macOS unfortunately. I might ask you to try out test release at some point instead.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/samschott/maestral/issues/1002#issuecomment-2016961183

@samschott, which release would be your test release? https://pypi.org/project/maestral/1.9.4.dev0/#copy-hash-modal-8dd12bfa-c0dc-4a5b-ae1b-b0a13f98de60?

**Comment by samschott** [comment]
Sorry, this completely fell off my radar. This is even already in the last stable release 1.9.3, though only manually tested myself on Ubuntu. Please let me know if its working for you!
