### ISSUE TITLE
Feature request: clickable notifications

### ISSUE THREAD

**Issue by coxackie** [SamSchott/maestral#101]
The official Dropbox client allows for some minimal interaction with desktop notifications (at least on Linux with GNOME DE). For example, the file manager (Nautilus, in the case of GNOME) should be opened in cases of:
1. specific file sync errors;
2. changed files;
3. ...

A bit of care should be given: in case 2 of changed files, what happens when these are too many, etc. Just opening this issue for discussion for the moment.

**Comment by SamSchott** [comment]
Done in v1.2.0.
