### ISSUE TITLE
Rename the System Service app to Maestral from Sam Schott

### ISSUE THREAD

**Issue by lothar-cell** [samschott/maestral#1021]
**Is your feature request related to a problem? Please describe.**
In System Settings/General/Login Items/Allow in the Background the name of the launch deamon is Sam Schott, which is kinda weird, I didn't know what's that at first.

**Describe the solution you'd like**
I'd like it renamed to Maestral.

**Additional context**
<img width="473" alt="Screenshot 2024-02-12 at 11 11 46" src="https://github.com/samschott/maestral/assets/2356354/54c17e99-ca0e-4f27-93a7-9776a6905e6c">

**Comment by samschott** [comment]
Could you try to uncheck 'Start at login' and re-check it in Maestral's settings? I think this should be fixed for newly registered startup items.

**Comment by lothar-cell** [comment]
Yep, it's fixed now, thank you!
