### ISSUE TITLE
OSError: [Errno 95] Operation not supported:

### ISSUE THREAD

**Issue by gianter962** [samschott/maestral#1033]
**Describe the bug**

maestral 1.9.2-1 does not complete compilation and hangs on "tests/offline/utils/test_path.py"

**To Reproduce**

Just try to update from 1.8.0 installation

**Expected behaviour**

maestral 1.9.2-1 complete its compilation and install normally

**System:**

 - Maestral version: 1.8.0
 - Python version: Python 3.11.8
 - OS: [e.g. Ubuntu] Archlinux vanilla
 - Desktop environment: [e.g. Gnome 3.32] Mate 1.28.2
 - PyQt version (for Linux GUI): --

**Additional context**

tests/offline/utils/test_path.py .....F

======================================================= FAILURES =======================================================
______________________________________________ test_move_preserves_xattrs ______________________________________________

tmp_path = PosixPath('/tmp/pytest-of-gianluca/pytest-0/test_move_preserves_xattrs0')

    def test_move_preserves_xattrs(tmp_path):
        src_path = str(tmp_path / "source.txt")
        dest_path = str(tmp_path / "dest.txt")
    
        # Extended attributes set by the user need to be prefixed with 'user.' in Linux.
        attr_name = "user.test" if IS_LINUX else "com.myapp.test"
        attr_value = "hello!".encode()
    
        touch(src_path)
        touch(dest_path)
>       xattr.setxattr(dest_path, attr_name, attr_value)

tests/offline/utils/test_path.py:118: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/lib/python3.11/site-packages/xattr/__init__.py:184: in setxattr
    return xattr(f).set(attr, value, options=options)
/usr/lib/python3.11/site-packages/xattr/__init__.py:78: in set
    return self._call(_setxattr, _fsetxattr, name, value, 0, options | self.options)
/usr/lib/python3.11/site-packages/xattr/__init__.py:60: in _call
    return name_func(self.value, *args)
/usr/lib/python3.11/site-packages/xattr/lib.py:82: in _setxattr
    raise error(path)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

path = b'/tmp/pytest-of-gianluca/pytest-0/test_move_preserves_xattrs0/dest.txt'

    def error(path=None):
        errno = ffi.errno
        strerror = os.strerror(ffi.errno)
        if path:
>           raise IOError(errno, strerror, path)
E           OSError: [Errno 95] Operation not supported: b'/tmp/pytest-of-gianluca/pytest-0/test_move_preserves_xattrs0/dest.txt'

/usr/lib/python3.11/site-packages/xattr/lib.py:33: OSError
=============================================== short test summary info ================================================
FAILED tests/offline/utils/test_path.py::test_move_preserves_xattrs - OSError: [Errno 95] Operation not supported: b'/tmp/pytest-of-gianluca/pytest-0/test_move_preserves_xattrs0/dest.txt'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
========================= 1 failed, 212 passed, 3 skipped, 2 deselected, 2 warnings in 40.43s ==========================
==> ERRORE: Si è verificato un errore in check().
    L'operazione sta per essere interrotta...
 -> errore durante la creazione: maestral-exit status 4

**Comment by samschott** [comment]
Not directly a bug in Maestral itself. It seems like you are running the unit tests on a system which does not support setting extended attributes. The test suite was not prepared to encounter this.

Fixed now.

**Comment by gianter962** [comment]
Thank you for your answer but the error remain

**Comment by gianter962** [comment]
![Schermata su 2024-04-07 18-47-49](https://github.com/samschott/maestral/assets/77537820/a1bff5ba-7eb3-4da8-ba05-b554b570d350)

**Comment by samschott** [comment]
I'm not quite sure how Maestral is distributed for Archlinux, or why the tests are part of the distribution / run as part of the installation process.

In any case, you'll to talk to the Archlinux package maintainers to include the updated tests. I'm reluctant to cut a new release for a change that is not actually part of the distributed Python code.

**Comment by gianter962** [comment]
Thanks for your prompt response. On Arch Linux Maestral is part of the AUR repository. It is compiled starting from the following PKGBUILD. If you can show me a way to exclude tests during compilation I would be happy.
Thanks in advance

# Maintainer: Jeremy Gust <jeremy AT plasticsoup DOT net>
# Contributor: Luis Martinez <luis dot martinez at disroot dot org>
# Contributor: Batuhan Baserdem <lastname dot firstname at gmail>
pkgname=maestral
pkgver=1.9.2
pkgrel=1
pkgdesc='A light-weight and open-source Dropbox client'
arch=('any')
url="https://github.com/SamSchott/maestral"
license=('MIT')
depends=('hicolor-icon-theme'
         'python'
         'python-click'
         'python-desktop-notifier'
         'python-dropbox'
         'python-fasteners'
         'python-importlib-metadata'
         'python-keyring'
         'python-keyrings-alt'
         'python-packaging'
         'python-pathspec'
         'python-pyro5'
         'python-requests'
         'python-rich'
         'python-setuptools'
         'python-survey'
         'python-typing_extensions'
         'python-watchdog'
         'python-xattr')
makedepends=('python-build'
             'python-installer'
             'python-wheel'
#             'python-sphinx'
#             'python-sphinx-autoapi'
#             'python-sphinx_rtd_theme'
#             'python-sphinx_mdinclude'
#             'python-sphinxext-opengraph')
)
checkdepends=('python-pytest')
optdepends=('maestral-qt: Qt interface for the maestral daemon'
            'python-systemd: Syslog support')
source=("$pkgname-$pkgver.tar.gz::$url/archive/v$pkgver.tar.gz")
sha256sums=('f9e1a54204082c006067aec8a224704a9c7c37977a9a4b06f308992b3205ec5e')

build() {
	cd "$pkgname-$pkgver"
	python -m build --wheel --no-isolation
#	cd docs
#	sphinx-build -b man ./ ./_build/man/
}

check() {
	cd "$pkgname-$pkgver"
	PYTHONPATH=src/ pytest -k 'not test_autostart and not benchmark' -x --disable-warnings
}

package() {
	cd "$pkgname-$pkgver"
	python -m installer --destdir="${pkgdir}/" dist/*.whl
	install -Dvm644 README.md -t "${pkgdir}/usr/share/doc/$pkgname/"
#	install -Dvm644 docs/_build/man/maestral.1 -t "${pkgdir}/usr/share/man/man1/"
	install -Dvm644 LICENSE.txt "${pkgdir}/usr/share/licenses/$pkgname/LICENSE"
}
