### ISSUE TITLE
[ISSUE] Maestral is very resource hungry in 5-10 minutes cycles 

### ISSUE THREAD

**Issue by T0mu** [SamSchott/maestral#114]
Hi Sam,
I am trying to update a massive folder and my laptop vent is going crazy.
I checked Reesource monitor and Maestral task is gobbling from 120 to 160% resources.
See screenshot.
<img width="898" alt="partial screenshot 2020-04-08 alle 11 53 03" src="https://user-images.githubusercontent.com/14136369/78771340-4f3ef900-7990-11ea-9a9f-a8e1cb52410f.png">

After a while it went back to normal behaviour while still updating...

<img width="905" alt="partial screenshot 2020-04-08 alle 11 57 40" src="https://user-images.githubusercontent.com/14136369/78771344-51a15300-7990-11ea-94da-09e8b40068e7.png">

And then after 3 minutes back to full force...

<img width="913" alt="partial screenshot 2020-04-08 alle 12 00 16" src="https://user-images.githubusercontent.com/14136369/78771544-9cbb6600-7990-11ea-8c34-8e61e61b9638.png">

 - Maestral version: 0.6.3
 - OS: Macos Catalina

**Comment by SamSchott** [comment]
That may happen with large folders. Just out of interest, how many items are inside it? And how many GB are we talking about?

As documented in the [wiki](https://github.com/SamSchott/maestral-dropbox/wiki/Config-File), there is an option in the config file called `max_cpu_percent` which limits the CPU usage. It is defined per virtual CPU core, i.e., the default value of 20% means 80% on a dual core processor with hyperthreading. You can change this to a lower value and restart Maestral. However, this is not a guarantee that the CPU usage will remain below the limit.

**Comment by T0mu** [comment]
Plenty of files, more than 30k.
It's a business “pool" account shared internally with 500 gb of data, I sync roughly 100 gb of it.
I will try the switch in the ini file and set it to 10%…
It’s not a matter of CPU usage, I’ve a 4 cores CPU, but what matters me most is fan and temp…
As a side note: I verified (in 10.6.3 at the moment) when I pause sync the app tends to get totally unresponsive (spinning beachball if I hover on the taskbar) and even letting it be tens of minutes it does not fix it and the sync operation goes on….
I will try latest release.
Thank you again!






________________________________
Da: SamSchott <notifications@github.com>
Inviato: mercoledì 8 aprile 2020 22:32
A: SamSchott/maestral-dropbox <maestral-dropbox@noreply.github.com>
Cc: T0mu <t.munari@outlook.com>; Author <author@noreply.github.com>
Oggetto: Re: [SamSchott/maestral-dropbox] [ISSUE] Maestral is very resource hungry in 5-10 minutes cycles (#114)


That may happen with large folders. Just out of interest, how many items are inside it? And how many GB are we talking about?

As documented in the wiki<https://github.com/SamSchott/maestral-dropbox/wiki/Config-File>, there is an option in the config file called max_cpu_percent which limits the CPU usage. It is defined per virtual CPU core, i.e., the default value of 20% means 80% on a dual core processor with hyperthreading. You can change this to a lower value and restart Maestral. However, this is not a guarantee that the CPU usage will remain below the limit.

**Comment by SamSchott** [comment]
It is actually a matter of CPU usage. Short peaks are typically fine but prolonged high CPU usage causes PCs, especially laptops, to heat up and fans to spin. If it's a quad core CPU, it will likely have 8 virtual cores and therefore an effective limit of 160% CPU usage with default settings. This would match your observations. Without the limit, Maestral would go up to almost 800% if available.

Regarding the pausing, this is a known issue. Maestral will eventually pause, but only once all queued changes have been synced. I should work on this at some point...

**Comment by SamSchott** [comment]
Did reducing the `max_cpu_percent` value help? If yes, I'll close this issue.

**Comment by T0mu** [comment]
yes, sorry for no follow up.
I have to tell you, nevertheless, large dropbox syncs are very very slow...
my 2c. internal vs.external API access seems quite.different...

**Comment by SamSchott** [comment]
> internal vs.external API access seems quite.different

You are probably right. After a certain number of API requests, Dropbox asks clients to back off for some time. This doesn't seem to be a problem for medium sized syncs (< 10k items) but becomes noticeable eventually.

I will check how much of the performance issues come from Maestral itself but my suspicion is that its mainly the API. I went through a round of profiling and optimisation for v0.6.2 which introduced significant speedups: indexing 30k files from Dropbox servers should roughly take 5 - 10 min, any additional time comes from downloads and rate limiting.

**Comment by SamSchott** [comment]
How slow is "very very slow"?

**Comment by T0mu** [comment]
> How slow is "very very slow"?

I May not be the best Guinea Pig for this evaluation since I suffer a lot of interfering factors on the experiment.

1) I mainly tested the sync through my dead slow adsl at home when I had to sync a new laptop to our shared Dropbox business at the office (roughly 50gb ofdata). really no way to sync it in a human scale.

while my personal account dropbox (10gb, more or less) synchronized some how.
even when I went to the office to sync the laptop on the lan+Gb-fiber it was sensibly slower.

i suppose my feeling is connected to these  2 other bias.
2) dropbox lan clients sync (I strongly suppose it works only for internal api) and
3) isps mandated speed throttling durnign the pandemic.

if you sum these app you can understand why I had to switch back to the dropbox original client for this profile...

**Comment by SamSchott** [comment]
That makes sense. And you are right, Dropbox does not provide an API for lan sync. I would have to code it from scratch and that would be quite a bit of work...

I'll close this for now.
