### ISSUE TITLE
[Question] Mac switch from GUI to terminal version

### ISSUE THREAD

**Issue by cotfas** [SamSchott/maestral#119]
How can I switch when I want to the terminal version instead of the GUI one?

Mac Catalina 10.15.4
Maestral v0.6.4

**Comment by SamSchott** [comment]
This is currently not possible with the macOS app bundle, unfortunately. You will have to install the Python package instead. But its planned for the 1.0.0 release to bundle the command line tool together with app and provide an option in the GUI.

**Comment by SamSchott** [comment]
A first usable beta for v1.0.0 is out and it includes support for the command line tool. If you like, you can try it out from https://github.com/SamSchott/maestral-dropbox/releases/tag/v1.0.0.dev4.

Feedback is welcome!

**Comment by cotfas** [comment]
Tnx, will keep you posted. :)
