### ISSUE TITLE
[BUG] On mac it started to delete

### ISSUE THREAD

**Issue by cotfas** [SamSchott/maestral#120]
Mac Catalina 10.15.4
Maestral v0.6.4

I had Drobox official v94.4.384 pointing to ~/Dropbox and running

Made a backup of ~/Dropbox

Made a copy of the Dropbox folder to ~/Desktop/Dropbox (Maestral)

*not 100%, if I`ve removed the .dropbox and the cache from the Dropbox (Maestral), I think I had (I`ve did more tests with one folder sync and fails until I started to migrate everything to Maestral)

Linked the Maestral app to the desktop folder and I think after it finished indexing I`ve noticed activity on the Dropbox official menu icon app, and when I saw in the Maestral it was sending delete actions.. I`ve immediately closed everything, I`ve compared the backup folder that I`ve made before doing anything and I`ve noticed deleted files, also on the dropbox webpage history, the deleted files were arround ~100, and all of them contained in the filename Romanian diacritics and special characters.

I`ve did another setup without Dropbox official running, and no content is lost, checked with BC for folder/files diff.

**Comment by SamSchott** [comment]
Thanks for the report, this is concerning. The haven't been any problems with other unicode characters in file names (such as Chinese) so I am surprised. Also, Maestral should just ignore the old Dropbox cache and build its own so any leftover `.dropbox` folder should not be an issue.

Could you maybe provide steps or example file names to reproduce this?

**Comment by cotfas** [comment]
I no longer have the backup so I can compare it, but as I remember I think it were one of the jpg below:

1*7O39AI_BLDrou8xL_vpFww.jpeg

1*9d_6adfxV79XiacUasAe3Q.jpg

And a lot of files with RO diacritics, example of diacritics:
WOW!! Un Discurs Remarcabil. Merită Văzut 100% - Îndrăznește să gândești.mp4

Not sure how the deletion happened, maybe were caused because I had also the Dropbox offical app opened.

**Comment by SamSchott** [comment]
There have been multiple improvements to conflict resolution and parallel changes in the last release and extensive tests have been added. I'll therefore close this issue for now, but feel free to reopen it if it occurs again.
