### ISSUE TITLE
[ISSUE] /.dropbox file not ignored

### ISSUE THREAD

**Issue by nalim** [SamSchott/maestral#121]
For years I have used Dropbox in Windows and Linux (Fedora) with Dropbox folder on a shared (between Windows and Linux) NTFS partition mounted in both Windows and Linux. After the Dropbox company decided to do not support non native filesystems (like NTFS in Linux) any more I have used https://github.com/dark/dropbox-filesystem-fix but recently it has stopped working reliably. So I turned to Maestral. It works great with a minor glitch in my use case. During the each sync, Maestral is trying to sync (upload) /.dropbox file and /.dropbox.cache folder created by Dropbox while running under Windows. Dropbox servers are then refusing to sync these system files when Maestral runs and Maestral notifies me about the sync issues, which is very annoing.

As written here (https://help.dropbox.com/installs-integrations/sync-uploads/files-not-syncing), .dropbox file should be ignored but it's not, because is not included in EXCLUDED_FILE_NAMES in constants.py:

EXCLUDED_FILE_NAMES = (
    'desktop.ini', 'thumbs.db', '.ds_store', 'icon\r', '.dropbox.attr',
    '.com.apple.timemachine.supported', OLD_REV_FILE
)

I solved the problem temporarily by creating /.mignore file with following content:

.dropbox
.dropbox.cache

Is this the proper way how to handle my problem?

Wouldn't be better to include those two files in EXCLUDED_FILE_NAMES?

**Comment by SamSchott** [comment]
> Is this the proper way how to handle my problem?

For now, this is the only way...

> Wouldn't be better to include those two files in EXCLUDED_FILE_NAMES?

I think this would make sense. Thanks for the report!
