### ISSUE TITLE
[BUG] Maestral on startup completely fills up /tmp directory.

### ISSUE THREAD

**Issue by bbaserdem** [SamSchott/maestral#122]
**Describe the bug**
When I start maestral to sync my dropbox files (cli version) my /tmp directory (8G) automatically gets filled; then I get a lot of `Could not sync` errors.

**To Reproduce**
Start maestral.

**Expected behaviour**
My `/tmp` directory to not be completely filled up.

**System (please complete the following information):**
 - Maestral version: 0.6.4
 - OS: Archlinux
 - Desktop environment: bspwm
 - Qt version: 5.14.2

**Additional context**
This is a fresh sync.

**Comment by SamSchott** [comment]
The `$TMP` directory is used as a staging ground for downloads and files are moved to your Dropbox folder only once the download has completed. Since up to 8 downloads are carried out parallel, this may use quite a bit of space in your temp folder. This of course requires that `$TMP` lies in a partition with sufficient space.

For now, you can set the `$TMP` environment variable for Maestral's process to a different location. In the future, it may make sense for me to ensure that unfinished downloads always live in the same partition as the Dropbox folder

**Comment by bbaserdem** [comment]
Thank you. I will use the workaround.

If the total size of the temporary files and the Maestral directory won't exceed the actual total size of the dropbox files, (that are marked to be synced) it might be useful to use `~/.cache/maestral` as the default temporary target. My use case is I work with brain imaging data and I use dropbox to share files with collegues; so sometimes we do data dumps around 100s of GBs. I can see defaulting to tmpfs is useful in the case of small file sharing; but in general it is very easy for certain usecases to exceed RAM capabilities. The default to user directory would help; since the default partition that you are synching to would be assumed to have enough free space to house your dropbox instance.

**Comment by SamSchott** [comment]
Dropbox itself actually uses a hidden folder `.dropbox` inside the local Dropbox folder. This is guaranteed to be on the same partition. The advantage of `$TMP` is that it's content gets deleted on every reboot automatically.

**Comment by coxackie** [comment]
Mabe it makes more sense to follow dropbox's paradigm here and use a similar hidden `.maestral` file inside the folder that should not be synced. But I can see it can lead to troubles if one uses both dropbox and maestral for syncing...

**Comment by peterhoeg** [comment]
> This is guaranteed to be on the same partition.

That is a Very-Good-Thing(tm). 

For large files, you definitely want to avoid the io when copying things over.

**Comment by SamSchott** [comment]
Done. I’ll add a warning to the Readme about syncing a folder with both clients at once, this could lead to a whole range of circular syncs...
