### ISSUE TITLE
Question, if connection interrupts?

### ISSUE THREAD

**Issue by cotfas** [SamSchott/maestral#123]
What happens if connection interrupts in the middle of download/uploading data (or pc restart)? It will continue where it left ?

**Comment by SamSchott** [comment]
A file will only be moved to your local Dropbox folder once it has been fully downloaded, the download itself takes place to a temporary location. Any interrupted downloads will be restarted from the beginning once Maestral is running again, in the meantime your Dropbox folder will look like the download never started...
