### ISSUE TITLE
[BUG] GUI interface causes GNOME to slow to a crawl in Pop_OS! 20.04

### ISSUE THREAD

**Issue by readtedium** [SamSchott/maestral#130]
**Describe the bug**
After trying out the Pop_OS! 20.04 beta, the Gnome interface slowed to the point where it was completely unusable—where it would take nearly a minute to register a click—and the only thing that allowed it to work again was to shut down the GUI interface to Maestral. Running the CLI version of the application did not present this problem.

I’m not sure if this is a Qt or Gnome issue or something on Maestral’s end but it was a showstopper.

**To Reproduce**
Run the latest version of Pop_OS! and Gnome, load up the Maestral GUI. 

**Expected behaviour**
Normal behavior without slowdown.

**System (please complete the following information):**
 - Maestral version: 0.64
 - OS: Pop_OS! 20.04 Beta
 - Desktop environment: Gnome 3.36 (Pop_OS! variant)
 - Qt version: 5.14

**Additional context**
Pop_OS! 20.04 should be out in the next couple of days if that matters.

**Comment by SamSchott** [comment]
I've seen the same on Ubuntu 20.04. This seems to be a general issue with the Qt system tray icon and Gnome 3.36 but I haven't identified the problem yet.

**Comment by SamSchott** [comment]
Could you try to set the environment variable `QT_AUTO_SCREEN_SCALE_FACTOR=0` before launching the GUI? Does this help?

**Comment by readtedium** [comment]
That actually did the trick, seems to be working well after a few seconds of trying. Will keep an eye on this for now.

**Comment by SamSchott** [comment]
Ok, then it is very likely an issue with high dpi support in Qt on Gnome 3.36. There hopefully is a better workaround than just disabling it. But it might not be straight forward.

**Comment by SamSchott** [comment]
It turns out that this is a really coincidental combination of a bug in Qt system tray icons when HiDPI scaling is enabled and changes made to the appindicator for Gnome 3.36. Fixing it would require fixes to either, for now I can only include a workaround which alleviates the problem.

**Comment by readtedium** [comment]
Sounds good—obviously annoying, but glad we caught it. I’ll leave this open for now until something shifts on the workaround front or with the external bugs.

**Comment by SamSchott** [comment]
Yes, thanks for the report! I have filed issues with both Qt and the appindicator shell extension. The Qt folks have acknowledged the issue but it won't be fixed any time soon.

The next release will have workaround which both reduces the frequency of icon changes and does not install icons in the platform theme (which are converted by QSystemTrayIcon into unnecessarily large 512 x 512 pixmaps).
