### ISSUE TITLE
installing on Mint Linux 19.3 get to python3 -m pip install --upgrade maestral[gui] and have following error

### ISSUE THREAD

**Issue by remixedcat** [SamSchott/maestral#141]
`Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-n8ic95jt/PyQt5/`

is what happens when I run:
python3 -m pip install --upgrade maestral[gui]

**Comment by SamSchott** [comment]
Which version of pip are you using? Could you upgrade to the latest and try again?

**Comment by remixedcat** [comment]
9.0.1.3

**Comment by remixedcat** [comment]
python3 -m pip install -U pip

I found that one another site and I was able to get the GUI to run.... 

strangeness

**Comment by SamSchott** [comment]
That is quite an old version, the latest is 20.1. Could you try to update pip? There are apparently  issues with installing PyQt5 with some older versions.

**Comment by remixedcat** [comment]
I'll try but that seems to be working for now. I there is a problem I will try that. thank you

**Comment by SamSchott** [comment]
Ok, glad it worked out.
