### ISSUE TITLE
[BUG] CPU activity when the app is paused syncing

### ISSUE THREAD

**Issue by cotfas** [SamSchott/maestral#142]
Catalina 10.15.4
Maestral 1.0.2

<img width="1047" alt="cpu" src="https://user-images.githubusercontent.com/3340367/81699820-86616800-9470-11ea-98c7-64309e8636ab.png">

[cpuActivity.mov.zip](https://github.com/SamSchott/maestral/files/4615992/cpuActivity.mov.zip)

See the attached files, I see it is still doing CPU activity when the Maestral app is paused syncing.

**Comment by cotfas** [comment]
Also when the app is still in pause, it has energy impact on the battery..

<img width="1559" alt="image" src="https://user-images.githubusercontent.com/3340367/81703605-7ef08d80-9475-11ea-8a48-dde30803cf0d.png">

I normally put the Maestral app on pause when I`m on battery or I need the full bandwidth of the internet and CPU/RAM resources for intensive work.

**Comment by SamSchott** [comment]
Yes, I am aware of the issue and already have a fix for the next release...

**Comment by SamSchott** [comment]
It's the GUI and not the daemon process which is causing the high CPU usage. Therefore, you can mitigate this by running the daemon without the GUI through the command line interface for now.

It's not as convenient, unfortunately, but you can start a GUI as necessary and it will attach itself to the running daemon. You'll notice that the "Quit Maestral" menu entry changes to "Quit Maestral GUI" which indicates that quitting the GUI will leave the daemon running.

**Comment by cotfas** [comment]
Yes, but I kinda need the statusbar to know what is going on.. :(

**Comment by cotfas** [comment]
If I`m switching to the terminal version from the GUI, I can switch it back with cli:

maestral gui

And to pause/start:

maestral pause|resume

And to see what has been synced:

maestral status

Do I have to do the:

maestral autostart

To register it with Mac startup?

Right?

**Comment by SamSchott** [comment]
Yes! Although `maestral autostart` only registers the daemon to start on login and not the GUI.

I'll see if I can get a beta release out with bug fixes soon.

**Comment by cotfas** [comment]
From the GUI I have disabled the autostartup, and from the CLI when I do:

maestral autostart

I get:

Autostart is disabled.

I did not restarted my mac yet to see if is ok.

**Comment by cotfas** [comment]
It does not restart the daemon on mac restart.

cotfas:~ work$ maestral status
Maestral daemon is not running.

And after restart, I got again the GUI maestral dialog error from https://github.com/SamSchott/maestral/issues/137

**Comment by SamSchott** [comment]
The GUI command to enable autostart is:
```
maestral autostart -Y
```
`maestral autostart` only returns the current status. Yeah, I am working on #137 but its difficult to debug...

**Comment by cotfas** [comment]
cotfas:~ work$ maestral autostart -Y
Enabled start on login.
cotfas:~ work$ maestral autostart
Autostart is enabled.
cotfas:~ work$

Perfect :)

Maybe update the repo readme file to be updated with the commands for mac as well, I did not knew about -Y param.

And the help guide does not give to much info:

cotfas:~ work$ maestral -h
usage: main [-h] [-c CONFIG_NAME] [--cli] [--frozen-daemon]

optional arguments:
  -h, --help            show this help message and exit
  -c CONFIG_NAME, --config-name CONFIG_NAME
                        Configuration name
  --cli                 Forward calls to CLI.
  --frozen-daemon       Start daemon only
cotfas:~ work$

**Comment by cotfas** [comment]
Will let you know on next reboot if the maestral autostart -Y worked. Thanks.

**Comment by cotfas** [comment]
Wow, definitely will use the daemon/cli instead of GUI from now on as I see the memory/cpu/energy impact looks way better.

@SamSchott good job, keep up the goos work, don`t forget about https://github.com/SamSchott/maestral/issues/144 please. :)

**Comment by SamSchott** [comment]
There is a beta out now which reduces the CPU usage of the GUI to more reasonable levels.

> Wow, definitely will use the daemon/cli instead of GUI from now on as I see the memory/cpu/energy impact looks way better.

Yes, the cocoa UI uses about as much memory as the daemon itself...
