### ISSUE TITLE
[BUG] Broken "Show Online" link for file that could not be downloaded

### ISSUE THREAD

**Issue by mcaskill** [SamSchott/maestral#143]
**Describe the bug**

A file in my Dropbox can't be downloaded (probably because of legal restrictions) but I can't figure which file this is.

Maestral tries to download it regularly which ends up polluting the output of `maestral status` and the _Sync Issues_ dialog (which slows the GUI down as the notifications stack up).

Note: I am masking the revision identifier with zeroes, just in case (I don't know how sensitive that information is).

> rev:0000000000000000
> Could not download file. The file cannot be transferred because the content is restricted. For example, sometimes there are legal restrictions due to copyright claims.

From the _Sync Issues_ dialog, I have "Show in Finder" and "Show Online" buttons. The former, on click, does nothing and the latter, on click, sends me to a page not found. I've been unable to find a working URI for previewing revisions.

> https://www.dropbox.com/previewrev%3A0000000000000000

**To Reproduce**

To reproduce the behaviour, I suppose one should upload a file that is protected and cannot be manipulated by the public API.

**Expected behaviour**

I would expect the "Show Online" button send me to the file's location on the Dropbox website for me to replace or remove. Also, I would expect to be given the name of the file instead of its revision identifier.

**System (please complete the following information):**

 - Maestral version: v1.0.2
 - OS: macOS v10.14.6
 - Qt version: _Unknown_

Thanks

**Comment by SamSchott** [comment]
Ah, damn. It should not show the rev number but the file path instead. This was an oversight on my part. There is currently no way to generate a preview URL from a rev number. But if you are using the Python package, you can get infos on the offending file as follows:

```python
from maestral.main import Maestral

m = Maestral()
md = m.client.get_metadata('rev:015982ea314dac40000000154e40990')
print(md.path_display)
```

Otherwise, you will need to wait until it is fixed.

> Maestral tries to download it regularly which ends up polluting the output of maestral status and the Sync Issues dialog (which slows the GUI down as the notifications stack up).

How often is the download retried? This should only happen when you pause and resume syncing. And do all the entries show the same "rev"? If not, then we are talking about multiple files or remote changes to the protected file.

**Comment by SamSchott** [comment]
Also, if you identify the file and it is not too large (or private), would you mind sharing? As you have noticed, I am still lacking a way to test the handling of download errors.

**Comment by mcaskill** [comment]
> […] if you are using the Python package […]

I'm using the app bundle. I can install the Python package instead to try and run the snippet you've shared.

> How often is the download retried? This should only happen when you pause and resume syncing.

Not sure what the frequency is but I have noticed it occurring one to four times after waking the computer. For example today, since booting my computer this morning, I've got twelve sync issue notifications so far:

1. Two after initial log-in, two after restarting just the daemon,
2. Two after waking my screen (display turns off after 3 minutes of inactvitiy), and finally
3. Four after waking my screen and logging-back in (requires password after 5 minutes).
4. Two after waking my screen after clicking "Sleep"

In case this is informative: When I have the menu bar icon and daemon active, I have two processes in the Activity Monitor. Only one process when its just the daemon running. I have Maestral configured to autostart but I don't see it in my _Login Items_.

> And do all the entries show the same "rev"? If not, then we are talking about multiple files or remote changes to the protected file.

Yes, I forgot to mention that it is always the same revision number. So a single file is stirring all this trouble.

I've tried diffing the original Dropbox and the new Maestral folders but nothing stands out. I've got a number of files with diacritics in the file names, so they appear in both but character set used is different. There's one GIF file I have that does not sync to Maestral but after removing it and triggering a sync, the issue still arises for the same file.

> Also, if you identify the file and it is not too large (or private), would you mind sharing?

Will do.

**Comment by mcaskill** [comment]
So, it was the GIF after all. A silly animation I've had in Dropbox since ~2014.

![nope](https://user-images.githubusercontent.com/29353/81825320-81e68f00-9504-11ea-9be5-e6115c1ac9f2.gif)

It started generating a new revision number after restoring the file. I've permanently deleted the file.

Here's the output from Python:

```python
>>> from maestral.main import Maestral
>>> m = Maestral()
>>> md = m.client.get_metadata('rev:4595330f000974b4')
>>> print(md.path_display)
/photos/Miscellaneous/nope.gif
>>> md = m.client.get_metadata('rev:5a5881be8f257000974b4')
>>> print(md.path_display)
/photos/Miscellaneous/nope.gif
```

**Comment by mcaskill** [comment]
Hrm. I now have this "Unexpected error" from Maestral. From `maestral log show`:

```
2020-05-13 10:43:34 maestral.sync INFO: Downloading rev:5a5881be8f257000974b4...
2020-05-13 10:43:34 maestral.sync ERROR: Unexpected error
Traceback (most recent call last):
  File "maestral/sync.py", line 2741, in startup_worker
  File "maestral/sync.py", line 1990, in get_remote_item
AttributeError: 'NoneType' object has no attribute 'path_display'
```

I've rebuilt the index and tried restarting but the issue persists.

```
2020-05-13 10:45:57 maestral.sync INFO: Downloading rev:4595330f000974b4...
2020-05-13 10:45:57 maestral.sync ERROR: Unexpected error
Traceback (most recent call last):
  File "maestral/sync.py", line 2741, in startup_worker
  File "maestral/sync.py", line 1990, in get_remote_item
AttributeError: 'NoneType' object has no attribute 'path_display'
```

The revision numbers are for that same GIF that is now permanently deleted.

**Comment by SamSchott** [comment]
Ah, so those where your error reports. I was wondering where they came from. Maestral is retrying failed downloads from the last run, however the saved rev number is not a valid path and it crashes...

You can fix this again through Python by clearing all saved download errors, just make sure to quit the app and all running daemons first:

```python
from maestral.main import Maestral

m = Maestral()
m.sync.download_errors.clear()
```

Also, thank you for the GIF. It is exactly what I needed: a small file which is DMCA protected (for some obscure reason).

**Comment by mcaskill** [comment]
Thanks for the extra snippet.

Is there a way to import `Maestral` from the app bundle?
I was only able to do that from the pip version.

**Comment by SamSchott** [comment]
Of course, sorry about the trouble.

> Is there a way to import Maestral from the app bundle?

No, there is is not. The app bundle ships with its own Python interpreter (about 4 MB of the 20 MB app size) which is not accessible from the outside...

**Comment by mcaskill** [comment]
That's what I thought. I've reinstalled the pip variant to run the routine above to clear download errors. Unfortunately, the error returns:

```
2020-05-13 12:57:44 maestral.sync INFO: Resuming interrupted downloads...
2020-05-13 12:57:44 maestral.sync INFO: Downloading rev:4595330f000974b4...
2020-05-13 12:57:44 maestral.sync ERROR: Unexpected error
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/maestral/sync.py", line 2741, in startup_worker
    sync.get_remote_item(dbx_path)
  File "/usr/local/lib/python3.7/site-packages/maestral/sync.py", line 1990, in get_remote_item
    with InQueue(self.queue_downloading, md.path_display):
AttributeError: 'NoneType' object has no attribute 'path_display'
```

Maybe there's another store that needs clearing that holds the list of "interrupted downloads".

Anything in `~/Library/Application Support/maestral` that I could edit to delete?

**Comment by mcaskill** [comment]
Found the offending revisions in:

```
~/Library/Application Support/maestral/maestral.state
```

By clearing the array `pending_downloads`, the error no longer arises.

I presume the `download_errors` is what you made me clear with your Python snippet.

**Comment by SamSchott** [comment]
Yes! I had forgotten about that one...

**Comment by mcaskill** [comment]
Thank you for your help. It's been an enlightening topic to explore and your support was much appreciated.
