### ISSUE TITLE
[Suggestion] For maestral CLI status command enhancement

### ISSUE THREAD

**Issue by cotfas** [SamSchott/maestral#144]
Catalina 10.15.4
Maestral 1.0.2

I see the maestral status command, will be nice to have a list with last ~25 files that were last synched along with UP/DOWN if were uploaded or downloaded, and date timestamp, maybe the full path of the files as well, will be nice to know where the files are located, also maybe if I hold CMD and click on a file path to open the folder location in finder.

**Comment by SamSchott** [comment]
Good suggestion. This should be easy to implement, apart from the clickable paths.

**Comment by cotfas** [comment]
I see in iTerm

cotfas:~ work$ pwd
/Users/work
cotfas:~ work$

When holding COMMAND and hovering on the path, it gets blue, and when clicking it, it opens the folder path in Finder.

I think basically if the list will contain a space between fullpath and filename it should work nativelly.

**Comment by cotfas** [comment]
Will really need the last synched files in CLI to know what is going on. :)

**Comment by SamSchott** [comment]
> When holding COMMAND and hovering on the path, it gets blue, and when clicking it, it opens the folder path in Finder.

That does seem to be a function of the terminal itself, just like URLs are clickable. Good to know.

**Comment by SamSchott** [comment]
v1.2.0 introduces the command `maestral history` to show last week's sync events. However, not the full local path is shown because those can be very long.
