### ISSUE TITLE
Migrate state information and file index to database

### ISSUE THREAD

**Issue by SamSchott** [SamSchott/maestral#147]
We currently abuse the config file API and its INI format to store state information and use a custom file format for the sync index. This is feasible because there is currently very little saved state such as sync cursors, selective sync settings, account info and a log of the last 50 file changes.

Advantages of the current approach:

- State and index files can be read by humans and modified with a simple text editor.
- Our current sync index format provides very high performance while still writing every new entry to the drive.
- We don't need to rely on the platform to provide a database such as sqlite or alternatively bundle our own.

Disadvantages:

- The current approach does not scale well. For instance, we may want to maintain a more extensive index of past changes, including user name, local or remote info, etc.
- The sync index is maintained separately and is not easily extendable to include additional metadata such as content hashes, mtimes and more.
- The current format of the index and state files is possibly more susceptible to corruption than a database (this will need to be tested).

**Comment by SamSchott** [comment]
Comments from anyone with experience in database usage are welcome. And if someone would like to take this up, pull requests will be reviewed favourably. Perquisites will be: no significant reduction in performance and  proper handling of crashes or "force quits" of the daemon.

**Comment by cotfas** [comment]
realm.io is a fast DB, not sure if it fits for the programming language or linux, otherwise sqlite should be crossplatform as well.

**Comment by techman83** [comment]
SQLite is simple, well supported and fast. However as pointed out relies on a system dependency and has platform specific caveats. I wonder if [TinyDB](https://pypi.org/project/tinydb/) would be suitable? I haven't personally had a good chance to use it in anger, but is pure python and similar to MongoDB. Though carries the same concurrency limitation that SQLite does.

**Comment by SamSchott** [comment]
All good suggestions, I will have a look and compare. SQlite does seem to be preinstalled on almost all platforms and has become a defacto standard. Are there any caveats beyond different versions on different platforms? I have become a bit weary of taking anything for granted on Linux. 

TinyDB also is a good suggestion since it is Python only and seems to be nice to use. Concurrency can always be enforced with a lock if need be...

**Comment by techman83** [comment]
No platform specific caveats that I'm aware of (apart from Macs being compiled without extension support, which I doubt will be needed), though I'm unsure how widely default installed it is, seems to be on the various flavours of debian/ubuntu I've got quick access to. SQLite itself has some limitations in regards to SQL support, but most of those can be worked around easily enough.

TinyDB would have the advantage of not requiring table create/migrate as it's document store rather than SQL, however as its stored as JSON file may have some performance implications.

**Comment by SamSchott** [comment]
Done in v1.2.0. Thanks for your input!
