### ISSUE TITLE
[Question] Update CLI to new versions?

### ISSUE THREAD

**Issue by cotfas** [SamSchott/maestral#151]
On mac, enabled from gui the cli, I think at version 1.0.0 or something like that, and now the new version arrived.

cotfas:~ work$ maestral status
Maestral v1.0.3 has been released, you have v1.0.3.beta1. Please use your package manager to update.

I have stopped the cli daemon and then I copied the app from the dmg to the /Applications folder, I have went to gui and uninstalled and installed the cli back, and in the terminal I keep seeing is the beta release, this also applies to the GUI, it shows as beta, eventhought I have downloaded the 1.0.3 from the github release tab:
https://github.com/SamSchott/maestral/releases/download/v1.0.3/Maestral.dmg

Anyway, updating from CLI how it is done? is there a command easier to simplify the whole process?

Thank you.

**Comment by SamSchott** [comment]
Sorry about that, the app bundle on GitHub had the wrong release number (even though it actually was production code). So it keeps prompting for an update... I have replaced now with the correct version.

There is however no need to reinstall the CLI. The install button only creates a symlink to the CLI which is contained inside the app bundle. As long as you don’t move the app to a different location, it will keep working through updates.

**Comment by cotfas** [comment]
And when updating to new versions, I guess I have to do a cli maestral stop, then update? Right? :)

**Comment by SamSchott** [comment]
Yes! I don’t think macOS allows you to replace the app while it’s running (at least I hope it doesn’t).
