### ISSUE TITLE
[BUG] Main executable fails on invoking distribution

### ISSUE THREAD

**Issue by bbaserdem** [SamSchott/maestral#158]
**Describe the bug**
I'm getting the following error;
```
Traceback (most recent call last):
  File "/usr/bin/maestral", line 9, in <module>
    for entry_point in distribution('maestral==1.1.0').entry_points:
  File "/usr/lib/python3.8/importlib/metadata.py", line 504, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.8/importlib/metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: maestral==1.1.0
```
Prior to upgrade from 1.0.3 to 1.1.0; maestral was working fine.

**To Reproduce**
Run `maestral` from command line.

**Expected behaviour**
This error to not happen

**System (please complete the following information):**
 - Maestral version: 1.3.0
 - OS: Archlinux
 - Desktop environment: None
 - Qt version: Irrelevant

**Additional context**
I tested running `distribution('numpy')` and `distribution('numpy==1.18.5')` to test how the distribution function is supposed to work; and I'm getting the same error. I suspect this is an issue with `importlib.metadata.distribution` somehow; but I'm not sure what is going on.

**Comment by SamSchott** [comment]
This is strange, AFAIK the `distribution` function does not take the package version as input but just its name.

1. Could you post the content of the entry point at `/usr/bin/maestral`? It is generated automatically during a pip-install and should be:

    ```Python
    #!/usr/bin/python3
    # -*- coding: utf-8 -*-
    import re
    import sys
    from maestral.cli import main
    if __name__ == '__main__':
        sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
        sys.exit(main())
    ```

2. How did you install Maestral?
3. Does the issue persist when downgrading?

**Comment by bbaserdem** [comment]
2. I install using the installation pkgbuild. (I'm very familiar since me and @coxackie wrote it) You can find it [here](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=maestral) If I do a pip install; it does work. For the time being; I assume it is an error with the PKGBUILD for now.
3. The issue does not persist on downgrade. Downgrading to 1.0.3 makes it work like intended.

The downgraded (1.0.3) entry point is as following;

```
#!/usr/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'maestral==1.0.3','console_scripts','maestral'
import re
import sys

try:
    from importlib.metadata import distribution
except ImportError:
    try:
        from importlib_metadata import distribution
    except ImportError:
        from pkg_resources import load_entry_point


def importlib_load_entry_point(spec, group, name):
    dist_name, _, _ = spec.partition('==')
    matches = (
        entry_point
        for entry_point in distribution(dist_name).entry_points
        if entry_point.group == group and entry_point.name == name
    )
    return next(matches).load()


globals().setdefault('load_entry_point', importlib_load_entry_point)


if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(load_entry_point('maestral==1.0.3', 'console_scripts', 'maestral')())
```

The 1.1.0 entry point using pip install (~/.local/bin/maestral) is as following;

```
#!/usr/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'maestral==1.1.0','console_scripts','maestral'
import re
import sys

try:
    from importlib.metadata import distribution
except ImportError:
    try:
        from importlib_metadata import distribution
    except ImportError:
        from pkg_resources import load_entry_point


def importlib_load_entry_point(spec, group, name):
    dist_name, _, _ = spec.partition('==')
    matches = (
        entry_point
        for entry_point in distribution(dist_name).entry_points
        if entry_point.group == group and entry_point.name == name
    )
    return next(matches).load()


globals().setdefault('load_entry_point', importlib_load_entry_point)


if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(load_entry_point('maestral==1.1.0', 'console_scripts', 'maestral')())
```

**Comment by bbaserdem** [comment]
This is strange; yesterday the maestral binary was actually like the one you posted;

```
#!/usr/bin/python3
# -*- coding: utf-8 -*-
import re
import sys
from maestral.cli import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

After posting my issue yesterday; i deleted the 1.1.0 version and downgraded to 1.0.3 to get it working. Today; I rebuilt it to post information about the build. The `/usr/bin/maestral` file generated by the PKGBUILD now reflects the pip 1.1.0 version I posted here; and it works. I don't know what was wrong with the build yesterday; but I guess it can be closed now.

**Comment by SamSchott** [comment]
Those entry points are quite different from what I was expecting but they look fine as well. Glad it's working now.
