### ISSUE TITLE
[BUG] File permissions always set to 0600

### ISSUE THREAD

**Issue by redbeam** [SamSchott/maestral#175]
**Describe the bug**
Every file that Maestral downloads or updates has its permissions set to 0600.

**To Reproduce**
Wait for the daemon to download/update a file that was added/modified. Its permissions will be (re)set to 0600.

**Expected behaviour**
The daemon should create new files with some consistent permissions (umask?) and keep them for updated files.

**System (please complete the following information):**
 - Maestral version: 1.1.0
 - OS: Red Hat Enterprise Linux Server release 7.8 (Maipo)
 - Desktop environment: n/a
 - Qt version: n/a

**Additional context**
I noticed this when I updated a bash script from my home PC (I run Dropbox on it and Maestral on a RHEL server, since Dropbox does not support it). The script had the execute permission set, but after modifying it, the permissions were set to read/write for the owner only (no execute). It was the same for other files.

Eventually, I discovered the source of the problem. Since Maestral uses a temporary file to store new downloads in and then moves that to the final location, it overwrites the existing permissions. The temporary file is created in `_create_local_entry(self, entry)` using the `tempfile` library, which always creates these with mode 0600 ([link](https://hg.python.org/cpython/file/63bde882e311/Lib/tempfile.py#l235)).

I needed a quick fix, so I modified the `sync.py` file.
```python
2528a2529,2535
>                     try:
>                         orig_mode = os.stat(local_path).st_mode & 0o777
>                     except FileNotFoundError:
>                         umask = os.umask(0)
>                         os.umask(umask)
>                         orig_mode = 0o777 & ~umask
>
2529a2537,2539
>
>                     os.chmod(local_path, orig_mode)
```

**Comment by SamSchott** [comment]
Thanks for the report! This does look like something which I should address eventually.

It looks like the official Dropbox client does sync permission metadata where possible, e.g., between Unixes. However, permission metadata is not available through the public API. So for now, the best solution really may be to preserve the previous (local) file permissions unless the file id has changed. This is not ideal since it will not propagate changes in permission between devices.

The next release will include an overhaul of the local index which will then also keep track of unique file / folder IDs. This should help when trying to maintain permissions locally for a file.

**Comment by SamSchott** [comment]
Fixed in v1.2.0. Note that we trigger additional file system events by modified permissions after the move which have to be ignored.

**Comment by m-guggenmos** [comment]
I noticed that maestral 1.2.2 sets all file permissions to 755 after the first sync with Dropbox. Is that intended?

**Comment by SamSchott** [comment]
Well, no, that wasn't intended. No idea how that particular piece of bad code snuck in.

**Comment by m-guggenmos** [comment]
Thanks! Looking forward to the next release

**Comment by redbeam** [comment]
Sorry for reopening this, I just recently noticed another instance of potentially unwanted behavior.

Maestral replaces updated files with a new, renamed temporary file. This inherently destroys any hard links or ACL's on the original file (not even considering UNIX permissions, which have to be set explicitly after the move).

My suggestion is:
What if, instead of `mv`, `cp` was used to apply changes from the temporary file to the original one? It would retain all of the mentioned attributes and would not be difficult to implement.
