### ISSUE TITLE
[BUG] Maestral daemon fails to automatically start with systemd

### ISSUE THREAD

**Issue by wolterhv** [SamSchott/maestral#178]
**Description**

In Arch Linux, with the Maestral daemon as an enabled systemd service, Maestral fails to start automatically. It logs

    Starting Maestral daemon...
    [57B blob data]
    Please check logs for more information.
    maestral.service: Failed with result 'protocol'.
    Failed to start Maestral daemon.

The same messages appear with `journalctl`, and `maestral log show` doesn't show any errors. Which log is being referred to?

**To Reproduce**
1. Install Maestral.
2. Enable as a systemd service (`systemctl enable --user maestral`).
3. Trigger systemd's automatic start of services (e.g. via re-login or reboot).

**Expected behaviour**
Maestral should start automatically without errors.

**System:**

Key | Value
--- | ---
 Maestral version | 1.1.0-1
 OS | Arch Linux, kernel 5.8.4-arch1-1, x86_64
 Desktop environment | Sway (I think this is not relevant in this case, it should start regardless of whether I start my desktop environment)
 Qt version | I'm not using the GUI.

**Comment by SamSchott** [comment]
How did you set up the systemd service? Through `maestral autostart -Y` or manually? There currently is an issue with the systemd unit file when using a custom config name, for instance for syncing a second account.

Could you post a copy of the systemd unit file? If you created it through the CLI, it will be at `~/.local/share/systemd/user/maestral-daemon@.service`. You can also try to disable and reenable it with `maestral autostart -N` followed by `maestral autostart -Y`.

The log is indeed the one shown by `maestral log show`. However, if the exception occurred before logging could be started, it won't be logged there.

**Comment by wolterhv** [comment]
> How did you set up the systemd service? Through maestral autostart -Y or manually? There currently is an issue with the systemd unit file when using a custom config name, for instance for syncing a second account.
>
> Could you post a copy of the systemd unit file? If you created it through the CLI, it will be at ~/.local/share/systemd/user/maestral-daemon@.service. You can also try to disable and reenable it with maestral autostart -N followed by maestral autostart -Y.

I don't quite remember how I set it up, but I did have the maestral-daemon@.service file at the location you mentioned. I post the contents for the sake of information:

`.local/share/systemd/user/maestral-daemon@.service`

```ini
[Unit]
Description = Maestral daemon for the config %i

[Service]
Type = notify
NotifyAccess = exec
ExecStart = /usr/bin/%i start -f -c %i
ExecStop = /usr/bin/%i stop -c %i
WatchdogSec = 30s
ExecStopPost = /usr/bin/env bash -c "if [ ${SERVICE_RESULT} != success]; then notify-send Maestral 'Daemon failed: ${SERVICE_RESULT}'; fi"

[Install]
WantedBy = default.target
```

I also had a file

`.config/systemd/user/maestral.service`

```ini
[Unit]
Description = Maestral daemon
Documentation = https://github.com/SamSchott/maestral-dropbox/wiki

[Service]
Type = notify
NotifyAccess = exec
ExecStart = /usr/bin/maestral start -f
ExecStop = /usr/bin/maestral stop
ExecStopPost=/usr/bin/env bash -c "if [ ${SERVICE_RESULT} != success ];\
then notify-send Maestral 'Daemon failed'; fi"
WatchdogSec = 30s

[Install]
WantedBy = default.target
```

Upon trying to restart them with `systemctl` and the `--user` flag, both fail with the result 'protocol'.

**Comment by wolterhv** [comment]
> How did you set up the systemd service? Through maestral autostart -Y or manually? There currently is an issue with the systemd unit file when using a custom config name, for instance for syncing a second account.
>
> Could you post a copy of the systemd unit file? If you created it through the CLI, it will be at ~/.local/share/systemd/user/maestral-daemon@.service. You can also try to disable and reenable it with maestral autostart -N followed by maestral autostart -Y.

I don't quite remember how I set it up, but I did have the maestral-daemon@.service file at the location you mentioned. I post the contents for the sake of information:

`.local/share/systemd/user/maestral-daemon@.service`

```ini
[Unit]
Description = Maestral daemon for the config %i

[Service]
Type = notify
NotifyAccess = exec
ExecStart = /usr/bin/%i start -f -c %i
ExecStop = /usr/bin/%i stop -c %i
WatchdogSec = 30s
ExecStopPost = /usr/bin/env bash -c "if [ ${SERVICE_RESULT} != success]; then notify-send Maestral 'Daemon failed: ${SERVICE_RESULT}'; fi"

[Install]
WantedBy = default.target
```

I also had a file

`.config/systemd/user/maestral.service`

```ini
[Unit]
Description = Maestral daemon
Documentation = https://github.com/SamSchott/maestral-dropbox/wiki

[Service]
Type = notify
NotifyAccess = exec
ExecStart = /usr/bin/maestral start -f
ExecStop = /usr/bin/maestral stop
ExecStopPost=/usr/bin/env bash -c "if [ ${SERVICE_RESULT} != success ];\
then notify-send Maestral 'Daemon failed'; fi"
WatchdogSec = 30s

[Install]
WantedBy = default.target
```

Upon trying to restart them with `systemctl` and the `--user` flag, both fail with the result 'protocol'.

**Comment by SamSchott** [comment]
Both of those look ok, apart from the the Exec lines in the first file (which was automatically generated with `maestral auto start -Y`). This is the issue which I mentioned. It should not affect you but the correct lines in this file should be:

```ini
ExecStart = /usr/bin/maestral start -f -c %i
ExecStop = /usr/bin/maestral stop -c %i
```

The second file looks like it was added manually at some point. Could you disable both services with `systemctl --user disable maestral-daemon@maestral.service` and `systemctl --user disable maestral.service` and renable only one of them, for instance with `systemctl --user enable maestral.service`?

If the service still fails, could you try to change the service type from `notify` to `exec`, remove the `WatchdogSec` field and again disable and enable the service?

To explain: The failure type “protocol” could mean that Maestral sends the wrong notifications to systemd when it starts up, despite running just fine. Changing the service type to `exec` will tell systemd not to expect any notifications in the first place. I could not reproduce the failure on my Ubuntu VM which makes it more difficult to debug.

**Comment by wolterhv** [comment]
I've disabled the manually added `.config/systemd/user/maestral.service` file.

I've also run `maestral autostart -Y` again.

The file `.local/share/systemd/user/maestral-daemon@.service` has the following contents:

```ini
[Unit]
Description = Maestral daemon for the config %i

[Service]
Type = notify
NotifyAccess = exec
ExecStart = /usr/bin/%i start -f -c %i
ExecStop = /usr/bin/%i stop -c %i
WatchdogSec = 30s
ExecStopPost = /usr/bin/env bash -c "if [ ${SERVICE_RESULT} != success ]; then notify-send Maestral 'Daemon failed: ${SERVICE_RESULT}'; fi"

[Install]
WantedBy = default.target
```

which is the same as in my previous post, but now I have confirmed it starts successfully and remains active. So I have no idea what was happening. My guess is maybe `maestral.service` was interfering somehow.

I'm going to close for now, since this seems no longer an issue! Thanks for your help :)

**Comment by SamSchott** [comment]
Glad to hear that it worked out!
