### ISSUE TITLE
[BUG] Abnormal exit code 255 in Maestral v1.2.0 on macOS

### ISSUE THREAD

**Issue by mcaskill** [SamSchott/maestral#181]
**Describe the bug**

When attempting to launch the latest version of `Maestral.app`, nothing happens (GUI-wise) but the `system.log` records this:

```
Sep 16 12:54:15 com.apple.xpc.launchd[1] (com.samschott.maestral.87356[55539]): Service exited with abnormal code: 255
```

**To Reproduce**

Unknown.

**Expected behaviour**

The application should launch, represented by the menu bar icon.

**System**

 - Maestral version: v1.2.0
 - OS: macOS Mojave v10.14.6
 - Qt version: _Unknown_

**Additional context**

I was previously using Maestral v1.1.0.

**Comment by SamSchott** [comment]
Hrm, I have never seen this before. The bundle was build on macOS Big Sur but with a deployment target of macOS 10.13. It's running just fine on Big Sur... It looks like I'll need to rebuild on a different system.

**Comment by mcaskill** [comment]
Thanks. If there's anything I can do on my end to help diagnose the issue.
I can install PyPI version if ever you suspect the issue is not related to the app bundle.

**Comment by SamSchott** [comment]
Its definitely a problem with building on Big Sur. I rebuilt the bundle on Mojave now and uploaded the new version. Could you test if this works for you?

On my end, the new build runs fine on both Mojave and Big Sur.

**Comment by mcaskill** [comment]
It works on my end, on both of my computers (which both run Mojave). Thanks!

I've now noticed an error that occurs on launch on both computers with Maestral v1.2.0 (not just the first launch):

```
Sep 16 15:31:39 com.apple.xpc.launchd[1] (com.apple.xpc.launchd.domain.pid.Maestral.56800): Could not resolve origin of domain. XPC services in this domain's bundle will not be bootstrapped: error = 107: Malformed bundle, taint = missing executable
```

I can't find in my logs if this occurred in previous versions. Despite the error, Maestral seems to be working fine. I tried with a new file to make sure it syncs.

**Comment by SamSchott** [comment]
It looks like the executable path is incorrectly specified in the bundle plist. It reads `MacOS/Maestral` but should just be `Maestral`. This seems to be this issue https://github.com/pyinstaller/pyinstaller/issues/4413 with Pyinstaller.

**Comment by SamSchott** [comment]
And it's updated yet again, with a corrected executable path. Packaging Python for distribution can be mess.

**Comment by mcaskill** [comment]
I confirm that the console error is gone on my end. Thanks again!

**Comment by SamSchott** [comment]
Excellent. Thanks for reporting.
