### ISSUE TITLE
[BUG] 1.2.0 is not able to read auth token from kwallet

### ISSUE THREAD

**Issue by peterhoeg** [SamSchott/maestral#185]
**Describe the bug**

Version 1.1.0 used kwallet for the auth token, but 1.2.0 says "No supported keyring".

Python keyring does have support for kwallet:

```
$ keyring --list-backends
keyring.backends.kwallet.DBusKeyring (priority: 5.1)
keyring.backends.fail.Keyring (priority: 0)
keyring.backends.chainer.ChainerBackend (priority: -1)
```

**To Reproduce**
1. Launch 1.2.0 with `maestral start --foreground`
2. Do the auth when prompted
3. Observe:
```
Starting Maestral...        [OK]
1. Go to: https://www.dropbox.com/blablabla
2. Click "Allow" (you may have to log in first).
3. Copy the authorization token.
Enter the authorization token here: some_auth_token
 > Credentials written.
 > Warning: No supported keyring found, Dropbox credentials stored in plain text.
```
4. Notice that a plain text token is written to `~/.local/share/python_keyring/keyring_pass.cfg`

**Expected behaviour**
Existing auth token to be read from kwallet or alternatively a new auth token written to 

**System (please complete the following information):**
 - Maestral version: 1.2.0
 - OS: nixos-unstable
 - Desktop environment: KDE Plasma 5.18.5, kf 5.73
 - Qt version: 5.14.5

**Additional context**

Dependencies:
<details>
acl-2.2.53
attr-2.4.48
audit-2.8.5
bash-4.4-p23
bash-interactive-4.4-p23
bzip2-1.0.6.0.1
bzip2-1.0.6.0.1-bin
coreutils-8.31
cracklib-2.9.7
cryptsetup-2.3.3
curl-7.72.0
db-4.8.30
dbus-1.12.20-lib
expat-2.2.8
gcc-9.3.0-lib
gdbm-1.18.1
glib-2.64.5
glibc-2.31
glibc-2.31-bin
gnupg-2.2.23
gnutar-1.32
gzip-1.10
iptables-1.8.5
json-c-0.14
kbd-2.0.4
kexec-tools-2.0.20
keyutils-1.6.1-lib
kmod-27
libapparmor-2.13.4
libassuan-2.5.3
libcap-2.27-lib
libffi-3.3
libffi-3.3-dev
libgcrypt-1.8.6
libgpg-error-1.38
libICE-1.0.10
libidn2-2.3.0
libkrb5-1.18
libmnl-1.0.4
libnetfilter_conntrack-1.0.8
libnfnetlink-1.0.1
libnftnl-1.1.7
libpcap-1.9.1
libseccomp-2.5.0-lib
libselinux-2.9
libSM-1.2.3
libssh2-1.9.0
libunistring-0.9.10
libX11-1.6.8
libXau-1.0.9
libxcb-1.13.1
libXdmcp-1.1.3
libyaml-0.2.5
linux-pam-1.3.1
lvm2-2.03.10-lib
lz4-1.9.2
ncurses-6.2
nghttp2-1.41.0-lib
openssl-1.1.1g
pcre2-10.35
pcre-8.44
popt-1.16
python3-3.8.5
python3.8-argh-0.26.2
python3.8-atomicwrites-1.4.0
python3.8-attrs-19.3.0
python3.8-blinker-1.4
python3.8-bugsnag-3.7.1
python3.8-certifi-2020.6.20
python3.8-cffi-1.14.2
python3.8-cffi-1.14.2-dev
python3.8-chardet-3.0.4
python3.8-click-7.1.2
python3.8-coverage-5.2.1
python3.8-cryptography-3.1
python3.8-cryptography-3.1-dev
python3.8-dbus-next-0.1.4
python3.8-dbus-python-1.2.16
python3.8-dbus-python-1.2.16-dev
python3.8-dropbox-10.4.1
python3.8-entrypoints-0.3
python3.8-fasteners-0.15
python3.8-idna-2.10
python3.8-importlib-metadata-1.7.0
python3.8-jeepney-0.4.3
python3.8-keyring-21.3.1
python3.8-keyrings.alt-3.4.0
python3.8-maestral-1.2.0
python3.8-mock-4.0.2
python3.8-monotonic-1.5
python3.8-more-itertools-8.4.0
python3.8-nose-1.3.7
python3.8-packaging-20.4
python3.8-pathspec-0.8.0
python3.8-pathtools-0.1.2
python3.8-pbr-5.4.5
python3.8-pluggy-0.13.1
python3.8-py-1.9.0
python3.8-pyasn1-0.4.8
python3.8-pycparser-2.20
python3.8-pyOpenSSL-19.1.0
python3.8-pyOpenSSL-19.1.0-dev
python3.8-pyparsing-2.4.6
python3.8-Pyro5-5.11
python3.8-pysocks-1.7.1
python3.8-pytest-5.4.3
python3.8-PyYAML-5.3.1
python3.8-requests-2.24.0
python3.8-sdnotify-0.3.2
python3.8-secretstorage-3.1.1
python3.8-serpent-1.30.2
python3.8-setuptools-47.3.1
python3.8-six-1.15.0
python3.8-SQLAlchemy-1.3.19
python3.8-systemd-234
python3.8-toml-0.10.1
python3.8-tornado-6.0.4
python3.8-u-msgpack-python-2.7.0
python3.8-urllib3-1.25.10
python3.8-watchdog-0.10.3
python3.8-wcwidth-0.2.5
python3.8-WebOb-1.8.6
python3.8-zipp-3.1.0
readline-6.3p08
readline-7.0p5
shadow-4.8
sqlite-3.33.0
systemd-246
util-linux-2.36
util-linux-2.36-bin
xz-5.2.5
zlib-1.2.11
</details>

**Comment by SamSchott** [comment]
Kwallet is definitely supported and indeed seems to be available. I suspect this is related to the keyring not getting unlocked.  If Maestral finds that it cannot *read* from the preferred keyring because it is locked it will raise a `KeyringAccessError` and crash, as you described in #160. If it cannot *write* to that keyring, it will fall back to plain text storage as encountered here.

Do you get any prompts by the system to unlock kwallet? Or could you do so manually before starting Maestral?

Note that once the daemon has picked a keyring backend during linking (even plain text) it will stick with this backend until it is unlinked. You could try to migrate the token manually or unlink maestral relink it but neither will help unless kwallet is actually unlocked.

To confirm that unlocking really is the problem, could you try to run the following Python snippet:

```Python
from maestral.oauth import load_keyring

ring = load_keyring("keyring.backends.kwallet.DBusKeyring")
ring.set_password("Maestral", "accountif", "token")
```

Are there any errors raise, such as `RuntimeError: python-dbus not installed` or `KeyringLocked`?

**Comment by peterhoeg** [comment]
It was working perfectly fine under 1.1.0 - my guess (based on a hunch) is that is has something to do with the introduction of `dbus-next` that in some way conflicts with `python-dbus` but I'll try out your suggestion and report back.

**Comment by SamSchott** [comment]
Any updates on this? I tested kwallet access on KDE Neon and couldn't reproduce the issue.

**Comment by janm91** [comment]
Not sure if this is the same error, but I'm using `kwallet` (the original token is stored there), on Artix linux.


This is what I get with version `1.2.1`:

```shell
> pacman -Qi maestral | grep Version
Version         : 1.2.1-1

> maestral start
Could not connect to DBUS interface
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/maestral/utils/notify_linux.py", line 65, in _init_dbus
    introspection = await self.bus.introspect(
  File "/usr/lib/python3.8/site-packages/dbus_next/aio/message_bus.py", line 133, in introspect
    return await asyncio.wait_for(future, timeout=timeout)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 491, in wait_for
    return fut.result()
  File "/usr/lib/python3.8/site-packages/dbus_next/message_bus.py", line 184, in reply_notify
    BaseMessageBus._check_method_return(reply, err, 's')
  File "/usr/lib/python3.8/site-packages/dbus_next/message_bus.py", line 586, in _check_method_return
    raise DBusError._from_message(msg)
dbus_next.errors.DBusError: The name org.freedesktop.Notifications was not provided by any .service files
1. Go to: https://www.dropbox.com/oauth2/authorize?address_gets_longer_here
2. Click "Allow" (you may have to log in first).
3. Copy the authorization token.
Enter the authorization token here: ^CAborted!
```

After a downgrade to `1.1.0` (nothing else was changed on the system):

```shell
> maestral start
Maestral v1.2.1 has been released, you have v1.1.0. Please use your package manager to update.
Starting Maestral...        [OK]

> maestral status
Maestral v1.2.1 has been released, you have v1.1.0. Please use your package manager to update.

Account:       email@gmail.com
Usage:         97.4% of 2.1 GB used
Status:        Indexing 1510...
Sync errors:   0

~ > maestral status
Maestral v1.2.1 has been released, you have v1.1.0. Please use your package manager to update.

Account:       email@gmail.com
Usage:         97.6% of 2.1 GB used
Status:        Up to date
Sync errors:   0
```

Synced sucessfully.



------------------


@SamSchott The code you wrote works properly (with both `1.1.0` and `1.2.1` maestral installed)

```python
Python 3.8.6 (default, Sep 30 2020, 20:59:51)
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from maestral.oauth import load_keyring
>>> ring = load_keyring("keyring.backends.kwallet.DBusKeyring")
>>> ring.set_password("MaestralTEST", "randomaccount", "token")
>>>
```

![writing_into_wallet_works_2020-10-13_21-52-27](https://user-images.githubusercontent.com/58979871/95909721-41cf5500-0d9f-11eb-991c-c2efb04535c6.png)



Can provide more data if needed.

**Comment by SamSchott** [comment]
@janm91, the error message you see means that Maestral could not find the Dbus interface for desktop notifications. You therefore won't get any notifications for file changes, etc. The message really should only show up in the logs and not typically be printed to the terminal - I'll look into that. But it is safe to ignore it unless you rely on those notifications.

It looks like your Dropbox credentials are stored successfully in the keyring.

**Comment by peterhoeg** [comment]
I can confirm that things started working again with 1.2.1.
