### ISSUE TITLE
[FEATURE] Docker image

### ISSUE THREAD

**Issue by aries1980** [samschott/maestral#187]
I'd like to contribute with an "official" Docker image, built with Github Actions, pushed to Docker Hub.

I already have a Dockerfile, but in order to make it work, it would be handy to make it possible to
- option to log into stdout instead of a file
- option to run the daemon in the foreground

Maybe these are already available, just let me know and I create a Pull Request.

PS: Thanks for your work!

**Comment by SamSchott** [comment]
Nice! A Docker file would be very welcome.

Both are currently available as command line flags  to `maestral start`: ` -f, --foreground` and `-v, --verbose`. The foreground behaviour is still a bit iffy, it will initially start a subprocess to check for and run any setup (linking etc) and then run the sync daemon in the main process. This has already been changed to proper single-process behaviour in the dev branch and will be rolled out in the next release.

Regarding the GUI, it will always start the daemon in a separate process and communicate with it over Unix sockets.

**Comment by aries1980** [comment]
https://github.com/SamSchott/maestral/pull/189 is there. Any feedback are welcome. Enjoy!
