### ISSUE TITLE
[FEATURE] Upgrade Docker base image to 3.9-alpine3.12

### ISSUE THREAD

**Issue by aries1980** [SamSchott/maestral#202]
We are using `python:3.8.6-alpine3.12`. What I propose here is 2-fold:

- Remove the explicit patch version from the `FROM` directive. This means automatically the latest patch version will be used for new builds. Because patch versions should be just bug and security fixes, and we can expect some rigour from a mature project such as Python, the probability of something like "uh-oh, this has worked in the previous version" is non-zero, but small.
- Upgrade to Python 3.9, so you can leverage the newer version of the language.

**Comment by SamSchott** [comment]
Agreed on both points.

Regarding switching to Python 3.9, I'd like to first run a couple of tests to see if there are any issues. But from the list of changes, I don't see anything problematic.

**Comment by SamSchott** [comment]
Closing as this was done with the latest update to the docker file.
