### ISSUE TITLE
Not working on macOS 10.13.6 High Sierra

### ISSUE THREAD

**Issue by fillumina** [SamSchott/maestral#206]
When launched from the cli it returns the following error:

$ ./Maestral
[4214] Error loading Python lib '/Applications/Maestral.app/Contents/MacOS/Python': dlopen: dlopen(/Applications/Maestral.app/Contents/MacOS/Python, 10): Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/Maestral.app/Contents/MacOS/libintl.8.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Applications/Maestral.app/Contents/MacOS/libintl.8.dylib

**Comment by SamSchott** [comment]
Damn, sorry about that. The bundle was built with a deployment target of macOS 10.13 but seems to be a pre-built library (libintl.8.dylib) shipped with a higher target. I will see if I can fix this and upload a new binary.

Does the previous release work for you?

**Comment by fillumina** [comment]
No, it didn't with a similar error but I read that this version should work with High Sierra so I gave it a try.
Thanks a lot for your effort!

**Comment by SamSchott** [comment]
This should be finally fixed the latest release. It turns out that it was a bit more complicated to fix. Not only where some of the support libraries built for a newer version of macOS, the GUI was also using methods and frameworks which were only introduced in later version.

**Comment by stysedo** [comment]
Any chance of bringing back support for macOS High Sierra for the pre-built GUI binary?

**Comment by SamSchott** [comment]
Maybe. I have recently changed the build process and now build all extension modules of dependencies "manually" with GitHub actions instead of downloading wheels from PyPI. This should give better control over compatibility / deployment target.

I'll need to check though if we are using any new APIs which where introduces after High Sierra.

**Comment by SamSchott** [comment]
Yes, apologies, I did not have time yet to look into this. Will need to create a virtual machine with macOS 10.13 first to properly test the binary.

**Comment by stysedo** [comment]
> Yes, apologies, I did not have time yet to look into this. Will need to create a virtual machine with macOS 10.13 first to properly test the binary.

I'm sorry that I made you feel like you should apologize!  I appreciate very much that you are looking into this.

**Comment by SamSchott** [comment]
No worries, I'm just saying that I will get to it eventually :)

**Comment by stysedo** [comment]
Thanks for taking time to bring back support for High Sierra!
Very excited to get rid of the bloated native Dropbox.app.
