### ISSUE TITLE
[FEATURE] Silence notifications about inability to sync particular files

### ISSUE THREAD

**Issue by d1vanov** [SamSchott/maestral#208]
Hi there! Thank you very much for this awesome piece of software that Maestral is!

There some files in my Drobox account which Maestral won't sync. That's fine, I'm aware that Dropbox API imposes limitations on syncing of some files (RestrictedContent error in particular). But what somewhat bothers me is that Maestral would show warning notifications about the inability to sync these files several times a day. It would be really nice to somehow mark the files which won't sync so that Maestral either doesn't even try to sync them or just doesn't show the warning about the inability to sync them. So that I'm not distracted by the notifications which are of little use for me.

How this could be implemented in GUI: some dialog available through the system tray's context menu item (or via some other way) in which the files would be listed which failed to sync the last time. Near these files there would be checkboxes which I could check so that Maestral won't nofity me about the problems with syncing these files again.

**Comment by SamSchott** [comment]
I am glad you find it useful :) And thanks for the suggestion.

I think it makes sense to have a GUI option at the same place where sync issues are reported. I am just not sure about what the option itself should do: it could either suppress all future notifications of this type for this file or add the file to the list of items which are excluded from syncing. The first option would require maintaining a list of suppressed notifications which will be quite a bit of work. The second option has the disadvantage that future changes of the file content will not automatically be synced even though they may now be permitted. Any opinions on which behaviour you would prefer?

For now, I can see two ways for you to suppress those notifications: Either exclude the offending files from syncing in the preferences or change the notification level to only show errors and no warnings. The latter can only be done through the command line with `maestral log level ERROR`.

**Comment by d1vanov** [comment]
Well, for my use case excluding the files from syncing entirely would be ok. If these files won't sync in future even if their sync becomes permitted, it would be entirely on me as a user since I disabled their sync myself. If the list of such excluded files wouldn't be hidden in some secret config file but exposed in a GUI dialog, it would be easy for me to uncheck some checkboxes and try to sync again.

Also thanks a lot for the advice about excluding the offending files from syncing! Somehow I overlooked the existence of selective sync in preferences and it seems to be exactly what I need to get rid of warnings about particular files. If I understand correctly, selective sync functions as an include list while what I'm asking for is an exclude list. Perhaps both could be useful but I can probably get away with include list option for now.

**Comment by SamSchott** [comment]
It's not really transparent from the GUI but selective sync does work as an exclude list: only files or folders which have been excluded are "remembered" and will not be downloaded. Any item which is newly added to your Dropbox will automatically by synced.

The list itself is saved in the config file. This will be at `~/.config/maestral/maestral.ini` on Linux and `~/Library/Application Support/maestral/maestral.ini` on macOS. This is documented in the [wiki](https://github.com/SamSchott/maestral/wiki/Config-File) together with warnings about manually editing configs...

There is also the option of creating a `.mignore` file which works similar to `.gitignore` and will prevent matching local items from being uploaded. I'll again point you to the [wiki](https://github.com/SamSchott/maestral/wiki/mignore).

**Comment by d1vanov** [comment]
Thanks a lot! It seems selective sync covers my needs even better that what I suggested to do :smiley: If you wish, you can close this issue as my use case appears to be fully covered already )

**Comment by SamSchott** [comment]
Alright, I'll close it. However, an option right there in the sync issues list to exclude file might be nice in the future.
