### ISSUE TITLE
Excluded folders (mignore) are still scanned via DirectorySnapshot?

### ISSUE THREAD

**Issue by andrewsali** [SamSchott/maestral#216]
**Is your feature request related to a problem? Please describe.**
I would like to exclude a large folder from being scanned every time Maestral is started, as this takes a considerable time (~30 minutes). It seems that even though it is listed in .mignore, the folder is still re-scanned via DirectorySnapshot .

**Describe the solution you'd like**
Use a custom listdir in DirectorySnapshot that returns immediately (with empty) if the folder matches an entry in .mignore

**Describe alternatives you've considered**
Move the large folder outside of the Dropbox directory - unfortunately not feasible in my setup.

**Additional context**
The excluded folder has tens of thousands of files and is slow to recursively traverse

**Comment by SamSchott** [comment]
That's a really good idea and may also reduce memory usage during the startup scan. Would you be willing to make the changes and submit a PR for this?

**Comment by andrewsali** [comment]
Sure, will give it a try!
