### ISSUE TITLE
[BUG] install maestral[gui] => Command "python setup.py egg_info" failed with error code 1

### ISSUE THREAD

**Issue by hb9eue** [SamSchott/maestral#233]
Hi Nice project an maestral cli works fine.

So I wanted to also install the GUI, but this fails. I have not much knowledge of python, so maybe you could give me a hint what goes wrong:

Collecting markdown2 (from maestral-qt>=1.2.2; sys_platform == "linux" and extra == "gui"->maestral[gui])
  Using cached https://files.pythonhosted.org/packages/a2/d2/6e6ab0d9387c332bf1de205522a8386b48e2dddf332ba6ad71b2ec371110/markdown2-2.3.10-py2.py3-none-any.whl
Collecting PyQt5>=5.9 (from maestral-qt>=1.2.2; sys_platform == "linux" and extra == "gui"->maestral[gui])
  Using cached https://files.pythonhosted.org/packages/1d/31/896dc3dfb6c81c70164019a6cbba6ab037e3af7653d9ca60ccc874ee4c27/PyQt5-5.15.1.tar.gz
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-2ocy7m8t/PyQt5/setup.py'

**Comment by SamSchott** [comment]
That's a very strange error. Which version of pip are you using? Could you upgrade to the latest with `pip3 install -U pip` and try again?

**Comment by hb9eue** [comment]
Thank you, updating pip solved the issue. The version causing the issue is the one provided by the actual debian stable distribution.

**Comment by SamSchott** [comment]
Yes, I have seen similar reports before. I'm glad updating fixed it.
