### ISSUE TITLE
How to hook maestral to existing 'Dropbox' directory? (migration Dropbox => maestral)

### ISSUE THREAD

**Issue by hb9eue** [SamSchott/maestral#239]
Dear Team

I ran in a strange issue. I have an existing /home/$USER/Dropbox directory which I previously synced with the the original 'Dropbox' tools.

Now I want to migrate to Maestral so that folder can reside on a filesystem not supported by Dropbox anymore.

When I select /home/$USER/Dropbox from the GT Gui, maestral creates a new directory

/home/$USER/Dropbox/Dropbox (Maestral)/

When I try to acomplish the same from the command line tool. I get some undefined 'sync errors' and 'permission errors'.

If I try to move the /home/$USER/Dropbox/Dropbox (Maestral)/ maestral wants to delete the whole /home/$USER/Dropbox and re-start syncing from the cloud. Which I rather would prefer not to do as I believe my local version is more up to date.

Is there any was to 'merge' the folders? Or do I have to backup my ~/Dropbox and later restore it after re-creating that Folder with Maestral?

-Benoît-

**Comment by hb9eue** [comment]
Somehow I am lost.... I backed up /home/$USER/Dropbox and deleted that folder.
Then I re-created it from within maestral. But again Maestral created /home/$USER/Dropbox/Dropbox (Maestral)/ and started syncronizing my data in there instead of the desired folder.

How do I get Maestral to use the Folder /home/$USER/Dropbox/ and not create it's own folder with a static name within that folder?

**Comment by SamSchott** [comment]
Sorry about the trouble, this part is badly documented.

There currently is no option in the GUI to select an existing folder, it will always create a new one to prevent any accidental loss of data. However, if you really want to merge an exiting folder with your Dropbox, you can do that with the CLI. However, I would strongly recommend a backup of your data first!

The CLI dialog should go as follows:

```
1. Go to: https://www.dropbox.com/oauth2/authorize? ...
2. Click "Allow" (you might have to log in first).
3. Copy the authorization token.
Enter the authorization token here: ...
 > Credentials written
Please give Dropbox folder location [~/Dropbox (Maestral)]: YOUR_EXITING_FOLDER
Directory "YOUR_EXITING_FOLDER" already exists.
Do you want to replace it or merge its content with your Dropbox? (replace, merge, cancel): 
```

At this last point, typing `merge` and pressing enter should trigger a download of the remote Dropbox to the existing folder (with possible sync conflicts created). Any new files in that folder to be uploaded afterwards. Neither Maestral nor the Dropbox server will attempt to merge any file changes but will create conflicting copies instead.

Hope this helps.

**Comment by SamSchott** [comment]
Closing since this hopefully is resolved.
