### ISSUE TITLE
Have stopped receiving daemon notifications

### ISSUE THREAD

**Issue by coxackie** [SamSchott/maestral#242]
**Describe the bug**
For some time now (maybe more than a month or so) I am not receiving any daemon notifications for changed files (when I do know that collaborators are working on them). `maestral notify level` returns `Notification level: FILECHANGE` as it should. I can produce more info upon request.

**To Reproduce**
Not sure if reproducible in other machines, but from description it is obvious what is happening.

**Expected behaviour**
I receive dem sweet sweet notifications.

**System (please complete the following information):**
 - Maestral version: 1.2.1
 - OS: Arch Linux
 - Desktop environment: GNOME 3.38
 - Qt version: N/A (only using cli)

**Comment by SamSchott** [comment]
Oi, that is strange. Can you check the logs for messages that say "Could not connect to DBUS interface" or "Notification failed"?

**Comment by coxackie** [comment]
hmmmm... `dbus_next.errors.DBusError: The name org.freedesktop.Notifications was not provided by any .service files`

Issue with `dbus_next`?

**Comment by SamSchott** [comment]
Issues with connecting to the platforms dbus notification service, not necessary caused by `dbus_next`. Is Maestral the only program affected? And can you send notifications manually with [notify-send](http://manpages.ubuntu.com/manpages/focal/man1/notify-send.1.html)?

**Comment by coxackie** [comment]
yes, notify-send works fine. Here is more info:
```
Nov 27 11:07:14 archer systemd[1115]: Created slice maestral.slice.
Nov 27 11:07:14 archer systemd[1115]: Starting Maestral daemon for config maestral...
Nov 27 11:07:14 archer maestral[1123]: Maestral v1.2.2 has been released, you have v1.2.1. Please use your package manager to update.
Nov 27 11:07:14 archer maestral[1123]: Could not connect to DBUS interface
Nov 27 11:07:14 archer maestral[1123]: Traceback (most recent call last):
Nov 27 11:07:14 archer maestral[1123]:   File "/usr/lib/python3.8/site-packages/maestral/utils/notify_linux.py", line 65, in _init_dbus
Nov 27 11:07:14 archer maestral[1123]:     introspection = await self.bus.introspect(
Nov 27 11:07:14 archer maestral[1123]:   File "/usr/lib/python3.8/site-packages/dbus_next/aio/message_bus.py", line 203, in introspect
Nov 27 11:07:14 archer maestral[1123]:     return await asyncio.wait_for(future, timeout=timeout)
Nov 27 11:07:14 archer maestral[1123]:   File "/usr/lib/python3.8/asyncio/tasks.py", line 491, in wait_for
Nov 27 11:07:14 archer maestral[1123]:     return fut.result()
Nov 27 11:07:14 archer maestral[1123]:   File "/usr/lib/python3.8/site-packages/dbus_next/message_bus.py", line 187, in reply_notify
Nov 27 11:07:14 archer maestral[1123]:     BaseMessageBus._check_method_return(reply, err, 's')
Nov 27 11:07:14 archer maestral[1123]:   File "/usr/lib/python3.8/site-packages/dbus_next/message_bus.py", line 594, in _check_method_return
Nov 27 11:07:14 archer maestral[1123]:     raise DBusError._from_message(msg)
Nov 27 11:07:14 archer maestral[1123]: dbus_next.errors.DBusError: The name org.freedesktop.Notifications was not provided by any .service files
Nov 27 11:07:14 archer dbus-daemon[1128]: [session uid=1000 pid=1128] Activating service name='org.freedesktop.secrets' requested by ':1.15' (uid=1000 pid=1123 comm="/usr/bin/python /usr/bin/maestral start -f -c maes")
Nov 27 11:07:14 archer systemd[1115]: Started Maestral daemon for config maestral.
Nov 27 11:07:14 archer maestral[1123]: Indexing local changes...
Nov 27 11:07:15 archer maestral[1123]: Up to date
```
Note that `maestral` was started via the user `maestral@maestral.service`.

**Comment by SamSchott** [comment]
That's interesting because communication with the system keyring to retrieve the auth token clearly succeeds. You can see that is this line:

```
Nov 27 11:07:14 archer dbus-daemon[1128]: [session uid=1000 pid=1128] Activating service name='org.freedesktop.secrets' requested by ':1.15' (uid=1000 pid=1123 comm="/usr/bin/python /usr/bin/maestral start -f -c maes")
```

However, keyring and its SecretService backend use `jeepney` instead of `dbus_next` to communicate over Dbus.

Do notifications work when you start the daemon manually and not as a systemd service?

**Comment by coxackie** [comment]
In fact, after I `systemctl --user restart` the daemon:
```
Nov 27 13:44:08 archer systemd[1115]: Stopped Maestral daemon for config maestral.
Nov 27 13:44:08 archer systemd[1115]: Starting Maestral daemon for config maestral...
Nov 27 13:44:08 archer maestral[6429]: Maestral v1.2.2 has been released, you have v1.2.1. Please use your package manager to update.
Nov 27 13:44:09 archer systemd[1115]: Started Maestral daemon for config maestral.
Nov 27 13:44:09 archer maestral[6429]: Indexing local changes...
Nov 27 13:44:10 archer maestral[6429]: Up to date
```
all seems ok, and I did get a notification when I changed some files through a different shared dropbox account. SO, it seems to be a problem upon first start. Maybe some other service has not started yet? Not sure how to tell...

**Comment by SamSchott** [comment]
Ok, so this may be a configuration issue with systemd. The desktop environment is in charge of starting the the notification service at login and apparently this happens only after the maestral daemon is started in your case.

It might be possible to wait for the notifications service by configuring the `Wants` and `After` options in the systemd unit file. However, I am not really familiar with the startup routine of Gnome and the service names. I'm afraid you are on your own with this one.

If you do figure out a reliable way, let me know and I'll include it in the default unit file created by maestral.

**Comment by coxackie** [comment]
I cannot figure this out... I ended up disabling the service file, and putting a desktop file in `~/.config/autostart/` that simply starts the user service. Because this happens later in the process of login in, notifications get activated without problem.

**Comment by SamSchott** [comment]
Sure, that way works as well, even though it is really only intended for GUIs. But I think you were on the right track with `dbus.service`. Could try adding the following lines to the unit definition?

```
[Unit]
Wants=dbus.socket
After=dbus.socket
```

I am unfortunately unable to test this here because notifications are working on all my Linux VMs.

**Comment by SamSchott** [comment]
And then of course reload the unit files with `systemctl --user daemon-reload`.

**Comment by coxackie** [comment]
tried it; also with the combinations of adding `dbus.service` to wants and after. Somehow it does not want to work. Oh, well...

**Comment by SamSchott** [comment]
Yeah, then I'm out of ideas 🤷‍♂️

**Comment by coxackie** [comment]
Feel free to close this. If something changes in the future, I will make sure to let you know.
