### ISSUE TITLE
Consider making bugsnag an optional dependency

### ISSUE THREAD

**Issue by coxackie** [SamSchott/maestral#250]
Dependencies not officially supported by distros can be frustrating to deal with, and I am hoping they are kept to a minimum. 

 Specifically, although I totally understand the benefits of `bugsnag` in catching bugs, I also think that users of certain distros (I am thinking Arch here) would anyway post bugs on github, and there is no benefit from this extra dependency.

 If `bugsnag` could be made optional (for example, check whether it is installed, and only use it then), it would help in cutting down the extra number of packages one needs to maintain.

 You can always ship in in the bundled versions, so I do not think there is any harm done here.

 Just my two cents.

**Comment by SamSchott** [comment]
Hm, is this going to be an issue with other dependencies such as [survey](https://github.com/Exahilosys/survey) as well?

**Comment by SamSchott** [comment]
I am quite partial to removing bugsnag completely, especially since the sync daemon itself is seeing very few errors these days. The user base also tends to be programmers (since the project isn't advertised anywhere) and a lot of issues therefore end up on GitHub.

**Comment by coxackie** [comment]
> Hm, is this going to be an issue with other dependencies such as [survey](https://github.com/Exahilosys/survey) as well?

I noticed previously that this is used now, so I opened https://github.com/Exahilosys/survey/issues/5 to ask for github releases. There is of course also the `wrapio` dependency coming along with `survey`. I will add these two in the [AUR](https://aur.archlinux.org/) when the new version of `maestral` comes out.

**Comment by coxackie** [comment]
> I am quite partial to removing bugsnag completely, especially since the sync daemon itself is seeing very few errors these days. The user base also tends to be programmers (since the project isn't advertised anywhere) and a lot of issues therefore end up on GitHub.
> 
> Edit: Having increasingly robust integration tests has also helped.

The number of dependencies that we have to place in the AUR (see comment above) is increasing and making it difficult to maintain. Whatever can be trimmed is very welcome.

**Comment by coxackie** [comment]
OK, this related but maybe is off-topic. But does not require opening a separate issue at the moment.

Still, on dependencies, I tired to update to 1.3.1 for Arch-related users, but:
https://www.archlinux.org/packages/community/any/python-watchdog/
Watchdog is already 10.4. Will not update, as I get an error locally. I can wait until the restriction is lifted in a future version, but now I can see that dependencies are becoming very tight. Of course, I understand from the point of developer's view stability is essential. On the other hand, Arch likes to be bleeding edge. Unless dependencies are only kept with a minimum requirement, this is certain to bring a lot of trouble for Arch packaging.

 Sorry for bringing extra headache. Once again, thanks for your work.

**Comment by SamSchott** [comment]
> Watchdog is already 10.4. Will not update, as I get an error locally. I can wait until the restriction is lifted in a future version, but now I can see that dependencies are becoming very tight.

I really do apologise! This release cycle was a bit of a mess. I felt that my hand was forced by two breaking changes to dependencies: 

* First, watchdog released 0.10.4 which ended up not emitting any file system events on macOS at all. So pinning to < 0.10.3 really is necessary until they fix this and solve their testing issues (they had practically disabled all tests for macOS).
* Then the Dropbox SDK released breaking changes in a minor version, which would cause any fresh install of Maestral from PyPI to fail out of the box. What's more, the forgot to specify new dependencies (https://github.com/dropbox/stone). This was the main reason for my rushed release.

Then, just when I had release v1.3.0, survey decided to completely overhaul the API. The the lesson learned for me is to pin versions at least to the next major release, as long as packages use semantic versioning, or the next minor release if they don't and potentially changes might be seriously unsafe. This especially the case for watchdog where any bugs may not lead to crashes but rather result silent loss of data from incorrect sync events.

For the future, I can offer the following:

* Relax the survey requirement as the project becomes more stable. This will probably be quite soon. It's also a really nice package and once it is picked up by others it's worth having on Arch.
* Drop bugsnag. This will also simplify the code base.
* Keep Dropbox pinned to the current major release.
* Watchdog: I am a bit concerned about this project. They seem to be quite fast and loose with releases for something that is very difficult to get right.

I can probably also adapt my release strategy to have more frequent bug fixes and dependency upgrades and fewer feature releases in between. How does that sound?

**Comment by SamSchott** [comment]
Also, watchdog 0.10.4 might actually be fine on Linux. And really I don't mind you overriding certain dependencies if you know they work on that platform. But it is sometimes difficult for me to keep with testing on some projects.

**Comment by coxackie** [comment]
Many thanks for the detailed response. There was no problem with `survey` and `wrapio` really, as at this point I have control what version to package. But, a lot of other dependencies are not maintained by me, and this is where the trouble lies.

 I think the problem (regarding Arch; not claiming that this is a problem in general) is that packages get upgraded quite quickly. (There are exceptions; a couple of times I had to ping a maintainer to update python-dropbox). This means that if some dependency packages are pinned to a maximum version (or, even worse, to a specific version), they will soon create problems. I cannot argue with maintainers of other packages not to update theirs.

 One option is to *only* have minimum version dependencies. This should be OK in principle with Arch. Otherwise, I guess someone could create a flatpak (somewhat preferable to snap) package which would pull all dependencies sandboxed.

 I understand this is a tough situation, so whatever you choose looking forward is OK.

**Comment by coxackie** [comment]
> Also, watchdog 0.10.4 might actually be fine on Linux. And really I don't mind you overriding certain dependencies if you know they work on that platform. But it is sometimes difficult for me to keep up with testing on some projects.

hmmm, not sure this is OK. I did override the dependency in the `PKGBUILD` file when installing the package, which is perfectly fine, but the `maestral` complained about the dependency when I try to start it. Did you mean for me to actually patch `setup.py`?

**Comment by SamSchott** [comment]
> Did you mean for me to actually patch setup.py?

Possibly. I am not sure how how Arch packaging (or any form of Linux packaging) works. I always imagined that the installation would not be carried out through pip but the platform's package manager which might or might not look at `setup.py`.

The long term target for Linux distribution is to generate an AppImage with [briefcase](https://github.com/beeware/briefcase). Packaging for macOS is already done using briefcase and the macOS GUI uses the sister project [toga](https://github.com/beeware/toga). Once there is feature parity between the the Gtk and Cocoa functionality in toga (I am actively contributing to both), the plan is to migrate the Linux GUI to toga-gtk and finally have a unified code-base and packaging solution. But this may still take a year or longer...

**Comment by coxackie** [comment]
Arch uses `setuptools` for the most part in dealing with native python packaging. I ended up patching `setup.py`, removing a lot of "ceiling" version dependencies, in order not to have things stopping unexpectedly in the near future. In particular, the `watchdog` dependency is now satisfied, and it works ok (again, for the time being).

 In all honesty, I am not very keen in patching releases. It is not the extra work - this is the least of my worries. It is mostly that you know much better what is going on with your project. Therefore, I would respectfully ask that you consider not putting upper limits on package versions, *at least for linux, and as long as they are not absolutely necessary*. You can certainly put all requirements you wish for OSX packaging, but if we could avoid the very tight restrictions for linux (especially in cases where it does not look they create a problem), it would be very helpful. Remember: we are typically happy in providing fast feedback if something looks wrong.

**Comment by SamSchott** [comment]
Closing since the bugsnag has been removed in 1.4.0. I've also removed many of the other upper bounds on dependencies.
