### ISSUE TITLE
[BUG] Maestral 1.30 GUI can't start

### ISSUE THREAD

**Issue by nalim** [SamSchott/maestral#255]
**Describe the bug**
After the upgrade from Maestal 1.23 to 1.30, Maestral GUI can't start

**To Reproduce**
$ maestral gui &
[1] 5509
[votava@azbd ~]$ Traceback (most recent call last):
  File "/home/votava/.local/bin/maestral", line 8, in <module>
    sys.exit(main())
  File "/home/votava/.local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/votava/.local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/votava/.local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/votava/.local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/votava/.local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/votava/.local/lib/python3.9/site-packages/maestral/cli.py", line 668, in gui
    run = default_entry_point.load()
  File "/usr/lib64/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'maestral_qt.app'

**Expected behaviour**
Maestral GUI started and showing an icon in tray area

**System (please complete the following information):**
 - Maestral version: 1.30
 - OS: Fedora 33 (Linux azbd 5.9.11-200.fc33.x86_64 #1 SMP Tue Nov 24 18:18:01 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux)
 - Desktop environment: Cinnamon 4.6.7
 - Qt version: 4.8.7

**Additional context**
$ python3 -m pip install --upgrade --user maestral[gui]
Requirement already up-to-date: maestral[gui] in ./.local/lib/python3.9/site-packages (1.3.0)
Requirement already satisfied, skipping upgrade: alembic<1.5,>=1.3 in ./.local/lib/python3.9/site-packages (from maestral[gui]) (1.4.3)
Requirement already satisfied, skipping upgrade: setuptools in /usr/lib/python3.9/site-packages (from maestral[gui]) (49.1.3)
Requirement already satisfied, skipping upgrade: bugsnag<5.0,>=3.4 in ./.local/lib/python3.9/site-packages (from maestral[gui]) (4.0.1)
Requirement already satisfied, skipping upgrade: sdnotify>=0.3.2 in ./.local/lib/python3.9/site-packages (from maestral[gui]) (0.3.2)
Requirement already satisfied, skipping upgrade: sqlalchemy<1.4,>=1.3 in ./.local/lib/python3.9/site-packages (from maestral[gui]) (1.3.20)
Requirement already satisfied, skipping upgrade: keyring<22,>=19 in ./.local/lib/python3.9/site-packages (from maestral[gui]) (21.5.0)
Requirement already satisfied, skipping upgrade: watchdog<=0.10.3,>=0.10.0 in ./.local/lib/python3.9/site-packages (from maestral[gui]) (0.10.3)
Requirement already satisfied, skipping upgrade: dropbox<12.0,>=10.9.0 in ./.local/lib/python3.9/site-packages (from maestral[gui]) (11.0.0)
Requirement already satisfied, skipping upgrade: fasteners>=0.15 in ./.local/lib/python3.9/site-packages (from maestral[gui]) (0.15)
Requirement already satisfied, skipping upgrade: Pyro5>=5.10 in ./.local/lib/python3.9/site-packages (from maestral[gui]) (5.11)
Requirement already satisfied, skipping upgrade: survey<3.0,>=2.1.0 in ./.local/lib/python3.9/site-packages (from maestral[gui]) (2.1.6)
Requirement already satisfied, skipping upgrade: requests>=2.16.2 in /usr/lib/python3.9/site-packages (from maestral[gui]) (2.24.0)
Requirement already satisfied, skipping upgrade: dbus-next>=0.1.4; sys_platform == "linux" in ./.local/lib/python3.9/site-packages (from maestral[gui]) (0.2.1)
Requirement already satisfied, skipping upgrade: keyrings.alt<5.0,>=3.1.0 in ./.local/lib/python3.9/site-packages (from maestral[gui]) (4.0.1)
Requirement already satisfied, skipping upgrade: packaging in ./.local/lib/python3.9/site-packages (from maestral[gui]) (20.4)
Requirement already satisfied, skipping upgrade: click<8.0,>=7.1.1 in ./.local/lib/python3.9/site-packages (from maestral[gui]) (7.1.2)
Requirement already satisfied, skipping upgrade: pathspec>=0.5.8 in ./.local/lib/python3.9/site-packages (from maestral[gui]) (0.8.1)
Requirement already satisfied, skipping upgrade: maestral-qt>=1.3.0; sys_platform == "linux" and extra == "gui" in ./.local/lib/python3.9/site-packages (from maestral[gui]) (1.3.0)
Requirement already satisfied, skipping upgrade: python-dateutil in /usr/lib/python3.9/site-packages (from alembic<1.5,>=1.3->maestral[gui]) (2.8.1)
Requirement already satisfied, skipping upgrade: Mako in /usr/lib/python3.9/site-packages (from alembic<1.5,>=1.3->maestral[gui]) (1.1.3.dev0)
Requirement already satisfied, skipping upgrade: python-editor>=0.3 in ./.local/lib/python3.9/site-packages (from alembic<1.5,>=1.3->maestral[gui]) (1.0.4)
Requirement already satisfied, skipping upgrade: webob in ./.local/lib/python3.9/site-packages (from bugsnag<5.0,>=3.4->maestral[gui]) (1.8.6)
Requirement already satisfied, skipping upgrade: SecretStorage>=3.2; sys_platform == "linux" in ./.local/lib/python3.9/site-packages (from keyring<22,>=19->maestral[gui]) (3.2.0)
Requirement already satisfied, skipping upgrade: jeepney>=0.4.2; sys_platform == "linux" in ./.local/lib/python3.9/site-packages (from keyring<22,>=19->maestral[gui]) (0.5.0)
Requirement already satisfied, skipping upgrade: pathtools>=0.1.1 in ./.local/lib/python3.9/site-packages (from watchdog<=0.10.3,>=0.10.0->maestral[gui]) (0.1.2)
Requirement already satisfied, skipping upgrade: stone>=2.* in ./.local/lib/python3.9/site-packages (from dropbox<12.0,>=10.9.0->maestral[gui]) (3.2.1)
Requirement already satisfied, skipping upgrade: six>=1.12.0 in /usr/lib/python3.9/site-packages (from dropbox<12.0,>=10.9.0->maestral[gui]) (1.15.0)
Requirement already satisfied, skipping upgrade: monotonic>=0.1 in ./.local/lib/python3.9/site-packages (from fasteners>=0.15->maestral[gui]) (1.5)
Requirement already satisfied, skipping upgrade: serpent>=1.27 in ./.local/lib/python3.9/site-packages (from Pyro5>=5.10->maestral[gui]) (1.30.2)
Requirement already satisfied, skipping upgrade: wrapio>=0.3.5 in ./.local/lib/python3.9/site-packages (from survey<3.0,>=2.1.0->maestral[gui]) (0.3.8)
Requirement already satisfied, skipping upgrade: chardet<4,>=3.0.2 in /usr/lib/python3.9/site-packages (from requests>=2.16.2->maestral[gui]) (3.0.4)
Requirement already satisfied, skipping upgrade: idna<3,>=2.5 in /usr/lib/python3.9/site-packages (from requests>=2.16.2->maestral[gui]) (2.10)
Requirement already satisfied, skipping upgrade: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/lib/python3.9/site-packages (from requests>=2.16.2->maestral[gui]) (1.25.8)
Requirement already satisfied, skipping upgrade: pyparsing>=2.0.2 in /usr/lib/python3.9/site-packages (from packaging->maestral[gui]) (2.4.7)
Requirement already satisfied, skipping upgrade: markdown2 in ./.local/lib/python3.9/site-packages (from maestral-qt>=1.3.0; sys_platform == "linux" and extra == "gui"->maestral[gui]) (2.3.10)
Requirement already satisfied, skipping upgrade: PyQt5>=5.9 in /usr/lib64/python3.9/site-packages (from maestral-qt>=1.3.0; sys_platform == "linux" and extra == "gui"->maestral[gui]) (5.15.0)
Requirement already satisfied, skipping upgrade: MarkupSafe>=0.9.2 in /usr/lib64/python3.9/site-packages (from Mako->alembic<1.5,>=1.3->maestral[gui]) (1.1.1)
Requirement already satisfied, skipping upgrade: cryptography>=2.0 in /usr/lib64/python3.9/site-packages (from SecretStorage>=3.2; sys_platform == "linux"->keyring<22,>=19->maestral[gui]) (3.0)
Requirement already satisfied, skipping upgrade: ply>=3.4 in /usr/lib/python3.9/site-packages (from stone>=2.*->dropbox<12.0,>=10.9.0->maestral[gui]) (3.11)
Requirement already satisfied, skipping upgrade: cffi!=1.11.3,>=1.8 in /usr/lib64/python3.9/site-packages (from cryptography>=2.0->SecretStorage>=3.2; sys_platform == "linux"->keyring<22,>=19->maestral[gui]) (1.14.1)
Requirement already satisfied, skipping upgrade: pycparser in /usr/lib/python3.9/site-packages (from cffi!=1.11.3,>=1.8->cryptography>=2.0->SecretStorage>=3.2; sys_platform == "linux"->keyring<22,>=19->maestral[gui]) (2.20)

**Comment by SamSchott** [comment]
Wow, thanks for the quick report. Just when I thought I had tested everything...

Until this is fixed, you can start the GUI directly with the `maestral_qt` command.

**Comment by nalim** [comment]
Wow, thanks for the quick fix. Just when I thought I would have to wait for it long time... ;-)
