### ISSUE TITLE
Sync issues

### ISSUE THREAD

**Issue by pfascia** [SamSchott/maestral#259]
Hi, I am trying this software and I like it, just a question, why some files are not synced? Some .exe, some .zip. some.rar show "Could not download file: The file cannot be transferred because the content is restricted.." 
Restricted? By who? And for saying they are resctricted, how do You do it?

Regards
PF

**Comment by SamSchott** [comment]
This is a limitation of the public Dropbox API: unlike their own client, files with a DMCA takedown notice cannot be downloaded using the public endpoints. The error is generated by Dropbox and only passed on by Maestral.

**Comment by SamSchott** [comment]
Closing as there is nothing I can do about it.
