### ISSUE TITLE
[BUG]Sync crashes

### ISSUE THREAD

**Issue by ddesmond** [SamSchott/maestral#268]
**Describe the bug**

after some time maestral throws six error
**To Reproduce**

sync files with gui

**Expected behaviour**

Sync files without error

**System (please complete the following information):**
 - Maestral version: latest from pypi (15 dec 2020)
 -  - OS:  Centos 7.6
 - Desktop environment: Gnome
 - Qt version: installed with pip3 from manual 
[error.save.txt](https://github.com/SamSchott/maestral/files/5697686/error.save.txt)

**Additional context**

save log from error in attach

Thanks!

**Comment by SamSchott** [comment]
This looks like an old version of six. Which version do have installed? The Dropbox SDK requires `six >= 1.12.0`.

**Comment by ddesmond** [comment]
i did, thats why i wrote, installed it from scratch and checked it so its proper version. its 1.15.0 now.
Gui seems to have constantly X on it and throws that error anyways. 

Console seems to be syncing fine, except the DBUS errors i have which are for another issue. Will wait until it syncs and reboot the host to see if anything changes.
Thanks for fast reply! 
Awesome work man! Hats down.

**Comment by SamSchott** [comment]
Glad you like it! DBUS errors from the daemon should be "safe" to ignore, they just mean that desktop notifications are not working as intended. DBUS errors from the Qt Gui may be more complex...

I am fairly certain from your traceback is related to an incompatible version of six, though 1.15.0 is indeed the latest. Is it possible that the daemon is loading a different version of six at runtime from somewhere?

The traceback which you uploaded shows `AttributeError: module 'six' has no attribute 'ensure_str'` and `ensure_str` was added to six in v1.12.0.

**Comment by ddesmond** [comment]
yes indeed, ive checked that for six too, im gona spend more debugging to make it work for our use case.
One question though.
Would i be able to trigger sync without maestral deamon restart? Our use case is kinda specific and the folder is symlinked from network drive but it dosnt trigger sync when adding new files either way (local or from dbox cloud)

**Comment by SamSchott** [comment]
> yes indeed, ive checked that for six too

Worst case, you could manually add a breakpoint before the error is raised and run the daemon in the foreground with `maestral start -f`. It will then drop you into a debug console where you can check the version and import path of six, if it really has no `ensure_str` function, etc.

> Would i be able to trigger sync without maestral deamon restart? Our use case is kinda specific and the folder is symlinked from network drive but it dosnt trigger sync when adding new files either way (local or from dbox cloud)

Ah, symlinks and network drives are a really bad combination to get file system notifications. Your best option is to pause and resume syncing periodically, this triggers a full rescan of local folders but it's heavier on the memory usage. Sync conflicts will also become more likely if the interval between syncs increases.

**Comment by ddesmond** [comment]
ok, we can close this issue since im not gona use the gui much for now and cos work havent had time to debug further. ill update you on this once im back again to sync 👍 
thanks again for fast reponse and very nice app :)

superb! Epico!

**Comment by ddesmond** [comment]
after some work, seems some files are missing, and i can replicate the issue, mainly with the files not beeing updated. but you know that already. its a hardcore thing which, we noticed now, and we didint lost much work, im trying to mitigate it somehow.
Do you have any advice how to work around this issue?
one thing that bumps into my mind is to copy with rsync and make a clone folder localy on the machine.
if you have any ideas, im open and listening....

**Comment by SamSchott** [comment]
@ddesmond, this sounds concerning. Could you open a new issue and describe which steps exactly will reproduce the sync problems? I can then try to debug this locally.
