### ISSUE TITLE
Syncing a folder with both the official Dropbox client and Maestral at the same time.

### ISSUE THREAD

**Issue by rodrigoescandon** [SamSchott/maestral#278]
I have a potentially dumb question. The readme contains the following warning:

> Never sync a folder with both the official Dropbox client and Maestral at the same time.

This warning refers to installing the official Dropbox client and Maestral **on a single computer** and trying to sync the same folder **on said computer**, right? There should be no problem if I use sync a folder using (only) the official Dropbox client on one computer and (only) Maestral in another, correct?

**Comment by SamSchott** [comment]
Exactly! The wording is a bit ambiguous.

**Comment by rodrigoescandon** [comment]
Got it, thanks!
