### ISSUE TITLE
Cannot create temporary directory

### ISSUE THREAD

**Issue by theflysurfer** [SamSchott/maestral#287]
Hello

I tried to set up Maestral on Ubuntu server on a Raspberry Pi 4 platform.
I get this error
![2021-01-25_17-21-50 1](https://user-images.githubusercontent.com/9251759/105733518-ebdb8300-5f31-11eb-99b8-5da12926b122.png)

Even so it started created some subfolders, for which it looks like the write permission are correct

![2021-01-25_17-23-05 1](https://user-images.githubusercontent.com/9251759/105733655-13325000-5f32-11eb-9101-05d74da10329.png)

Even the hidden folder looks to have to appropriate rights

![2021-01-25_17-25-55 1](https://user-images.githubusercontent.com/9251759/105733973-686e6180-5f32-11eb-9c16-ce9f42a413a2.png)

What should I do ?

**Comment by SamSchott** [comment]
@theflysurfer, what file system are you using for `/media/3To`? This may be related to #272.

**Comment by theflysurfer** [comment]
This is ntfs mounted with ntfs-3g

I will look at the #272 post, it looks similar. 

Thanks

**Comment by SamSchott** [comment]
Closing since this is fixed in 1.4.0. Maestral ignores any errors when chmod fails.
