### ISSUE TITLE
Where is the daemon?

### ISSUE THREAD

**Issue by raffaem** [SamSchott/maestral#290]
I am on Ubuntu 20.10

`maestral` is telling me the daemon is running, but there is no such daemon find out by `service`

```
raffaele@mypc:~$ maestral start
Daemon is already running.
raffaele@mypc:~$ service --status-all | grep maestral
raffaele@mypc:~$ 
```

**Comment by raffaem** [comment]
The maestral daemon is not a service but a process. You need to find it with `ps`

**Comment by SamSchott** [comment]
Yes! Well, according to Wikipedia:

> a daemon is a computer program that runs as a background process, rather than being under the direct control of an interactive user

So it *is* a daemon, it's just not managaned as a service. Though maestral does offer systemd integration: `maestral autostart -Y` will install it as a systemd service to run on startup. Once installed, you can manage it with the regular systemctl commands:

`systemctl start|stop|restart maestral-daemon@maestral.service`.
