### ISSUE TITLE
[BUG] Maestra re-syncs after moving DropBox folder to a new partition

### ISSUE THREAD

**Issue by raffaem** [SamSchott/maestral#294]
**Describe the bug**
1. Move your Dropbox folder to somewhere else
2. After copying the files to the new place, updating internal index, Maestral starts to sync again with the server

**To Reproduce**
See above

**Expected behaviour**
Since I have just moved the folder to another place, there is no reason why we should expect that something on the server changed. Maestral should not sync.

**System (please complete the following information):**
 - Maestral version: GUI v. 1.3.1, daemon v. 1.3.1
 - OS: [e.g. Ubuntu] Ubuntu 20.10
 - Desktop environment: [e.g. Gnome 3.32] GNOME 3.38.1
 - Qt version: 5.14.2

**Additional context**

`maestral log show` displays on the last lines an inifinite series of:

```
2021-01-29 18:44:38 maestral.sync DEBUG: Modification of "<REDACTED>" detected but file content is the same as on Dropbox
```

Maestral should also sync whenever I buy a beer, get out with friends, run `gcc helloworld.c`.

**Comment by SamSchott** [comment]
For some reason it thinks that your files where not only moved but also all modified. But when comparing their content hashes to those on Dropbox servers, it notices that the content did not change and skips the upload. Still, the hashing will take a while and use CPU.

Did you do something like recursively change the permissions for the new folder after the sync was restarted?

**Comment by raffaem** [comment]
It is still syncing

`2021-01-29 23:49:00 maestral.sync DEBUG: Modification of "<REDACTED>" detected but file content is the same as on Dropbox
`

> For some reason it thinks that your files where not only moved but also all modified. But when comparing their content hashes to those on Dropbox servers, it notices that the content did not change and skips the upload. Still, the hashing will take a while and use CPU.
> 
> Did you do something like recursively change the permissions for the new folder after the sync was restarted?

No I did not change permission.

But the source folder before the move was on a ext4 parition with LUKS 2 encryption. The destination folder after the move is on a NTFS partition. Has this something to do with the new sync?

**Comment by SamSchott** [comment]
> But the source folder before the move was on a parition with file system ext4 and LUKS 2 encryption. The destination folder after the move is on a partition with file system NTFS.

I think this explains it. Moving the folder across partitions will change the ctimes of all items and therefore trigger a resync. Moving within the same partition uses fast-copy syscalls which leave the ctime unchanged. This also explains why the actual move was slow. Now that I'm aware of the issue, I can work around that.

Also note issue #272 for NTFS partitions: you'll need to make sure that the partition is mounted in a way that `chmod` calls succeed. This requirement will be relaxed in the next release but will still raise errors for now.
