### ISSUE TITLE
WebDAV client

### ISSUE THREAD

**Issue by raffaem** [SamSchott/maestral#297]
**Is your feature request related to a problem? Please describe.**

Zotero can sync using WebDAV instead of its own storage

**Describe the solution you'd like**

DropBox provides no WebDAV interface. I would have Maestral provide a WebDAV interface and translate WebDAV calls into DropBox API calls

**Describe alternatives you've considered**
I have considered [DropDAV](https://dropdav.com/) but it is not working

**Additional context**
See [Zotero with WebDAV](https://www.zotero.org/support/sync#webdav)

**Comment by SamSchott** [comment]
Thanks for the suggestion. I am not really familiar with WebDav and what supporting it would require. From Wikipedia, it's a HTTP protocol for file operations, so would either entail running a local webserver on the client PC or providing a remote webserver to process WebDav requests. And there may be quirks such as per-client file locking (not supported by Dropbox) to work around.

For now, it looks like WebDAV support would be too much work to implement -- there is a reason why DropDav charges $5 per month per user. This might of course change in the future, if the project gets significant funding or if an enthusiastic developer is happy to take on the work.
