### ISSUE TITLE
[BUG] Stuck on fetching remote changes

### ISSUE THREAD

**Issue by raffaem** [SamSchott/maestral#300]
**Describe the bug**
My Maestral is stuck on "Fetching remote changes"

**To Reproduce**
I don't know. I just started it yesterday and today and it was stuck there.

**Expected behaviour**
Should sync

**System (please complete the following information):**
 - Maestral version: GUI v. 1.3.1, daemon v. 1.3.1
 - OS: [e.g. Ubuntu] Ubuntu 20.10
 - Desktop environment: [e.g. Gnome 3.32] GNOME 3.38.1
 - Qt version: 5.14.2
 
**Additional context**

`maestral log show`

```
 <FileMetadata(path_display=<FILE ON REMOTE SERVER NOT ON LOCAL FOLDER>)>
```

```
$ maestral status

Account:      <REDACTED>
Usage:        4.7% of 437.6 TB used
Status:       Fetching remote changes...
Sync threads: Running
Sync errors:  0
```

`maestral activity`

This output cannot be copied. When I select it, it is automatically unselected

**Comment by SamSchott** [comment]
Hm, this may be a similar issue to #289. At least this time the entire process doesn't seem to be blocked. The log output which you show appears to be from the debug output. Could you provide the preceding log message? It should either be "Listed remote changes" or "Cleaned remote changes".

Also, is it stuck indefinitely or does it *eventually* resume, just much later than expected? The requests to Dropbox servers have a very long timeout so a flaky internet connection may result in long pauses before it gives up.

`maestral activity` is an interactive display which is updated every 1 sec. Depending on your shell, selections might not be preserved during refresh.

**Comment by SamSchott** [comment]
This may be a long shot but is there any way to reproduce the suck behaviour reliably?

Maestral uses quite a bit of shared state, mostly for database access, which is currently synchronised by locks. Even though I haven't encountered this myself, I wouldn't rule out a deadlock in one of the sync threads.

**Comment by raffaem** [comment]
Now it is stuck in Connecting...

`2021-02-02 21:57:36 maestral.sync INFO: Connecting...`

I don't know how to reproduce. Is there a way to find out if a thread is deadlocked?

**Comment by SamSchott** [comment]
> I don't know how to reproduce. Is there a way to find out if a thread is deadlocked?

A deadlock would be blocking without ever progressing. In your case, it seems to be progressing but very slowly and possibly in circles.

I have a suspicion about what might be happing and think I can reproduce it on my end. Is it possible that the internet connection was intermittently lost during the "Fetching remote changes..." stage? I think there may be a bug that could result in multiple threads trying to list those changes when the connection is reestablished. They would get into each others hairs and result in backoff requests from Dropbox servers. This could explain the behaviour which you are seeing.

I'll investigate and come back to you...

**Comment by raffaem** [comment]
> > I don't know how to reproduce. Is there a way to find out if a thread is deadlocked?
> 
> A deadlock would be blocking without ever progressing. In your case, it seems to be progressing but very slowly and possibly in circles.
> 
> I have a suspicion about what might be happing and think I can reproduce it on my end. Is it possible that the internet connection was intermittently lost during the "Fetching remote changes..." stage? I think there may be a bug that could result in multiple threads trying to list those changes when the connection is reestablished. They would get into each others hairs and result in backoff requests from Dropbox servers. This could explain the behaviour which you are seeing.
> 
> I'll investigate and come back to you...

Yeah. my internet connection is not reliable at all

**Comment by SamSchott** [comment]
I can see why having resumable indexing would be useful then, especially with so many files to sync :)

Ok, I think I know what is going on now and the problem definitely still exists in the dev branch. I'll hopefully have a fix soon but in the meantime, my best recommendation is to quit and restart Maestral when it appears to be stuck in a never-ending sync cycle. Apologies for this!

**Comment by SamSchott** [comment]
This *should* be fixed now. I have pushed a pre-release of version 1.3.2.dev0 to PyPI which you can install with:

```
pip3 install -U --pre maestral[gui]
```

This also includes the patches from #296.

Could you try this out and see if it fixes the issues for you? This update will be stable and reversible, the only migration in the release concerns the keyring backend in macOS and therefore doesn't affect Linux.

**Comment by raffaem** [comment]
Hurray! Thank you so much!

It is giving me the following errors upon install:

```
ERROR: launchpadlib 1.10.13 requires testresources, which is not installed.
ERROR: secretstorage 3.3.0 has requirement jeepney>=0.6, but you'll have jeepney 0.4.3 which is incompatible.
```

However, after uninstalling the previous version and reinstalling the pre one, no such error was showed.

Maestral preferences now show version 1.3.2.dev0 for both daemon and GUI.

Although the log shows a lost connection:

```
2021-02-03 18:45:07 maestral.sync DEBUG: Lost connection
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out
```

This probably refers before I activated the VPN.

Maestral is now syncing.

Are the logs cleared when Maestral quits? Otherwise that log above may refer to a previous instance.

Maestral is now syncing and showing this as last line in logs:

`DeletedMetadata(path_display=<ABRIDGED>)>`

I will tell you tomorrow whether it suceeds ^.^

I would propose an option to save logs into a file with abridged filenames.

**Comment by SamSchott** [comment]
> Are the logs cleared when Maestral quits? Otherwise that log above may refer to a previous instance.

The logs are preserved and only cleared when they grow above a few MB, you'll need to clear them manually with `maestral log clear` otherwise.

> `2021-02-03 18:45:07 maestral.sync DEBUG: Lost connection`

That's message is absolutely fine. It just means that a connection timed out. You'll see lots of those with a bad internet connection.

> I would propose an option to save logs into a file with abridged filenames.

Not sure if there is any benefit from that. File names are only recorded in the logs if the level is set to DEBUG, to be able to follow specific issues with particular files and see how particular sync events are handled. Not having file names will defeat that purpose. If you set the log level back to INFO with `maestral log level INFO`, which is the default, no file names will be recorded.

> Maestral is now syncing.

Fingers crossed, let me know how it goes!

**Comment by raffaem** [comment]
> Not sure if there is any benefit from that. File names are only recorded in the logs if the level is set to DEBUG, to be able to follow specific issues with particular files and see how particular sync events are handled. Not having file names will defeat that purpose. If you set the log level back to INFO with maestral log level INFO, which is the default, no file names will be recorded.

Ah ok, sorry for my misunderstanding :) It was only to upload the logs here without everybody in the world being able to see my filenames :)

Are the logs automatically saved in a file?

> Fingers crossed, let me know how it goes!

I will put "Maestral beta tester" on my resumé :)

**Comment by SamSchott** [comment]
> Are the logs automatically saved in a file?

Yes, they are. On Linux, they are saved to `~/.cache/maestral`, on macOS to `~/Library/Logs/maestral`. You can also directly open the most recent log file in an external editor with `maestral log show -e`. The logs will grow up to 10 MB before being overwritten.

> I will put "Maestral beta tester" on my resumé :)

For what it's worth :) Also thank you for reporting those issues and following up! Especially problems that only show up under particular circumstances, such as a bad internet connection, are otherwise very hard to find for me.
