### ISSUE TITLE
[PROPOSAL] Manage inotify limit better

### ISSUE THREAD

**Issue by raffaem** [SamSchott/maestral#305]
Suddenly the following appeared, without me doing anything strange:

![image](https://user-images.githubusercontent.com/54762742/107162479-b8720d00-69a3-11eb-8098-7e5cd810b49e.png)

1. Why this windows appeared out of the blue?
2. Where does "524XXX" comes from? That variable was set to 100000 previously
3. Can we change that variable when we install Maestral?

**Comment by raffaem** [comment]
It appeared again .. to I have to restart my PC after the change?

**Comment by SamSchott** [comment]
> Why this windows appeared out of the blue?

Because now that you have everything synced, you have *a lot* of items that need to be watched.

> Where does "524XXX" comes from? That variable was set to 100000 previously

To be fair, this error message should be improved. 524288 is a decent number because it is larger than most Dropbox folder sizes. But really the message should say: set `fs.inotify.max_user_watches` to a value exceeding the number of items in your Dropbox folder...

> Can we change that variable when we install Maestral?

No. Changing it will fiddle with the system settings and requires elevated privileges. Neither should be done automatically at install time but deliberately by the user or admin. Some people will want to reduce the number of allowed inotify watches, for instance on embedded systems with very little memory.

**Comment by SamSchott** [comment]
> It appeared again .. do I have to restart my PC after the change?

Yes! Another info missing from the message...

**Comment by raffaem** [comment]
> But really the message should say: set `fs.inotify.max_user_watches` to a value exceeding the number of items in your Dropbox folder...

Honestly it wouldn't be so straightforward for my use case. 

I would have 10k files, set that setting to 10001, then it is sufficient for me to include another folder, or for a college to add a file to exceed the limit again.

And then when I include another folder to download in local, I would need to remember to update that system setting again.

> > Can we change that variable when we install Maestral?
> 
> No. Changing it will fiddle with the system settings and requires elevated privileges. Neither should be done automatically at install time but deliberately by the user or admin. Some people will want to reduce the number of allowed inotify watches, for instance on embedded systems with very little memory.

Can we change it at runtime? For instance, can that message box change it for me?

The message could end with something like: "Do you want Maestral to update this setting for you?". And if I click yes it would run "sudo sed ...." or something like that (asking for my password)

**Comment by raffaem** [comment]
I am still getting this message even if I did what Maestral asked me to do

```
2021-02-08 12:46:34 maestral.sync ERROR: Unexpected error: Please restart to continue syncing
Traceback (most recent call last):
  File "/home/raffaele/.local/lib/python3.8/site-packages/maestral/sync.py", line 3776, in start
    self.local_observer_thread.start()
  File "/home/raffaele/.local/lib/python3.8/site-packages/watchdog/observers/api.py", line 256, in start
    emitter.start()
  File "/home/raffaele/.local/lib/python3.8/site-packages/watchdog/utils/__init__.py", line 93, in start
    self.on_thread_start()
  File "/home/raffaele/.local/lib/python3.8/site-packages/watchdog/observers/inotify.py", line 117, in on_thread_start
    self._inotify = InotifyBuffer(path, self.watch.is_recursive)
  File "/home/raffaele/.local/lib/python3.8/site-packages/watchdog/observers/inotify_buffer.py", line 35, in __init__
    self._inotify = Inotify(path, recursive)
  File "/home/raffaele/.local/lib/python3.8/site-packages/watchdog/observers/inotify_c.py", line 198, in __init__
    self._add_dir_watch(path, recursive, event_mask)
  File "/home/raffaele/.local/lib/python3.8/site-packages/watchdog/observers/inotify_c.py", line 395, in _add_dir_watch
    self._add_watch(full_path, mask)
  File "/home/raffaele/.local/lib/python3.8/site-packages/watchdog/observers/inotify_c.py", line 409, in _add_watch
    Inotify._raise_error()
  File "/home/raffaele/.local/lib/python3.8/site-packages/watchdog/observers/inotify_c.py", line 421, in _raise_error
    raise OSError(errno.ENOSPC, "inotify watch limit reached")
OSError: [Errno 28] inotify watch limit reached
```

My folder is ~190k files and I have set that variable to the suggested ~500k

**Comment by SamSchott** [comment]
Hm, that is strange.  Can you verify that the `max_user_watches` really has been increased? The following terminal command will give you the current value:
```
sysctl fs.inotify.max_user_watches
```
You can also increase the number of watches directly with:
```
sudo sysctl fs.inotify.max_user_watches=524288
```
This will increase the max number of watches immediately but will be reset after a reboot.

**Comment by SamSchott** [comment]
> The message could end with something like: "Do you want Maestral to update this setting for you?". And if I click yes it would run "sudo sed ...." or something like that (asking for my password)

That's a good suggestion. There probably is a platform API for starting a subprocess with elevated privileges which handles the password prompt. I'll look into it.

**Comment by raffaem** [comment]
Now it is asking me to set that variable to 512, which is lower than before and lower than the current number:

![image](https://user-images.githubusercontent.com/54762742/107326490-c90daa80-6aab-11eb-9f61-43dbf05daede.png)

```
$ sysctl fs.inotify.max_user_watches
fs.inotify.max_user_watches = 524288
```
Where does all these numbers come from?

**Comment by SamSchott** [comment]
Ok, increasing `max_user_watches` worked! But it appears that you are also running our of inotify instances, which is surprising. Again, 512 just is a best guess of what should be sufficient and not really based on data. The number are all powers of two. Does increasing `max_user_instances` solve the issues?

Also, do you have any other programs running which are monitoring the file system vs inotify? In this case, the new limits might not be high enough.

You can get the number of files being watched by all processes, you can use:

```
lsof | grep inotify | wc -l
```

`max_user_watches` should be set to something quite a bit higher, to give a bit of flexibility.

To see all processes using inotify, order by their number of instances:

```
for foo in /proc/*/fd/*; do readlink -f $foo; done | grep inotify | sort | uniq -c | sort -nr
```

This will give output looking like:

```
      4 /proc/9370/fd/anon_inode:inotify
      2 /proc/2942/fd/anon_inode:inotify
      1 /proc/2570/fd/anon_inode:inotify
      1 /proc/2524/fd/anon_inode:inotify
```

where the number is the PID.

You can find a good writeup about this at https://transang.me/enospc-inotify-in-ubuntu/.

**Comment by SamSchott** [comment]
A Wiki page about this is probably a good idea.

**Comment by SamSchott** [comment]
I've added a section in the docs about adjusted inotify limits: https://www.maestral.app/docs/inotify-limits.

I might also add a link to this help page in the error message. This should hopefully be enough documentation to help users out.

**Comment by SamSchott** [comment]
Most if this has been done in v1.4.4. I have not included any automatic adjustments to inotify limits, just because the potential of things going wrong and the number of corner cases with Linux is too large.
