### ISSUE TITLE
[BUG] Update requirements to include Qt

### ISSUE THREAD

**Issue by kTag** [SamSchott/maestral#306]
**Describe the bug**

It's not mentioned clearly anywhere that Qt is a requirement and it seems the current Ubuntu distro doesn't include Qt

**To Reproduce**

Follow requirement instruction and Maestral doesn't start because it's missing all the Qt libraries

**Expected behaviour**

Qt requirement should be mentioned in the main index page and installation page

**System (please complete the following information):**
 - Maestral version: 1.3.1
 - OS: Ubuntu 20.10
 - Desktop environment: Gnome 3.38.3
 - Qt version: N/A

**Additional context**

**Comment by SamSchott** [comment]
PyQt5 is specified as a requirement for the GUI in the installation instructions at https://github.com/SamSchott/maestral#installation.

Running `pip3 install -U maestral[gui]` however should install install everything for you through pip. If this fails, you can try to install PyQt5 through your package manager. On Ubuntu, this would be: `sudo apt install python3-pyqt5`.

Let me know if there are any issues with this.

**Comment by kTag** [comment]
I mean the native Qt Ubuntu package is not installed by default in Ubuntu. I had to install it manually. Not PyQt. 



—
Pierre N

**Comment by SamSchott** [comment]
Hm, the PyQt5 wheels should include copies of the corresponding Qt libraries. There is no need for a separate installation. It's a different situation when you are building PyQt5 from source.

**Comment by SamSchott** [comment]
Closing this since it isn't an issue with Maestral but rather with installing PyQt5.
