### ISSUE TITLE
Segfault on macOS when creating file names with some unicode characters

### ISSUE THREAD

**Issue by SamSchott** [SamSchott/maestral#322]
**Describe the bug**
When creating a local file with unicode characters in the name that are 'exotic' such as é or ä or emojis, Maestral will crash with a segfault on macOS. Linux is not affected.

**To Reproduce**
See above.

**System:**
 - Maestral version: 1.4.0 and higher
 - OS: macOS

**Additional context**
The underlying issue lies with the path handling in the watchdog dependency, as described in https://github.com/gorakhargosh/watchdog/pull/763. Until an update with a fix is released, the only work around is to use the app bundle on macOS which has been updated to contain a patched version of watchdog.

Once a fix has been released, please update watchdog with `pip3 install -U watchdog.`

**Comment by BoboTiG** [comment]
Release v2.0.1 online ;)
