### ISSUE TITLE
Reduce size of Docker image

### ISSUE THREAD

**Issue by SamSchott** [SamSchott/maestral#324]
Following recent changes to `cryptocurrency`, Rust is now required to build wheels for cryptocurrency (which is an indirect dependency of maestral through keyring). This is codumented at https://cryptography.io/en/latest/installation.html#alpine. Since no wheels are available for Alpine Linux, as used in the Docker image, this has required some changes to the docker file:

1. Use Alpine 3.13 which comes with Rust >= 1.41.0.
2. Install cargo as a build dependency.

Despite removing build dependencies afterwards, the resulting docker image has ballooned in size from ~25 MB to ~125 MB.

@aries1980, any idea how this might be improved? I assume there are some build caches which are not cleared but don't really have experience with Alpine Linux or Rust to figure out what can be stripped from the Docker image.

**Comment by SamSchott** [comment]
A side-effect is also that the build time has increased to about 25 min on GH actions. It would be nice if this can improved by caching wheels between builds. But this is by no means essential.

**Comment by aries1980** [comment]
> Rust is only required when building cryptography, meaning that you may install it for the duration of your pip install command and then remove it from a system.

Do we need to build `cryptography` from scratch? `pip install` does not install an already compiled version?

**Comment by SamSchott** [comment]
Yes, we need to build from scratch. They do not publish wheels for Alpine / musl libc.

**Comment by aries1980** [comment]
Well, then I am not sure if we can circumvent the build, but at the end, we can remove Rust for sure. I can try to have a look at and create a PR.

**Comment by SamSchott** [comment]
> but at the end, we can remove Rust for sure

Well, Rust comes with Alpine Linux, so it should have been part of the image previously as well. And the current docker file does remove build dependencies. But I suspect there may be libs downloaded for the build and other generated files that blow up the image size.

> I can try to have a look at and create a PR.

That would be great!

> Any idea what could be a "cache key"?

No idea, sorry. I know that there is a GH action to cache dependencies between runs (https://github.com/actions/cache) but have never used it before. I could image for instance a two stage docker build where the first stage is cached. But this really is more of a nice to have.

**Comment by SamSchott** [comment]
Oh, right, I understand your question now. And it's a good question. One could maybe use the latest versions of the Python dependencies (including transitive dependencies) as a cache key, i.e., rebuild the cache if there is a new version of one of them available. Getting such a dependency tree from pip seems difficult at the moment. There is discussion about a `pip resolve` command but it's not more than a feature request at the moment.

**Comment by SamSchott** [comment]
Turns out reducing the image size really is as simple as deleting the cargo caches at `/root/.cargo`. I've just submitted a PR.

If you have some spare time, feel free to work on caching part of the builds. But it's by no means a priority, GitHub Actions are free for open source projects :)

**Comment by aries1980** [comment]
Good job! :)
