### ISSUE TITLE
If you move the folder and let Maestral know the new folder path, Maestral downloads them all again

### ISSUE THREAD

**Issue by raffaem** [SamSchott/maestral#346]
**Describe the bug**

Quit Maestral.

Moved the Dropbox folder out in new partition.

Formatted the old partition.

Moved Dropbox folder back in.

The old partition is mounted at a different mountpoint (e.g. /media/user/intdata instead of /media/user/data).

Opening Maestral, it complains that the folder cannot be found anymore (of course it keeps looking for /media/user/data). 

It asks to "unlink" the account or insert a location to (re-download?) the folder.

I put in the new location of the Dropbox folder (in /media/user/intdata).

Click Ok.

Maestral shows that the folder is not empty (I don't remember the exact dialogs now....), and asks what you want to do with it. I pressed "Merge". Then Maestral asks which remote folders you want to sync, and all remote folders are selected, even though only a few of the remote folders are in the local folder. I manually unselected the remote folders that are not in local. 

But Maestral nevertheless created all the remote folders in local and is now syncing.

I suppose that when the sync finished only the effectively selected remote folders will be in local?

**To Reproduce**
See above

**Expected behaviour**
Maestral should recognize that the new local folder is an "old" (?) sync, and only selects those remote folders that were syncing before. Maybe track which folders are being synced in a .maestral/synced file inside the Dropbox folder?

Or chage the "Merge" into "This folder is a previous sync".

Of course it is perfectly possible that in the meantime remote contents have changed, so Maestral should sync again and is expected to do so, but only for the folders that were previously syncing.

At the very least, manually unselecting not synced folders should prevent Maestral to download them all.

**System:**

 - Maestral version: 1.4.2
 - OS: [e.g. Ubuntu] Ubuntu 20.10
 - Desktop environment: [e.g. Gnome 3.32] GNOME 3.38
 - PyQt version (for Linux GUI): 
PyQt5==5.15.0
PyQt5-Qt==5.15.2
PyQt5-sip==12.8.1

**Comment by SamSchott** [comment]
> Then Maestral asks which remote folders you want to sync, and all remote folders are selected, even though only a few of the remote folders are in the local folder. I manually unselected the remote folders that are not in local.

It should remember which folder where selected, though I'll have to double check what the Linux GUI does when it cannot find the local Dropbox folder. It might just be that it resets some of the sync settings.

> At the very least, manually unselecting not synced folders should prevent Maestral to download them all.

Again, it *should* and it typically does. Could you post / upload the log file?

**Comment by SamSchott** [comment]
This should be fixed in v1.4.4.
