### ISSUE TITLE
Stop the daemon from the GUI

### ISSUE THREAD

**Issue by raffaem** [SamSchott/maestral#351]
The GUI has an option "Quit Maestral __GUI__".

This may also be a bit misleading as, of course, the daemon keeps running.

You also need to remember to manually stop the daemon for certain debug purposes.

Can we have an option "Stop Maestral GUI & Daemon"?

**Comment by SamSchott** [comment]
Hm, maybe. If the daemon is already running when the GUI is launched, closing the GUI will not stop the daemon. It is only for this case that the option is "Quit Maestral GUI". The assumption here is that if the daemon was started from the command line or systemd, the used will want to stop it in the same way.

If on the other hand no daemon was running and GUI started it itself, the menu entry will simply read "Quit Maestral" and will quit both the GUI and daemon. The underlying logic: always use the same interface to stop things as was used to start them.

I can see how this is could be confusing. But I am a bit reluctant to add another entry to an already long menu...

**Comment by raffaem** [comment]
Ah I understand now how it works. Sorry for the confusion :)

So when I saw that "Quit Maestral GUI" I must have started the daemon some other way :)
