### ISSUE TITLE
Don't try to guess the Secret Service provider :)

### ISSUE THREAD

**Issue by raffaem** [SamSchott/maestral#352]
**Describe the bug**

In the past I used gnome-keyring as my freedesktop.org Secret Service provider.
Now I have switched to KeePassXC.

I opened Maestral with KeePassXC registered as the Secret Service provider, Maestral asked a new Dropbox authorization and is now resyncing.

Problem: if, when I open Maestral, KeePassXC is closed, Maestral will start gnome-keyring-daemon, which will try to create a new keyring (I removed the old ones when I switched to KeePassXC).

This _prevents_ KeePassXC to register as freedesktop.org Secret Service provider. Only one provider can be and gnome-keyring is already there.

If you get into this situation, the passages are:
1. Close Maestral
2. Issue `sudo killall gnome-keyring-daemon`
3. Open KeePassXC
4. KeePassXC remembers from last time that it was not able to register as Secret Service provider. So you need to re-register from the settings
5. Open Maestral

In `.config/maestral/maestral.ini` I have:

```
[app]
notification_level = 15
log_level = 10
update_notification_interval = 604800
keyring = keyring.backends.SecretService.Keyring
```

So Maestral knows that its secrets are kept by the Secret Service Provider

**To Reproduce**
See above

**Expected behaviour**
I think Maestral should:

1. Remember the exact Secret Service Provider that is keeping its keyring? That is, remember if it is GNOME keyring or KeePassXC?
I don't know whether that would be congruent with the standard.
Moreover, I think it would be theoretically possible in my situation to copy the secrets from GNOME keyring to KeePassXC when switching over (instead of basically resetting them like I did)?
What in this situation? Well, one would have to manually modify Maestral's config file to specify the new Secret Service provider

2. Don't try to guess the Secret Service provider.
If there is no Secret Service provider registered, just display a message "In the config file I see that my secrets are kept by a Secret Service provider. But there is no Secret Service provider currently registered". 

**System:**

 - Maestral version: 1.4.2
 - OS: [e.g. Ubuntu] Ubuntu 20.10
 - Desktop environment: [e.g. Gnome 3.32] GNOME 3.38
 - PyQt version (for Linux GUI): 5.15.0

**Comment by raffaem** [comment]
I think the "culprit" are those lines of `src/maestral/oauth.py`:

```
                # get preferred keyring backends for platform
                available_rings = keyring.backend.get_all_keyring()
                supported_rings = [
                    k
                    for k in available_rings
                    if isinstance(k, supported_keyring_backends)
                ]

                ring = max(supported_rings, key=lambda x: x.priority)
```

**Comment by raffaem** [comment]
Temporary workaround:
`sudo chmod -x /usr/bin/gnome-keyring-daemon`

Maestral will throw exception
`maestral.errors.KeyringAccessError: Could not load auth token, SecretService Keyring is locked. Please unlock the keyring and try again.`

but at least `gnome-keyring-daemon` is not started

**Comment by SamSchott** [comment]
I'm not sure if there is anything that Maestral can do here but I'm also not particularly familiar with the Secret Service API.

AFAIK, the there is no way to either query or set the Secret Service provider from the D-Bus interface. The code which you quote tries to prioritise between higher level backends (macOS Keychain, Secret Service, text file, etc). I think it is the job of the desktop environment to launch and unlock the configured Secret Service provider on login or on-demand when a D-Bus connection is made.

The systemd service file for Secret Service *should* specify which provider will be started on-demand and I suspect that this still is the gnome-keyring-daemon in your case.

**Comment by raffaem** [comment]
Can you provide me the code run by Maestral that actually causes `gnome-keyring` (directly or indirectly) to be called, so I an better debug this?

The source says:
```
Supported keyring backends
    are, in order of preference:

        * MacOS Keychain
        * Any keyring implementing the SecretService Dbus specification
        * KWallet
        * Gnome Keyring
        * Plain text storage
```

So I thought that if it doesn't find the Secret Service, if calls GNOME keyring (and so I thought the GNOME keyring was opened by Maetral directly, and not by the OS as in "something is calling the Secret Service. Let's open GNOME keyring")

**Comment by SamSchott** [comment]
> So I thought that if it doesn't find the Secret Service, it calls GNOME keyring

It doesn't, it will insist on sticking with the backend where it originally stored the auth token (the backend which is saved in the config file after linking). The auth module only looks for auth tokens where it originally stored them. If you manually migrate the token, as you have noted, you'll need to edit the config file to set another backend.

The relevant lines in the code are, when we are already linked:

https://github.com/SamSchott/maestral/blob/56b04ebc8cfe0f00b454e61348a1f0da8f36c03c/src/maestral/oauth.py#L150-L166

When we are not yet liked:

https://github.com/SamSchott/maestral/blob/56b04ebc8cfe0f00b454e61348a1f0da8f36c03c/src/maestral/oauth.py#L171-L193

Note that the module only checks for all available backends in the second case. Once it has determined the best candidate, it stores the result in the config file.

I've updated the doc strings to clarify this.

**Comment by SamSchott** [comment]
> something is calling the Secret Service. Let's open GNOME keyring

That's exactly what is happening. For instance on my ubuntu virtual machine, I have a systemd unit file `/usr/share/dbus-1/services/org.freedesktop.secrets.service` with the following content:

```ini
[D-BUS Service]
Name=org.freedesktop.secrets
Exec=/usr/bin/gnome-keyring-daemon --start --foreground --components=secrets
```

This ensures that the gnome-keyring-daemon is started on a D-Bus request to the Secrets Service API, because Gnome Keyring is the default provider on Ubuntu.

**Comment by raffaem** [comment]
You are right!

I have substituted that line with `/usr/bin/keepassxc` and now starting Maestral starts KeePassXC!

I will submit a request to KeePassXC to offer the option to register as default systemd Secret Service provider by changing that file.

Thank you so much!
