### ISSUE TITLE
Cannot launch version 1.4.3 on Apple Silicon

### ISSUE THREAD

**Issue by jcjee** [SamSchott/maestral#353]
**Describe the bug**
Cannot launch version 1.4.3 on Apple Silicon MacBook Air

**To Reproduce**
Install 1.4.3 version on a M1 MacBook

**Expected behaviour**
Error message "Could not start Maestral" is displayed. System log contains the following error:

com.apple.xpc.launchd[1] (application.com.samschott.maestral.16779534.16779540[790]): Service exited with abnormal code: 251

**System:**
 - Maestral version: 1.4.3
 - OS: MacOS Big Sur 11.3 Beta (20E5196f)

**Comment by SamSchott** [comment]
Ouch, I was hoping this wouldn't happen. The new build is a universal binary but at least one bundled library may not be. I was expected the system to then just start it under Rosetta translation. Unfortunately I personally don't have access to an M1 mac to test this.

Can you choose to run the app under Rosetta in the Finder's "Get Info" panel? Does that help? If not, I'll upload a good old fashioned x86_64 app bundle again...

**Comment by jcjee** [comment]
Yes, running 1.4.3 under Rosette works, thanks so much!

**Comment by SamSchott** [comment]
@jcjee, could I use you as a guinea pig? Could you try the attached app bundle and see if it runs without Rosetta? It should have all remaining libraries updated to universal binaries.

[Maestral.app.zip](https://github.com/SamSchott/maestral/files/6136748/Maestral.app.zip)

**Comment by jcjee** [comment]
@SamSchott just tried this universal build it seems to work fine 👍

**Comment by SamSchott** [comment]
Excellent :) I've updated the dmg on the Releases page accordingly.
