### ISSUE TITLE
Selective sync dialog is slow to respond for several seconds when first opened

### ISSUE THREAD

**Issue by 9a3eedi** [SamSchott/maestral#365]
**Describe the bug**
When opening the selective sync dialog, the dialog is somewhat unresponsive for several seconds. It's difficult to scroll and select check boxes when it's not responsive. 

My guess is that it's still not done populating the entire list and so it's constantly updating the UI widget, which is causing it to constantly try to redrew and causes it to be unresponsive

**To Reproduce**
1. Have a well populated Dropbox 
2. Open the selective sync dialog
3. Notice how it's difficult to scroll or do anything, until after 10-20+ seconds.

**Expected behaviour**
A responsive UI when the dialog appears.

**System:**
Majaro ARM Linux with KDE on a Pinebook Pro with a Rockchip RK3399 SOC with Mali T860 MP4 GPU and 4GB of RAM.

(very exotic, I know! Isn't open-source beautiful?)

**Additional context**
The computer isn't exactly a powerhouse, so this may be something that's only noticeable on weaker CPUs. However, I still consider it an issue. It does take several seconds (10-20) and it doesn't feel right.
My Dropbox has quite a lot of files. This might be another cause to the issue

**Comment by SamSchott** [comment]
> My guess is that it's still not done populating the entire list and so it's constantly updating the UI widget, which is causing it to constantly try to redrew and causes it to be unresponsive

Yes, I expect this is the issue. The actual listing is performed by the daemon process. Though I am a bit the surprised at the UI becoming unresponsive. Actually fetching the folders from Dropbox servers should be sufficiently slow to the the UI ample time to update in between.

> My Dropbox has quite a lot of files. This might be another cause to the issue

The dialog will initially load the top level and the second level of files and folders. It can therefore display all top-level files and folders as well as the second level immediately when expanded. Any further folder content is fetched only as necessary. How many files and folders do you have at the top-level and the first level?

**Comment by 9a3eedi** [comment]
I have around 83 files in the top level, 36 of which are folders. In the second level unfortunately it's a bit tedious for me to count manually. I was attempting to mount my Dropbox with rclone but it just didn't work for me, otherwise I could use some tools.

**Comment by SamSchott** [comment]
Oh, that is really not much at all. I was expecting something around 10,000. I have had no issues with around 2,000 folders at the top level and hundreds of folder at the second level.

Is it possible that a particular folder contains a particularly large number items (anything > 1,000)? Other than that, I am not sure why there would be any slowdowns.

I can certainly remove the pre-loading of children, which will speed up the initial population of the list without a significant reduction in convenience.

**Comment by 9a3eedi** [comment]
Going through my folders there is one particular folder that possibly has more than a thousand files in the second level. Maybe that's the culprit. Also keep in mind that my machine is very weak, consider it the same performance as a low end Intel Atom

Man I need to clean up my Dropbox :)

**Comment by SamSchott** [comment]
> there is one particular folder that possibly has more than a thousand files in the second level

Ok, in this case I hope that the performance issues will be resolved by the latest changes. If graphics performance remains an issue, I can recommend the CLI. Excluding files or folders is less convenient - you'll need to directly give the path relative to Dropbox - but is only limited by the performance of the daemon.
