### ISSUE TITLE
Selective sync dialog usability improvements

### ISSUE THREAD

**Issue by 9a3eedi** [SamSchott/maestral#366]
**Is your feature request related to a problem? Please describe.**
When using selective sync, it is somewhat messy and hard to find the folders you want.

**Describe the solution you'd like**
When opening the selective sync dialog, there are a few improvements I would like to see as a user:

- The files should be sorted folders first. Currently there are files dispersed between folders and it's a bit of a mess.
- I'm not sure if it's intended, but files should not appear, only folders. However, this might be a feature, I can't really say. I do know that the regular Dropbox app does not show files.
- Another idea is to allow the user to sort in different ways (e.g. ascending/descending, type, etc.)

**Comment by SamSchott** [comment]
Sorting is certainly a good suggestion. Files are intentionally listed, you can exclude both files and folders from syncing with Maestral.

**Comment by 9a3eedi** [comment]
If files are listed intentionally, I suggest providing an easy way to select or deselect the root folder and the files that are in it

**Comment by SamSchott** [comment]
I am not sure what you mean by that. There is a "Select all" checkbox which selects or deselect all items *in* the root folder. Is that not sufficient? Or are you looking for a way to specifically exclude all files or all folders from syncing?

**Comment by 9a3eedi** [comment]
You're right, it's sufficient. I was talking out of memory and forgot that the button was there

**Comment by SamSchott** [comment]
Done in v1.4.4.
