### ISSUE TITLE
Enable keyring unlocking via generic command

### ISSUE THREAD

**Issue by wolterhv** [SamSchott/maestral#380]
I would like to have maestral authenticate by reading the output of an arbitrary command. The purpose behind this is being able to have maestral use the `gpg-agent` to decrypt a pre-encrypted authentication secret. 

On the configuration file, this could be implemented by having something like the following:
```
[app]
keyring = command
keyring_command = ['gpg', '-d', '/home/homeboy/secrets/maestral-dropbox-secret.gpg']
```

This could benefit users of other password managers like `pass` too, and is possibly a superset of other already implemented authentication features.

What do you think?

**Comment by SamSchott** [comment]
I can see a number of problems with this:

1. It enables the potential execution of arbitrary code. What is to stop an attacked from modifying the config file and setting `keyring_command = ['rm', '-Rf', '/']`?
2. Maestral currently uses the [keyring](https://github.com/jaraco/keyring) package to store and retrieve auth tokens. The `keyring` config key corresponds to a supported and installed keyring backend such as Gnome keyring, etc. Bypassing this setup to only *read* a secret would mean that the new "command" backend has no way of storing secrets.
3. Actually getting an auth token yourself is not trivial. The token which you copy from the Dropbox website when authenticating is just a temporary token which Maestral exchanges for a long-lived auth token. Dropbox has a good [blog post](https://dropbox.tech/developers/pkce--what-and-why-) about this.

I can see the value in supporting other types of backends but the more secure way IMO would be to write a proper backend for the keyring package that uses `gpg-agent`.

**Comment by wolterhv** [comment]
Thanks for the quick reply.

1. It's a good point, to be honest I'm not sure what kind of control is implemented by other programs that support this kind of authentication, such as `getmail` and `aerc`. I assume they just delegate the risk to the user. However, I do think that if an attacker obtains write access to your home directory, you're pretty much screwed at that point anyway :smiley: 
2. I hadn't thought about the read-only issue, I was thinking of encrypting the token myself, and then just having maestral read it. However, I can see how this would be inconvenient for most users. I completely understand your position though, you've delegated authentication to another package and I think that's completely valid. I'll look into writing a backend for keyring!
3. Thanks for the tip!

I'll close this issue now. Cheers!
