### ISSUE TITLE
Maestral filestatus on root folder: unwatched

### ISSUE THREAD

**Issue by raffaem** [SamSchott/maestral#389]
Sam,

when I call `maestral filestatus .` on the root Dropbox folder, it says "unwatched".

It works and says "up to date" on the subfolder.

I think it's confusing.

**Comment by SamSchott** [comment]
Good point. This should return "synced".

Another issue with this API is that it currently is non-recursive. Querying the sync status of a folder will tell you nothing about its children. But that is for a different ticket...
