### ISSUE TITLE
Cannot exclude items from selective sync, possibly due to full disk

### ISSUE THREAD

**Issue by 9a3eedi** [samschott/maestral#394]
**Describe the bug**
I was using maestral and it decided to download some large files and I ran out of space. So to make space available again I try to open the selective sync dialog and exclude some folders. However, when pressing the update button, I get a "Cannot set excluded items, please try again later when idle". Restarting the app did not help. I also tried to pause the app from syncing but it never paused. At this point I'm not sure what to do.

I'm not sure if this is caused by a full disk, but this is my currently situation and it's probably related. Excluding files did work in the past for me.

**To Reproduce**
1. sync some files until the disk is full (probably)
2. try excluding some items

**Expected behaviour**
The items that were deselecting getting excluded, space getting freed up, and syncing continues.

**System:**

 - Maestral version: 1.4.1
 - Python version: 3.9.5
 - OS: Manjaro linux (ARM,, running on pinebook pro)
 - Desktop environment: KDE Plasma on Wayland 
 - PyQt version (for Linux GUI): 5.15.4

**Additional context**
The disk I'm using is ext4 running on eMMC. My platform is a bit exotic so this may also be a factor.

**Comment by 9a3eedi** [comment]
Well I managed to exclude items after rebooting and using the command line (python -m maestral excluded add <folder>) before starting the daemon, so that's good :D

Not sure if I should close the issue...

**Comment by SamSchott** [comment]
Huh, interesting. I think you are correct in assuming that the lack of disk space was the underlying issue. Did Maestral explicitly raise an error about running out of disk space? If yes, could you post the traceback from the logs to see where exactly it was raised?

When handled correctly, such errors should stop the sync daemon and release any locks that indicate a "busy" state. As a result, you should not see any error messages such as "please try again later when idle". However, this error scenario isn't well tested at the moment.

**Comment by 9a3eedi** [comment]
Maestral has not raised any error regarding disk being out of space, but KDE did. The disk had like 148MB remaining (not exactly 0) but I still consider that running out of space.

**Comment by samschott** [comment]
Closing since this seems to be resolved. The locking mechanism was overhauled some time ago.
