### ISSUE TITLE
Open Dropbox Folder opens on internet browser

### ISSUE THREAD

**Issue by dark-dryu** [SamSchott/maestral#398]
**Describe the bug**
When I chose the "Open Dropbox Folder" in the context menu of the tray icon, it launches the file manager inside firefox. 

**To Reproduce**
Maestral gui installed through pip on linux. 

**Expected behaviour**
It would be optimal that this option opened the folder in the file manager of the system.

**System:**

 - Maestral version: 1.4.3
 - Python version: 3.9.5
 - OS: Arch Linux
 - Desktop environment: i3-gaps
 - PyQt version (for Linux GUI): 5.15.4

Possible explanation:
File manager is not configured as default?

**Comment by SamSchott** [comment]
Under the hood, the command uses `subprocess.Popen(["xdg-open", url])` on Linux where `url` in this case is the file path. You can run the same command manually and check if this indeed starts Firefox or the platform's file manager.

I think you can use `xdg-mime` to query or set the default program (*.desktop entry) for an url scheme.

**Comment by dark-dryu** [comment]
Thanks for the response and for pointing out the command. Unfortunately when I run `subprocess.Popen(["xdg-open", "file:///home/user/Videos"])` in a python shell my file manager opens that path, while Maestral keeps opening the path on firefox. 

When I select the "Open Dropbox Folder" option, xdg-open gives the followin error: `x-www-browser: command not found
` and the path is opened in firefox. Could this be some hint of what is happening?

**Comment by SamSchott** [comment]
Apologies, my comment was slightly misleading. The path is passed not as a URL but as a plain path to `xdg-open`. The command to replicate is therefore `subprocess.Popen(["xdg-open", "/home/user/Videos"])`. The behavior of `xdg-open` will be subtly different for a URL vs file path. From their man page [here](https://linux.die.net/man/1/xdg-open):

> If a URL is provided the URL will be opened in the user's preferred web browser. If a file is provided the file will be opened in the preferred application for files of that type. xdg-open supports file, ftp, http and https URLs.

And further down:

> Examples:
xdg-open 'http://www.freedesktop.org/'
Opens the Freedesktop.org website in the user's default browser
xdg-open /tmp/foobar.png
Opens the PNG image file /tmp/foobar.png in the user's default image viewing application.

The actual opening routine is not part of Maestral itself but I'm using [`click`](http://github.com/pallets/click) and its `click.launch()` function to do the job. If a file URL is passed, they explicitly strip any `file://` prefixes and unquote the URL.

I believe they are doing the right thing here. Following the man page, passing a file URL should start a web browser while passing a path should start the default application for the file type (typically the platform's file manager if the path points to a folder).

You can check if this is configured correctly with `xdg-mime`. For example on my test machine with Gnome, I get:
```shell
$ xdg-mime query filetype '/home/samschott/Dropbox (Maestral)'
inode/directory
```
and
```shell
$ xdg-mime query default inode/directory
org.gnome.Nautilus.desktop
```

**Comment by dark-dryu** [comment]
Thanks for the detailed explanation. Oddly enough I get the same output as you
`$xdg-mime query filetype '/home/andreu/Dropbox (Maestral)'
inode/directory
$ xdg-mime query default inode/directory                   
thunar.desktop`

I even tried changing the default file manager to Nautilus `xdg-mime default org.gnome.Nautilus.desktop inode/directory` but still same result. I do not want to involve you more than needed, it is not a big deal personally, and use cases are limited. Feel free to close the issue, since it may be affected by something external to maestral.

**Comment by SamSchott** [comment]
That is strange, my best bet is that the environment used to start the GUI differs from the terminal environment in some way. But I really don't know which environment variables might impact this behaviour.

As you say, this is very likely the effect of some setting outside of maestral, so I'm closing the issue for now. Do let me know if you figure out the reason, I might be able to adapt the desktop entry or systemd unit file to correctly pick up / set certain environment variables.
