### ISSUE TITLE
Typo on About page claims official Dropbox client uses 500GB memory for mid-sized library

### ISSUE THREAD

**Issue by aaronrudkin** [SamSchott/maestral#401]
**Describe the bug**

From the About page:

> The focus on “simple” file syncing does come with advantages: on macOS, the Maestral App bundle is smaller than the official Dropbox app (40 MB vs 420 MB) and uses less memory (100 MB for a medium sized Dropbox on macOS vs 500 GB). The memory usage will depend on the size of your synced Dropbox folder and can be further reduced when running Maestral without a GUI.

**Expected behaviour**

You probably mean 500 MB.

**Additional context**

Additionally, I think you could benefit from mentioning native universal binary/M1/ARM support on the various public-facing product pages; that's how and why I found out about Maestral. :)

**Comment by SamSchott** [comment]
Oh, good catch! Indeed, 500 MB and not GB.

Regarding native Apple Silicon support, yes, maybe I should mention that. That info is currently hidden away in the downloads page. It isn't really a feature of the code base, it rather comes with the excellent [briefcase](https://github.com/beeware/briefcase) tool which I use to package Maestral. Nevertheless, there were a couple of hoops to jump through to actually make those builds work.
