### ISSUE TITLE
Off-center text on first startup / link dropbox page

### ISSUE THREAD

**Issue by aaronrudkin** [SamSchott/maestral#402]
**Describe the bug**

On the first startup, the introductory text is off-center/misaligned -- it's possible you intended to right-align the text but I'm not sure, I suspect left-align would be better here.

<img width="662" alt="Screen Shot 2021-06-12 at 8 57 18 PM" src="https://user-images.githubusercontent.com/14701267/121791112-1f464380-cb9b-11eb-879b-57b8a665402c.png">

The followup link page has right-aligned text as well, which doesn't look as out of place (due to the padding/spacing/layout), but still I'd expect left aligned would be the norm:

<img width="662" alt="Screen Shot 2021-06-12 at 9 03 21 PM" src="https://user-images.githubusercontent.com/14701267/121791189-0f7b2f00-cb9c-11eb-877a-06922edba6f4.png">

**To Reproduce**

Clean install on system with below information (retina display, M1 Macbook Air running Big Sur), launch.

**Expected behaviour**

Text is fully visible and does not display this way.

**System:**
 - Maestral version: v1.4.4
 - Python version: Homebrew Python3.9.5
 - OS: [e.g. Ubuntu]: MacOS Big Sur (11.3.1)

**Additional context**

Installed from release page Pkg.

(Side note: As I explore Maestral I'll probably file more bugs; my sense is more small bugs are better than omnibus issues, but let me know if you have any particular norms about issue filing I'd be happy to combine them, just let me know)

**Comment by SamSchott** [comment]
Thanks for the report! The text should be aligned to the center and not to the right. And it does appear that way on my system (Intel macOS 11.4). I suspect the difference comes from running on an M1 machine.

From the Apple's documentation [here](https://developer.apple.com/documentation/uikit/nstextalignment), the values of the `NSTextAlignment` enum are different between macOS and iOS with the values for `right` and `center` switched around. It appears that M1 machines are using the iOS definition of those enums.

I've opened a ticket https://github.com/beeware/toga/issues/1282 with toga GUI library which Maestral is using on macOS but might work around this manually until an upstream fix is released.

**Comment by SamSchott** [comment]
> my sense is more small bugs are better than omnibus issues

Absolutely, yes! Multiple small bug reports are much easier to manage. If two issues turn out to be a manifestation of the same bug, I can also close one in favour of the other.

**Comment by SamSchott** [comment]
You are using the App bundle, right? What happens if you force it to run under Rosetta translation? Does the alignment appear correctly then?

**Comment by aaronrudkin** [comment]
Confirmed that forcing to run under Rosetta fixes the text alignment, your intuition was right. I'll leave the issue open so that you can track the upstream progress.

**Comment by SamSchott** [comment]
Fixed in v1.4.5.
