### ISSUE TITLE
Mac: Nonstandard ⌘+Q behaviour + missing menu

### ISSUE THREAD

**Issue by aaronrudkin** [SamSchott/maestral#403]
**Describe the bug**

When opening Maestral for the initial setup process, ⌘+Q does not work to close the application. The menu is missing, and so you cannot close in that manner. The close button will close the window, but not terminate the application. Force quit does work.

**System:**
 - Maestral version: 1.4.4
 - OS: [e.g. Ubuntu] MacOS Big Sur 11.3.1 on an M1 Macbook Air (2020)

**Additional context**

My guess is that the ⌘+Q shortcut doesn't work because it's not actually bound to anything at the system level, it's just tied to the implementation of a system menu, which is not implemented in this case. The close button closing the window rather than the application is an HCI norm on Mac but many applications are smart enough to close the application entirely if it's a single modal like Maestral -- I'll leave it to you to think about the design implications of fixing this or not.

**Comment by SamSchott** [comment]
Good catch, this was due to a change in API in toga which I had overlooked. In fact, Maestral should quit when the setup dialog is closed.

A keyboard binding for ⌘+Q should also be possible, after all there is a "Quit" menu entry in the system tray menu.
