### ISSUE TITLE
MacOS: "Cancel and Unlink" closes Maestral window but does not exit Maestral

### ISSUE THREAD

**Issue by aaronrudkin** [SamSchott/maestral#405]
**Describe the bug**

Selecting "Close and Unlink" from the folder onboarding screen will close Maestral's active window, but not terminate the application, leaving it invisible. 

**To Reproduce**

Open Maestral. Link Dropbox account. Click "Close and Unlink".

**Expected behaviour**

Application closes fully.

**System:**
 - Maestral version: 1.4.4
 - OS: [e.g. Ubuntu]: MacOS Big Sur 11.3.1

**Comment by SamSchott** [comment]
Again, a manifestation of the same issue as in #403.
