### ISSUE TITLE
MacOS: Reopening Maestral after "Close and Unlink" offers "Unlink" option which hangs

### ISSUE THREAD

**Issue by aaronrudkin** [SamSchott/maestral#406]
**Describe the bug**

Sort of hard to describe -- the "Cannot find Dropbox folder" offers an "Unlink" button, which if clicked when Maestral is already unlinked will spawn a loading icon throbber and grey out all buttons in Maestral, but it will never succeed or fail, leaving Maestral soft-locked. Maestral, in this state, is no longer listed in the Force Quit dialog, and so needs to be killed manually via kill or Activity Monitor

<img width="712" alt="Screen Shot 2021-06-14 at 8 59 04 PM" src="https://user-images.githubusercontent.com/14701267/121971484-a9beac80-cd2d-11eb-98b6-708e0ede61c3.png">

**To Reproduce**

Install Maestral. Open Maestral. Link Maestral to Dropbox. Click "Close and Unlink". Force quit Maestro (bug described in #405). Re-open Maestral. Choose "Unlink" from dialog.

**Expected behaviour**

Upon relaunching, Maestral should know it is unlinked and offer the initial linking dialog rather than the "Cannot find Dropbox folder" dialog. Regardless, "Unlink" button should not silently hang -- it should either error loudly (e.g. note that it failed because Dropbox said it already wasn't linked) or error quietly (e.g. claim it succeeded even though it failed). Regardless, it should be possible to close Maestral from the Force Quit menu, or from standard menus or window controls when it is on this dialog box.

**System:**
 - Maestral version: 1.4.4
 - OS: [e.g. Ubuntu]: MacOS Big Sur 11.3.1 running on M1 Macbook Air

**Comment by SamSchott** [comment]
> Maestral should know it is unlinked and offer the initial linking dialog rather than the "Cannot find Dropbox folder" dialog

I think this is another manifestation of #403 where the handler when closing a window is not invoked properly.

> Regardless, "Unlink" button should not silently hang

Same as above.

**Comment by SamSchott** [comment]
I've rebuilt the app bundle with the correct version of the GUI toolkit now and will release a new version once the upstream toolkit releases theirs. That should fix all issues with closing windows and callbacks which should be executed on close.

Thanks again for spotting this!
