### ISSUE TITLE
[Feature] On macOS use Sparkle for automatic update

### ISSUE THREAD

**Issue by hstriepe** [SamSchott/maestral#412]
The app currently notifies of available updates.
For the app downloaded from the website on macOS, it would be great to use Sparkle to automate updates. I have implemented it in apps and it is very reliable and streamlined.

**Comment by SamSchott** [comment]
@hstriepe, this has come up before. I haven't used Sparkle before myself but from a first impression, the most work would be:

1. Set up an "appcast" somewhere (probably the website).
2. Include the sparkle framework in the app bundle. I could either just add it manually to the Xcode project or ideally work with the upstream [briefcase](https://github.com/beeware/briefcase) project which we use to build the app bundle. Support for including external frameworks / libraries is on their TODO list, they just haven't found a volunteer yet to do the work...

The Sparkle API itself looks really straight forward to use.

**Comment by hstriepe** [comment]
Yes. Most of it is automatic. The latest version have made setting up appcasts and checksums, etc. much easier.

Cheers,
-- Harald
+ ❤️

**Comment by SamSchott** [comment]
This is done now in v1.4.8. Setting up Sparkle was a breeze, setting up the appcast is a git of pain, especially when generating automatically from GitHub releases.

**Comment by hstriepe** [comment]
You should have tried the appcast setup 10 years ago!
