### ISSUE TITLE
An unexpected error occurred on initial sync

### ISSUE THREAD

**Issue by arabesc** [SamSchott/maestral#437]
**Describe the bug**

![image](https://user-images.githubusercontent.com/2709027/129816319-ecc8008f-1425-4e99-ab70-829a01e234c7.png)
It's permanent error, restart doesn't help.

**To Reproduce**

Install Maestral with Homebrew, link to Dropbox account, start full sync with an existing Dropbox folder.

**Expected behaviour**

Sync is succeeded.

**System:**

 - Maestral version: 1.4.6
 - Python version: 3.9.6
 - OS: macOS 11.5.2
 - Desktop environment: n/a
 - PyQt version (for Linux GUI): n/a

**Additional context**

Traceback (most recent call last):
File "Contents/Resources/app_packages/maestral/manager.py", line 557, in _handle_sync_thread_errors
File "Contents/Resources/app_packages/maestral/manager.py", line 535, in startup_worker
File "Contents/Resources/app_packages/maestral/sync.py", line 2776, in download_sync_cycle
File "Contents/Resources/app_packages/maestral/sync.py", line 2934, in apply_remote_changes
File "Contents/Resources/Support/Python/Resources/lib/python3.9/concurrent/futures/_base.py", line 608, in result_iterator
File "Contents/Resources/Support/Python/Resources/lib/python3.9/concurrent/futures/_base.py", line 438, in result
File "Contents/Resources/Support/Python/Resources/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
File "Contents/Resources/Support/Python/Resources/lib/python3.9/concurrent/futures/thread.py", line 52, in run
File "Contents/Resources/app_packages/maestral/sync.py", line 3279, in _create_local_entry
File "Contents/Resources/app_packages/maestral/sync.py", line 3324, in _on_remote_file
File "Contents/Resources/app_packages/maestral/sync.py", line 3077, in _check_download_conflict
File "Contents/Resources/app_packages/maestral/sync.py", line 834, in get_local_hash
File "Contents/Resources/app_packages/maestral/utils/path.py", line 418, in content_hash
OSError: [Errno 83] Device error

**Comment by SamSchott** [comment]
Thanks for the report! I haven't seen this one before. The error occurs when the sync process is tying to calculate the content hash of a file. According to Apple's documentation on the error code 83:

> 83 EDEVERR Device error.  A device error has occurred, e.g. a printer running out of paper.

Is your local Dropbox folder on an external drive or on the internal SSD? And have you experienced any problems with that drive?

For now, I can only recommend:

1. Running First Aid in Apple's "Disk Utility" for the drive where you Dropbox folder is located.
2. Restarting Maestral and hoping that the error disappears 

This is certainly an error which should be handled with a better message than "unexpected error", I'll look into what kind of error handling might be appropriate here.

**Comment by arabesc** [comment]
> _Is your local Dropbox folder on an external drive or on the internal SSD?_

It's a local system NVMe SSD

> _And have you experienced any problems with that drive?_

No

**Comment by SamSchott** [comment]
Hm, it is either an issue with how Python translates an error code received by the OS, or it is an issue at the file system / drive level...

Can you check which file path exactly is causing the problem? If you set the log level to debug with `maestral log level DEBUG`, try syncing again, and then look at the logs with `maestral log show -e` after the error occurs, it should show the last path / file that it was trying to sync. Trying to open that file manually, if it exists on the drive, should give a hint if anything is wrong.

Just a heads up, the log output will be *very* verbose at the debug level. You'll need to scroll through a lot of lines before getting to the last few log messages before error.

**Comment by arabesc** [comment]
I've just found a file that is in sync process.
The system doesn't allow to copy it even when Dropbox app isn't running, it gives the following error:
![image](https://user-images.githubusercontent.com/2709027/129904249-367dee83-ff27-461e-9d91-f114ec888738.png)

**Comment by SamSchott** [comment]
Ok, so the error code which you are seeing is the same as Maestral is showing: 100083 (reported as 83 by Python). Can you delete this file or does that also fail? If you can delete it, I would recommend doing so and restoring it later from Dropbox.

Otherwise, we might be back to running First Aid in Disk Utility...

> It seems there is some kind of oplock.

I'm not particularly familiar with oplocks. What leads you to this conclusion?

**Comment by arabesc** [comment]
I've deleted the file and restored it through the Dropbox web-interface.
It solves the 100083 error during the copy attempt, but I haven't checked how Maestral behaves yet.

I don't think there were some sort of system oplocks, I suspect there is some Dropbox file driver in the system that returns error when there is attempt to read from an incomplete file and Dropbox app isn't running, and when Dropbox app is running it reads either from a file or from the cloud.

**Comment by SamSchott** [comment]
Uh, are you trying to sync a folder both with Maestral and the official Dropbox client at the same time? That will result in chaos...

**Comment by arabesc** [comment]
No, I don't. I quit Dropbox app before running Maestral. But Dropbox app is installed in the system and the folder I'm trying to sync belongs to the original Dropbox app.

**Comment by SamSchott** [comment]
Right, in that case deleting the file should hopefully fix the problem 🤞Let me know how it goes. In the meantime, I'll look into providing better error messages for more exotic OSErrors.
