### ISSUE TITLE
Not seeing Team Spaces on a Business account

### ISSUE THREAD

**Issue by chrisnoden** [SamSchott/maestral#441]
**Describe the bug**
When connecting to a business account, Maestral (MacOS 11 install via brew) is only showing the contents of the Dropbox user's home directory not all the shares that are available.

**To Reproduce**
Connect Maestral to a business account that has Shared Folders.

**Expected behaviour**
Should view all available shares with the user dir being a sub-directory alongside the shared folders.

**System:**
 - Maestral version: 1.4.6
 - Python version: 3.9.6
 - OS: [e.g. Ubuntu] MacOS 11.5.1
 - Desktop environment: MacOS

**Additional context**
Tested using a Business Advanced trial

**Comment by SamSchott** [comment]
@chrisnoden, I'm not sure if I correctly understand the issue.

Do you mean shares which are "mounted" in your Dropbox directory and actively being synced? Those would show up on the Dropbox website under "All Files" and will also be downloaded / synced by Maestral. If those are not displayed in the selective sync dialog, this is definitely a bug.

Or do you mean folders which appear on the Dropbox website under "Shared"? Those will not appear or be synced unless you add them to your Dropbox folder. It would be possible in principle to list "unmounted" shared folders as well, either through the CLI with `maestral ls` or through the GUI. But AFAIK, the public Dropbox API does not allow subscribing to file change notifications for unmounted shared folders.

If you are talking about the second case, how are you planning to use it? The typical workflow with shared folders is that you *add* them to the user directory to sync them.

**Comment by chrisnoden** [comment]
@SamSchott Thanks for the very quick response.

If I login to my Dropbox Business account via the web browser, my "All files" listing (the root directory) would look like:
- Chris Noden
- Shared Folder 1
- Shared Folder 2
- Shared Folder 3
etc, with `Chris Noden` being my own "private home directory" that is not shared with/by the business admin team. There is nothing in my private home `Chris Noden` directory but plenty in the team shares.

This is also how it would look if I use the Dropbox app to sync locally - except that directory structure will be within the directory on my Mac that is used for the business account:
- ~/Business Dropbox/Chris Noden
- ~/Business Dropbox/Shared Folder 1
- etc

If I use the Mac App "CloudMounter", which also uses an API connection, then I also see the above "folders".

In all the above scenarios, I have to open one of the folders and, assuming I have permission, I can view/create/edit dirs/files within them.

However, with Maestral after I paste in the API key for the same account, the selective sync dialog is blank. When I open the new Maestral directory in finder it is empty. If I create a file in the Maestral directory and check via the Dropbox website, I can see the file appear inside my private `Chris Noden` directory. Maestral is only letting me work within that one directory. It can't be a restriction of the API if CloudMounter is able to access them.

**Comment by SamSchott** [comment]
Thanks for the clarification, I was confused by your usage of "home directory". This does indeed look like a bug but I am not sure why this is happening. I'm also confused by the selective sync dialog being completely blank, it should at least list folders inside your "private" directory.

Could you check the output of `maestral ls -l` in the terminal (after installing the command line tool)? This should explicitly list all folders together information about if they are being synced and if they are shared or private.

**Comment by chrisnoden** [comment]
As mentioned, my home directory was empty. But if I put a couple of dirs in it before linking then the selective sync does show those folders from inside my home directory.

`maestral ls -l` returns the same view
```
❯ maestral ls -l

Name   Type    Size  Shared   Syncing  Last Modified
Dir 1  folder     -  private  ✓        -
Dir 2  folder     -  private  ✓        -
```

So, maestral works but it's only working inside this home directory (or whatever dropbox calls it), rather than working in the root of my dropbox account.

**Comment by SamSchott** [comment]
Ok, I see what you mean. AFAIK, this "Team Spaces" functionality is relatively new, it is described at https://help.dropbox.com/teams-admins/team-member/team-folders. My own business account uses traditional shared folders and I wasn't quite aware of this functionality. It might require access to unique Dropbox Business API endpoints which we currently don't have / did not request.

I'll look into this and see if it's something that we should support. But I cannot promise any timeline for this. Thanks for the report!

**Comment by SamSchott** [comment]
I've had a quick look at the API docs and this looks like its actually quite easy to implement and doable with the current access level. The only difficult part will be proper handling when a user joins or leaves an existing team.

**Comment by acantril** [comment]
This is behaviour that I also see.
I was super pumped about using this - but for now it's pretty much a show stopper. Most people who dropbox for business have all of the "real" stuff outside of the usual folder. Im in the same position as @chrisnoden .. my folder is empty, everything of value is at the top level outside my folder.

My list is also empty to select what to sync... so something seems broken.

**Comment by SamSchott** [comment]
@acantril, apologies for that! As I've said earlier, including other other folders in the sync will be very easy to implement. The only "difficult" part is elegantly handling when a user joins or leaves a team. At least its on my radar now!

**Comment by acantril** [comment]
Oh man it's not your fault ... you are providing a massive service to the people screwed over by dropbox and their horrible apps - i was just dissapointed, i was all ready to make the move haha :)

**Comment by acantril** [comment]
So serious question ... ever considered a 'sponsor a feature' where 1 or more people can throw some $ your way and get features implemented quicker :)

**Comment by SamSchott** [comment]
That might be a possibility. Though my problem is not really the money, rather finding time next to my day job which I am very much planning to keep!
