### ISSUE TITLE
Badge Icons on macOS

### ISSUE THREAD

**Issue by planbnet** [SamSchott/maestral#443]
The macOS platform provides an API for displaying the sync status of files and folders as a badge icon:
https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/Finder.html

It looks like the implementation of the API would be quite trivial, but as Maestral seems to be pure python, I'm not sure if there is a way to support this without changing the whole build process, as the extension would have to be written in swift/obj-c and included in the app bundle.

**Comment by planbnet** [comment]
Just found the maestral-cocoa repo. This is probably the wrong place for this issue...

**Comment by SamSchott** [comment]
No worries, I still tend to address all issues here.

I'm aware of Finder extensions but am somewhat reluctant to take this on. The long term plan is to have a unified GUI for macOS and Gnome (using native widgets but abstracting over platform differences using the [beeware](https://beeware.org) project's tools). Introducing Finder integration, especially when it needs to live in a separate extension bundled with the app, adds platform-dependent packaging steps beyond what beeware provides out of the box.

**Comment by pbendersky** [comment]
Does Maestral provide a local API where an external app could tap to add the badges instead of having Maestral do it?
