### ISSUE TITLE
Show which files are uploading in the log and in filestatus

### ISSUE THREAD

**Issue by raffaem** [SamSchott/maestral#448]
My log currently reads:

```
2021-09-02 10:44:45 sync DEBUG: Created "[ABRIDGED]" on Dropbox
2021-09-02 10:44:48 sync DEBUG: Created "[ABRIDGED]" on Dropbox
2021-09-02 10:44:48 sync INFO: Syncing ↑ 75/82
```

But, regarding the last line, it looks like it's uploading something, but which file is it uploading?

It doesn't say.

Also:
```
$ maestral filestatus .
uploading
```

I propose to show which file it is uploading both (i) in the log in and (ii) in filestatus.

**Comment by SamSchott** [comment]
In a sense this is already possible:

1. If you set the log level to DEBUG, logs for individual files are shown. This is however very verbose, giving details on conflict resolution, etc.
2. The command `maestral activity` will show a live view of all files currently being uploaded or downloaded, together with progress for large files.

The `maestral filestatus` command shows the status of an individual file or folder, similarly to what a badge in a file manager might show. `maestral filestatus '~/Dropbox (Maestral)/my file'` will show the status of just that file.

I do see a use case for showing logs with a file level granularity at a level of INFO, without all of the noise of DEBUG.

**Comment by raffaem** [comment]
I didn't know `maestral activity`.

Thanks!

**Comment by frozenpandaman** [comment]
A display of the `maestral activity` output in an expandable GUI menu would be fantastic as a future enhancement/feature!
