### ISSUE TITLE
run daemon as non-root user

### ISSUE THREAD

**Issue by the-wes** [SamSchott/maestral#460]
I apologize if this is a stupid question or if it has been answered elsewhere. I did try looking for it.

I would like to run the maestral daemon as user "dropbox" on my headless linux system. any time I try, I get this error:

PermissionError: [Errno 13] Permission denied: '/run/user/0/maestral'

the documentation I found does suggest that it should be possible:

https://maestral.readthedocs.io/en/latest/_modules/maestral/daemon.html#sockpath_for_config

I suspect I'm just missing something simple. Please strike me with a clue bat!

thanks,
-wes

**Comment by SamSchott** [comment]
Absolutely, this should be possible. Maestral will create a socket file in the runtime directory, as determined by the environment variable `$XDG_RUNTIME_DIR`. For example, if the runtime directory is set to `/run/user/1000`, it will create the socket file in `/run/user/1000/maestral`.

I suspect that the runtime dir is incorrectly configured in your case: `/run/user/0` is typically reserved for the root user, the "dropbox" user won't be able to create a socket file there.

Did you log in as root and then switched users with `su dropbox`? In this case, you'll probably retain the environment variables from the root user. Try logging in as the "dropbox" user in the first place.

Otherwise, you will need to check if anything is overwriting `$XDG_RUNTIME_DIR` for the dropbox user.

**Comment by the-wes** [comment]
yup, that is exactly what I did. using su - dropbox worked perfectly. now I'm getting errors when using maestral autostart -Y but I can do that manually. thank you!

**Comment by SamSchott** [comment]
Glad it's working now. Just out of interest, what is the error when using `autostart -Y`?

**Comment by the-wes** [comment]
[dropbox@localhost ~]$ maestral autostart -Y
Failed to get D-Bus connection: Connection refused
Failed to get D-Bus connection: Connection refused
Traceback (most recent call last):
  File "/usr/local/bin/maestral", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/dropbox/.local/lib/python3.6/site-packages/maestral/cli.py", line 1307, in autostart
    auto_start.enable()
  File "/home/dropbox/.local/lib/python3.6/site-packages/maestral/autostart.py", line 357, in enable
    self._impl.enable()
  File "/home/dropbox/.local/lib/python3.6/site-packages/maestral/autostart.py", line 117, in enable
    subprocess.check_output(["systemctl", "--user", "enable", self.service_name])
  File "/usr/lib64/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['systemctl', '--user', 'enable', 'maestral-daemon@maestral.service']' returned non-zero exit status 1.

**Comment by SamSchott** [comment]
Thanks for the info! That also looks like an environment-related error, the `systemctl` command cannot establish a Dbus connection. This one will be more difficult to trouble-shoot. You can open a new issue if you like but I cannot promise any help in resolving it...

**Comment by the-wes** [comment]
so what I did was, I ran autostart -Y as root on a VM and copied the unit file it created, modified it slightly and pasted that into the production system. I changed the %i instances to the config name I'm using (the default of "maestral") and added a User=dropbox parameter. this appears to be working so far!
