### ISSUE TITLE
blank.gif and cup.coffee files cannot be synced - copyright issue?

### ISSUE THREAD

**Issue by jonathanlang** [SamSchott/maestral#487]
I have a couple websites with templates that include some node code and images out of the box. 
Two types of files seem to have an issue syncing (even though they exist in my local folder already anyways): 
<img width="455" alt="image" src="https://user-images.githubusercontent.com/1255480/138774570-f6a9c2a4-0c89-40e0-8d3b-f85d7323273f.png">
blank.gif are all exactly 43 bytes:
![blank](https://user-images.githubusercontent.com/1255480/138774741-2382a92f-9a93-4092-bcff-38f5f760574d.gif)
the cup.coffee files are 1 byte in size (zipped because of GitHub file type restrictions): 
[cup.coffee.zip](https://github.com/SamSchott/maestral/files/7413683/cup.coffee.zip)

Does Dropbox have some sort of copyright check on its API? Anyone else see a similar issue?

**Comment by SamSchott** [comment]
Closing since there is nothing we can do about this.
