### ISSUE TITLE
Maestral does not sort Selective Sync Dialog recognizably

### ISSUE THREAD

**Issue by posguy99** [samschott/maestral#498]
**Describe the bug**
Open the Selective Sync dialog, observe that some, but not all, directories sort to the top.  Observe that other files/folders appear semi-randomly in the file list.  The headers for both columns are clickable, implying that the sort can be controlled, but it appears to not be so.  See attached picture.

**To Reproduce**
Open the Selective Sort dialog.

**Expected behaviour**
Files and folders should be sorted correctly.

**System:**

 - Maestral version: 1.51
 - Python version: 3.9.7 (but on macOS, isn't it using a bundled version?)
 - OS: macOS Catalina 10.15.7 + Security Update 2021-007
 - Desktop environment: Finder
 - PyQt version (for Linux GUI):

**Additional context**
I attach a screenshot which I believe shows it.  Does this have something to do with case-sensitivity?  Dropbox is not, neither is the APFS filesystem I am running Maestral against

![2021-10-29-13-06-46 image](https://user-images.githubusercontent.com/408644/139496065-3bb47b7d-ab9a-41f7-8fbc-c616dc755aec.jpg)
.

**Comment by SamSchott** [comment]
Thanks for the report! Yes, this is a known limitation, I haven't implemented sorting yet. Its on the todo list and I will get there eventually!

**Comment by samschott** [comment]
Sorting is now performed alphabetically.
