### ISSUE TITLE
Support Exclusions based on partial path / filename match

### ISSUE THREAD

**Issue by cycomachead** [SamSchott/maestral#504]
**Is your feature request related to a problem? Please describe.**

I keep a lot of code repos in Dropbox, but I would really like to not sync `node_modules` since it's large and easy to regenerate. Sometimes, I also temporarily move files, but want to not sync them or delay syncing. iCloud Desktop sync uses a `.nosync` applied to a file or folder to accomplish this.

**Describe the solution you'd like**

It would be great if the list of exclusions let you specify matches that would apply to a full path. e.g. I might specify `node_modules,.nosync` as my exclusions list, beyond the typical list selection of folders. 

**Describe alternatives you've considered**

In the case of node_modules I've occasionally manually excluded this path from a few folders, but that gets tedious. 

**Additional context**
I think this is definitely a "power user" type feature, but it's the type of thing I think devs would find useful. I wasn't necessarily imagining needing the full power of regular expressions, though I certainly wouldn't complain if that existed. 

The other model I've considered is something like a gitignore style list of exclusions, though even then I think that's more flexibility than I would necessarily use.

**Comment by mcaskill** [comment]
I believe [`.mignore`](https://maestral.app/docs/mignore) should do the trick.

**Comment by SamSchott** [comment]
Yes, [mignore](https://maestral.app/docs/mignore) sounds like what you are looking for.
