### ISSUE TITLE
`maestral sharelink` truncates the urls upon piping output

### ISSUE THREAD

**Issue by xave** [SamSchott/maestral#505]
**Describe the bug**
The command `maestral sharelink list` shows the information one would expect. However, when one wants to use a tool such as `awk` to get the urls only, the url link is truncated and thus useless. The same goes for if one uses the `>>` command to put the entire output into a file. 

Currently the url will be something like https://website.com/lots-of-gibberish/**...**. The ellipses should not be there.

**To Reproduce**
`maestral sharelink list >> myfile.txt`
-or-
`maestral sharelink list | awk '{print $1}'` should give a list of all **full** URLs

`maestral sharelink list | awk '{print $1}' | grep file-i-want` should give the **full** URL of the matching file(s).

The output will all have the end of the url replaced with ellipses.
**Expected behaviour**
When piped into other commands, you would have the entire url.
**System:**
 - Maestral version: GUI 1.5.1, daemon 1.5.1
 - Python version: 2.7.16, 3.8.9
 - OS: mac OS Big Sur v11.6

**Additional context**
n/a

**Comment by SamSchott** [comment]
Thanks for the report!
