### ISSUE TITLE
Moving dropbox folder will cause maestral to loop over and over forever

### ISSUE THREAD

**Issue by raffaem** [SamSchott/maestral#520]
**Describe the bug**
1. Make the dropbox folder disappear (in my case, I mounted the partition that contained it to a different mountpoint)
2. Run `maestral gui`
3. maestral will loop over and over with no possiblity to be closed.
Here are part of what it prints in the console:
```
Traceback (most recent call last):
  File "/home/raffaele/.local/lib/python3.10/site-packages/maestral_qt-1.5.1-py3.10.egg/maestral_qt/utils.py", line 293, in run
    self.emitter.sig_result.emit(res)
RuntimeError: wrapped C/C++ object of type WorkerEmitter has been deleted

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/raffaele/.local/lib/python3.10/site-packages/maestral_qt-1.5.1-py3.10.egg/maestral_qt/utils.py", line 295, in run
    self.emitter.sig_result.emit(exc)
RuntimeError: wrapped C/C++ object of type WorkerEmitter has been deleted

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/raffaele/.local/lib/python3.10/site-packages/maestral_qt-1.5.1-py3.10.egg/maestral_qt/utils.py", line 297, in run
    self.emitter.sig_done.emit()
RuntimeError: wrapped C/C++ object of type WorkerEmitter has been deleted
QSocketNotifier: Can only be used with threads started with QThread
QImage::pixel: coordinate (0,0) out of range
```

The last line is repeated a few times, and then this whole log is repeated.

This loop can't be stopped easily. CTRL+X won't kill it. `sudo killall maestral` won't kill it. `sudo killall maestral_qt` won't ill it. I had to run `sudo killall python3` to ill it.

**To Reproduce**
See above

**Expected behaviour**
Maestral should ask where the folder was moved

**System:**

 - Maestral version: commit b829e86ce187864e539fad0f0da0b091b4d05a06
 - Python version: 3.10
 - OS: [e.g. Ubuntu] Fedora 35 Workstation
 - Desktop environment: [e.g. Gnome 3.32] GNOME 40
 - PyQt version (for Linux GUI): 5.15

**Additional context**

**Comment by raffaem** [comment]
Maestral is still showing this pop-ups although there is no maestral process running:
![image](https://user-images.githubusercontent.com/54762742/141131236-f16bd45d-9620-4669-a4cb-8ebd0970c00d.png)

**Comment by SamSchott** [comment]
Oh, that should not happen. As you have noted, there typically will be dialog allowing to choose a new folder location. Let me look into this...

**Comment by SamSchott** [comment]
BTW, did you remount the partition while Maestral was running? The error flows will be different when the folder disappears while sync is running vs when syncing is started.

**Comment by raffaem** [comment]
> BTW, did you remount the partition while Maestral was running? The error flows will be different when the folder disappears while sync is running vs when syncing is started.

I changed the mount point in `/etc/fstab` and rebooted.

Maestral was set up to start at boot

**Comment by SamSchott** [comment]
Ok, I think I've figured out the issue. I made a change some time ago about the meaning of the `pending_dropbox_folder` API of the sync daemon. I adapted the macOS GUI accordingly but forgot to do the same for Qt. The linked PR fixes this. Apologies for the inconvenience!

> I cannot change from the Qt interface either

Changing the folder from the preference pane currently requires selecting a new empty folder. This is because performing a merging of two local folders (the old one and the new selected one) is not something which I currently have implemented. It would require covering a whole lot of corner cases and figuring out a good GUI to do so.

**Comment by raffaem** [comment]
How can I kill it in the meantime?

It loops over and over.

`sudo killall maestral` and `sudo killall maestral_qt` find no processes.

**Comment by raffaem** [comment]
ok I removed maestral from autostart, installed the latest git, logged out and back in.

Now I've got this:

![image](https://user-images.githubusercontent.com/54762742/141201689-7dda885f-6d3f-4ce7-90c1-3945a24fe7de.png)

will it work if I select the new position of the Dropbox folder?

Or will it download all the folder again?

**Comment by raffaem** [comment]
uhm I tried to select the new position, but it says the folder is not empty and proposes me to merge it

**Comment by SamSchott** [comment]
> sudo killall maestral and sudo killall maestral_qt find no processes.

It will likely register as a Python process, since there is no standalone executable for Linux at the moment.

> uhm I tried to select the new position, but it says the folder is not empty and proposes me to merge it

Yes, this will offer you a merge option. It will reindex the remote Dropbox but not download any locally existing files. Merging is handled by the standard conflict resolution strategy.

**Comment by raffaem** [comment]
> Yes, this will offer you a merge option. It will reindex the remote Dropbox but not download any locally existing files. Merging is handled by the standard conflict resolution strategy.

I'm still not sure what "reindex" means exactly (maestral downloads the list of files and folders in remote Dropbox? Maybe with their hash?).

But my remote Dropbox is very big. I've moved the folder back were it was.

**Comment by SamSchott** [comment]
> I'm still not sure what "reindex" means exactly (maestral downloads the list of files and folders in remote Dropbox? Maybe with their hash?).

Exactly that, it downloads a list of files and folders with content hashes and compares them to what it finds locally. This reindexing could in principle be skipped if we could trust that the selected folder was indeed previously synced.

The current flow for moving a Dropbox folder indeed assumes that both locations are available during the move and therefore does not help when remounting a volume. In fact, there currently is no "easy" way to manually move the folder while Maestral is not running and seamlessly continue syncing. This currently requires updating the config files values directly.
