### ISSUE TITLE
Could not start or connect to sync daemon- using GUI app in macOS 10.13.6

### ISSUE THREAD

**Issue by stysedo** [SamSchott/maestral#522]
**Describe the bug**
Maestral frequently (but not always) fails to start at login/boot despite the preference setting for "Start Maestrsal at login" being enabled. The message, "Could not start Maestral - Could not start or connect to sync daemon. Please try again and contact the developer if this issue persists" is displayed. Waiting a few moments and then manually launching Maestral.app is successful. We are using Maestral entirely from the macOS Maestral.app GUI on macOS 10.13.16.

![Maestral 151 could not start on High Sierra-screen](https://user-images.githubusercontent.com/22488914/141380079-0f06b633-f387-46c2-a972-adc24466cdd2.jpg)

We have verified that ~/Library/LaunchAgents/com.samschott.maestral.maestral.plist is present with the string <Applications/Maestral.app/Contents/MacOS/Maestral>

Maestral 1.5.1
macOS 10.13.6

**Comment by SamSchott** [comment]
If this occurs infrequently and only on startup, the issue might be as simple as a timeout. Maestral allows only a few seconds for the daemon to start. There will be many different processes starting at the same time at login, causing the daemon startup to be slower than usual and GUI to give up on it.

What kind of system are you running macOS 10.13 on? I've increased the startup timeout to 20 sec in the last release and no longer see such timeouts on my own system. I do still occasional see them on the slower GitHub test runners.

**Comment by stysedo** [comment]
> the issue might be as simple as a timeout
> What kind of system are you running macOS 10.13 on? 

Yes, this machine is quite old. With a a Core2Duo CPU and a rotational HDD!

**Comment by SamSchott** [comment]
Yes, I think this explains it.

**Comment by SamSchott** [comment]
I've increased the timeout to 30 sec, that should hopefully be sufficient. Until this is released, you will just need to live with the occasional error message :)

**Comment by stysedo** [comment]
Thanks for accommodating my slow gear!
