### ISSUE TITLE
Foreground window losing focus

### ISSUE THREAD

**Issue by betalogue** [samschott/maestral#528]
**Describe the bug**
With Maestral running in the background on my Mac Pro running macOS 10.15.7, I have a problem with the system randomly putting the current foreground window (whatever the parent app) in the background. It happens intermittently, but is VERY annoying. When it happens, NO window appears to be in the foreground anymore and I have to click on the window to bring it back to the foreground.

**To Reproduce**
Keep Maestral running in the background, with macOS menu extra visible.

**Expected behaviour**
Maestral should stay idle in the background and NOT interfere with window focus!

**System:**
 - Maestral version: 1.5.1
 - Python version: 2.7.16
 - OS: macOS 10.15.17
 - Desktop environment: macOS 10.15.17
 - PyQt version (for Linux GUI):

**Additional context**
Online searches reveal similar problems in macOS over the years with some versions of Google Drive or Dropbox. Since my problem started soon after I first installed Maestral, and since the problem stops when I quit Maestral, I have reason to believe that Maestral is the culprit!

I would like to use Maestral instead of the official Dropbox app, but this is a bit too much.

**Comment by betalogue** [comment]
I am actually still struggling to pin it down. I am no longer 100% convinced that it was caused by Maestral. I have disabled a bunch of things, including Maestral, and the problem seems to be gone. I will reintroduce each of these things one at a time and test things for a few days, just to make sure. So it'll take me some time. I'll let you know when I get around to Maestral.

Thanks.

**Comment by betalogue** [comment]
Just want to update and say that, after somehow eliminating the problem (disabling a bunch of inessential menu extras, mostly), I waited for several days, then reinstalled Maestral, and haven't had the problem since. So it doesn't look like Maestral was the culprit (at least not by itself.).

I'll update again if there are any new developments.

Thanks.

**Comment by samschott** [comment]
Closing since this seems to be resolved.

**Comment by betalogue** [comment]
Yes. Thanks.
