### ISSUE TITLE
Filenames containing emojis will not sync

### ISSUE THREAD

**Issue by cfarvidson** [SamSchott/maestral#532]
**Describe the bug**

I noticed that a file that had an emoji in the filename did not get synced. `Some filename 🚀.pdf` did not work for me. 

**To Reproduce**

Rename a file to `Some filename 🚀.pdf` and see the issue in the `Show sync issues` menu.

**Expected behaviour**

The file should sync or maybe a better error message pointing to the fact that the filename is invalid? ¯\_(ツ)_/¯ 

**System:**

 - Maestral version: Version 1.5.1 (40)
 - Python version: ? (I installed the mac app bundle)
 - OS: macOS 12.0.1
 - Desktop environment: 
 - PyQt version (for Linux GUI):

**Additional context**

This is the error message on the machine with the file.

<img width="383" alt="Screenshot 2021-11-26 at 13 25 51" src="https://user-images.githubusercontent.com/7823236/143581144-ca55c3e1-92e5-4215-b807-2355f1fddd6f.png">

**Comment by tjluoma** [comment]
This is a limitation of Dropbox:

https://help.dropbox.com/files-folders/sort-preview/file-names

**Comment by cfarvidson** [comment]
Closing the issue 🙂
