### ISSUE TITLE
Docs for installing GUI result in "no matches found: maestral[gui]" when using ZSH

### ISSUE THREAD

**Issue by Zeustopher** [SamSchott/maestral#543]
**Describe the bug**
The documentation at https://maestral.app/docs/installation and https://github.com/SamSchott/maestral/blob/master/README.md#python-package-using-pypi say to install the GUI issue the following command:
```sh
$ python3 -m pip install --upgrade maestral[gui]
```
However, on my system this initially resulted in an error message `zsh: no matches found: maestral[gui]`. It appears that it was caused by `zsh` (shell I'm using instead of `bash`) using the `[ ]` for pattern matching / globbing. See https://stackoverflow.com/a/30539963 for a similar complaints and explanation on what is causing it.

I had to put quotes around the package name in order for it to install:
```sh
$ python3 -m pip install --upgrade 'maestral[gui]'
```

**Expected behaviour**
In order for the instructions to be run on as many systems as possible without any issue I'd suggest adding the above quotes to the documentation.

**System:**
 - Maestral version: N/A
 - Python version: Python 3.8.10
 - OS: Linux Mint 20.2
 - Desktop environment: Cinnamon
 - PyQt version (for Linux GUI): N/A
 - Shell: ZSH (via Oh-My-Zsh)

**Comment by SamSchott** [comment]
Good catch. Yes, `zsh` and `bash` both use square brackets for globbing / pattern matching. Where `bash` and `zsh` differ is what happens when a pattern doesn't match any file. Bash passes the pattern unchanged to the command.`zsh`, by default, signals an error. This is why the brackets will need to be escaped in `zsh`.
