### ISSUE TITLE
maestral history returns changes made in the future

### ISSUE THREAD

**Issue by kieranhood** [samschott/maestral#544]
**Describe the bug**
Running command 'maestral history', or "Show Recent Changes" from the menubar shows file changes made in the future (year 2023).

**To Reproduce**
Installed app and made first sync with dropbox.

**System:**
 - Maestral version: 1.5.2 Mac Package
 - Python version: 3.9.9
 - OS: macOS 12.0.1

Is there a way to delete the delete the recent history?

**Comment by SamSchott** [comment]
Oh, that is funky. Which modified dates does the website show for those files?

You can reset the sync history by running the following command in a Terminal:
```shell
$ sqlite3 ~/Library/Application\ Support/maestral/maestral.db "DROP TABLE history;"
```
The sync history only is there for informational purposes, resetting won't affect anything else.

**Comment by kieranhood** [comment]
It was showing various times from the 6th June 2023. Ran that command and its all good again. Thanks!

**Comment by samschott** [comment]
Should be fixes now, we now replace modified times from the future with the time of sync.

**Comment by 12elotro** [comment]
I have the same problem, it shows changes in the files in the future year 2038, and those changes always appear first as they are the most recent.

I execute the order:

`sqlite3 ~/Library/Application\ Support/maestral/maestral.db "DROP TABLE history;"`

But it shows the following result:

Error: unable to open database "/home/david/Library/Application Support/maestral/maestral.db": unable to open database file

My knowledge is limited, I am writing to you how I installed Maestro on Linux Mint 20.3

```
$ apt install python3.8-venv

$ python3 -m venv maestral-venv

$ source maestral-venv/bin/activate

(maestral-venv)$ pip install --upgrade pip

(maestral-venv)$ python3 -m pip install --upgrade 'maestral[gui]'

(maestral-venv)$ sudo apt-get install '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev

(maestral-venv)$ maestral gui
```
