### ISSUE TITLE
Clicking on notification does nothing useful

### ISSUE THREAD

**Issue by felibb** [SamSchott/maestral#547]
**Describe the bug**

Clicking on an "Items synced" notification from Maestral causes a Dock icon for Maestral to appear, but nothing else (seemingly) happens.

**To Reproduce**

* Enable notifications for Maestral
* Wait for Maestral to sync something to PC
* Receive notification from Notification Center
* Click on notification

**Expected behaviour**

Maybe open a folder with said synced items? Maybe see what official client does in a similar use case.

**System:**

 - Maestral version: 1.5.2
 - OS: [e.g. Ubuntu] macOS 10.15.7

**Additional context**

I don't know what an action should be, but right now it's pointless. Unclear why a Dock icon appears either, since no preferences window, nor any other Maestral window, is open at that point. Hope this is clear, and not a dupe of some earlier bug. Thanks.

**Comment by SamSchott** [comment]
In case of a single synced file or folder, clicking on the notification will open a new Finder window showing that item. In case of multiple synced items, there is currently no action at all (as you have discovered). It could potentially make sense to open all containing folders if multiple items are synced, though I am not sure how much the added value would be.

**Comment by felibb** [comment]
@SamSchott thanks. Opening multiple folders is indeed pointless, if not annoying. Perhaps a single notification per item, but that could pollute the notification centre in no time.

Still, the Dock icon should not appear if the app has no windows to show.

**Comment by SamSchott** [comment]
> Still, the Dock icon should not appear if the app has no windows to show.

Fair point.

Also note that currently you will need to click the "Show" button of the notification to reveal the item, not just the notification itself. This could probably also be changed as clicking anywhere on the notification is often an intuitive action.
