### ISSUE TITLE
Preferences Question/Guidance

### ISSUE THREAD

**Issue by Duhkha8** [samschott/maestral#560]
Hi, I learned of Maestral from David Sparks and the MPU podcast. I just installed the macOS App Bundle. Simply curious about a few things:

1. I assume you advise checking "Start Maestral on login" so app is always syncing with DB, esp. if daily workflow is DB dependent? One reason I ask is that I don't see it now in SP > Users & Groups > User > as one of my account login items.
2. Related, It's basically just a menu bar app (technical term, I know 😄) so any need to "hide" Maestro in SP > Users & Groups > User > Login Items?
3. Any problems if I change local directory name from Dropbox (Maestral) to Dropbox?

Appreciate your thoughts. Kind regards,

-John

**Comment by samschott** [comment]
@Duhkha8, welcome as a new user!

> I assume you advise checking "Start Maestral on login" so app is always syncing with DB, esp. if daily workflow is DB dependent?

Absolutely up to you. Personally, I typically start it at login. Maestral won't show up as a login item in System Preferences but should nevertheless start at login. This is a bit confusing but its unfortunately the only way to manage startup properly if you have multiple instances of the same program to sync different accounts. If you prefer, you can of course uncheck "Start Maestral on login" and add it as a login item yourself instead.

> so any need to "hide" Maestro in SP > Users & Groups > User > Login Items?

No need to hide it. It will manage this on its own.

> Any problems if I change local directory name from Dropbox (Maestral) to Dropbox?

No problems. The default name "Dropbox (Maestral)" was just chosen in case people want to try it out while still running the official client.

**Comment by Duhkha8** [comment]
Grateful. Thank you. Happy New Year.
