### ISSUE TITLE
System (minimal) requirements for Mac OS?

### ISSUE THREAD

**Issue by mgrn0** [samschott/maestral#578]
**Describe the bug**
The github repository readme states that the minimum requirement for Mac OS is "**10.14. High Sierra**", that is misleading since **10.14** was called "_Mojave_", whereas **10.13** was called "_High Sierra_".

So - what is is the actual minimal Mac OS version needed to run Maestral?

**To Reproduce**
Open https://github.com/samschott/maestral#system-requirements

**Expected behaviour**
See the minimal system requirements, would also be nice on the maestral website.

**System:**
not applicable

**Additional context**
not applicable

<img width="620" alt="Screenshot 2022-01-13 at 12 27 06" src="https://user-images.githubusercontent.com/3019226/149322334-706c8ee4-6f33-49ae-9357-83f451b26bd0.png">

**Comment by samschott** [comment]
Thanks for catching this! It should be macOS 10.13 High Sierra.

**Comment by mgrn0** [comment]
awesome, thanks and - it works perfectly on 10.13 :) horray!
