### ISSUE TITLE
Install command line tool from preferences won't do anything

### ISSUE THREAD

**Issue by ubidefeo** [samschott/maestral#587]
**Describe the bug**
I wanted to do a bit of debugging of a minor sync issue and thought I'd install the command line tool from __preferences__ but nothing happens.
I have tried looking at the specified path (`/usr/local/bin') but the binary is not there.
Should I install it via `pip`?
Are there any chances doing so will break the behaviour?

**To Reproduce**
* open __preferences__
* click the __Install__ button
* wait (there's not feedback to the user)
* open a shell
* try to execute `maestral`
* nothing happens
* `cd /usr/local/bin`
* `ls -la | grep -i maestral`
* the binary is not there

**Expected behaviour**
* install button should at least prompt something to the user 
* tool should be installed

**System:**

 - Maestral version: 1.5.2 / 1.5.2
 - Python version: 3.9.8
 - OS: Mac OS 12.1 (Monterey)
 - Desktop environment: n/a
 - PyQt version (for Linux GUI): n/a

**Comment by samschott** [comment]
That's annoying, I thought I had fixed all issues with the CLI installation. Could you check the following?

1. I assume that `/usr/local/bin` exists?
2. Who is the owner of `/usr/local/bin`? `root` our your own user account?
3. Could you start Maestral from the Terminal by running `/Applications/Maestral.app/Contents/MacOS/Maestral` and try again? Are any errors printed to the Terminal?

In principle, installing the CLI should also work if `/usr/local/bin` does not exist or is owned by root, macOS should then show you an authorisation dialog. The way we request this authorisation should also work on M1 Macs (at least it used to when I last had access to one). Answering the above questions would just help me to know which code path is being executed.

**Comment by ubidefeo** [comment]
1. it exists
1. owner of `/usr/local/bin` is `root:wheel` (I'm system admin)
1. `Contents/Resources/app_packages/toga_cocoa/app.py:115: DeprecationWarning: There is no current event loop
[Cocoa] Not implemented: ScrollContainer.set_on_scroll()`

that's all I get.
`/usr/local/bin` is there because I have Segger's tools (JLink and such)

**Comment by ubidefeo** [comment]
@samschott 
I have an update on this one!
It seems that I had two instances running, one was hung.
I killed both, retried the installation and I got the security popup and it correctly installed :)

I will close this issue.
Thank you for looking into it, though 🙏🏼

**Comment by samschott** [comment]
Excellent, I'm glad its resolved.
