### ISSUE TITLE
v1.5.3 (M1) crashes on startup and at every upload

### ISSUE THREAD

**Issue by minimondo** [samschott/maestral#602]
The previous version was rock-solid. The latest version requires starting exactly 3 times manually before it launches without crash.

Also, every time a file is changed on the M1 DropBox folder (ie. an upload) Maestral again crashes with the same error log (see attached). I get "invalid destination port" followed by a SEGV.

[MAESTRAL.txt](https://github.com/samschott/maestral/files/8022909/MAESTRAL.txt)

**Comment by samschott** [comment]
Ah, damn. From the crash report, this may be related to #30 and updating the latest version of the Sparkle framework. I'm surprised though that the crash appears appears to be triggered by a download sync.

I should be getting an M1 Mac hopefully next month, this should make debugging easier.

**Comment by minimondo** [comment]
Ah. I quit and uninstalled my package-installed Maestral; I then installed it via "brew". Now it seems to be running flawlessly!

**Comment by dansteen** [comment]
I see this as well.  The crash only happens when I paste in the auth token, and it starts to sync.  If I put in an invalid auth token it does not crash.   

As a note, the times it crashed I got an error message from the dropbox auth page (https://www.dropbox.com/1/oauth2/authorize_submit).  It's not that it didn't create the auth token, but rather that I got a red box saying something like "could not complete request" even though it provided a token.   I'll try and grab a screenshot next time I see it.

**Comment by dansteen** [comment]
The error was "could not complete request".  I was not able to get a screenshot fast enough, however, I did manage to have maestral work by clicking the "accept all" button on the GDPR cookie popup prior to authorizing and getting a token. 

No idea if that is really the fix though :shrug:

**Comment by samschott** [comment]
Oh, the "could not complete request" error is not related to Maestral, this is a Dropbox internal error which is only temporary. The hard crash of the Maestral GUI however should be fixed in the latest pre-release.

**Comment by samschott** [comment]
I've finally gotten my hands on an Apple Silicon machine and was able to fix a good number of different crashes on ARM.

You can try out the latest pre-release version from [here](https://nightly.link/samschott/maestral-cocoa/suites/5566330263/artifacts/179904155) and and report back if you like. A warning about this version: it will trigger a full reindexing of the Dropbox folder on first run. This should not take too long though, especially on M1 machines.

**Comment by samschott** [comment]
The new release is out now so I'm closing this. Note that one of the crashes was related to update checks, so you might need to download it manually.
