### ISSUE TITLE
how do I clear "sync issues" ?

### ISSUE THREAD

**Issue by schwerd** [samschott/maestral#608]
noticed app gave me a couple of sync issues.  I corrected them.  how do I get rid of the "sync issues" notices? there seems to be no way to delete them or clear them once I've dealt with the issue.

thank you

**Comment by samschott** [comment]
In principle, they should clear automatically once a successful sync is registered for that path. However, there currently is a bug resulting in some upload sync issues not being cleared after the corresponding item is deleted. In this case, completely restarting the Maestral should clear them.

**Comment by schwerd** [comment]
cool
thank you

love this app
