### ISSUE TITLE
Wrong size of max available on DB account

### ISSUE THREAD

**Issue by petitJo** [samschott/maestral#621]
**Describe the bug**

Hi! In the drop down menu of Maetral, as in the preference box, the max capacity displayed is not correct.
It says 10.2GB but I own 9.5 of storage. (is it the same unity?)
**To Reproduce**

**Expected behaviour**

**System:**

 - Maestral version:1.5.3
 - Python version: 
 - OS: [e.g. Ubuntu]macOS Monterey 12.2.1
 - Desktop environment: [e.g. Gnome 3.32]
 - PyQt version (for Linux GUI):

**Additional context**

Thanks!

**Comment by samschott** [comment]
Indeed, this comes back to different units being used. Maestral uses the decimal definition
```
1 GB = 100^3 bytes = 10^9 bytes
```
while Dropbox uses the binary definition
```
1 GB = 1024^3 bytes = 2^30 bytes
```
In macOS, space usage is reported in the decimal definition as well, therefore the space usage shown by Maestral corresponds to the size of your Dropbox folder if you download all items. In Linux the definition used depends on the individual tool.

See also https://en.wikipedia.org/wiki/Gigabyte and https://en.wikipedia.org/wiki/Binary_prefix#Operating_systems.
