### ISSUE TITLE
GUI Maestral stuck on "Setting" status

### ISSUE THREAD

**Issue by JeffCGD** [samschott/maestral#638]
**Describe the bug**
My install of Maetral on MacOS Mojave 10.14.6 is stuck at the "Setting Up" state, after loosing connection to dropbox. No amount of re-authorising with Dropbox, reinstalling Maestral, nuking preferences or support files, or anything else I can think of, seems to help.

**To Reproduce**
Launch Maestral. Get tired of waiting. Quit Maestral. repeat.

**Expected behaviour**
I would expect Maestral to load, synch, and operate as it did previously 

**System:**
 - Maestral version: 1.5.3
 - Python version: Python 2.7.16 (default, Mar 25 2021, 18:52:10) 
 - OS: MacOS Mojave 10.4.6
 - Desktop environment: MacOS Mojave 10.4.6
 - PyQt version (for Linux GUI): NA

**Additional context**

![Screen Shot 2022-03-09 at 7 24 44 AM](https://user-images.githubusercontent.com/101864478/158972987-e8370de4-0b23-488f-ae25-f3cea41a43cf.jpg)

**Comment by jamieshaw** [comment]
I've first experienced this issue upgrading fro 1.5.3 -> 1.6.0 on macOS High Sierra 10.13.6.

Same issue, getting stuck at "Setting up…" — logs show last message as "indexing remote Dropbox".
Removing the maestro config and Dropbox target folders, and starting from fresh with 1.5.3 fixes the issue.  Same issue encountered when upgrading (again) to 1.6.0, or fresh install of 1.6.0.

**Comment by samschott** [comment]
This may be the same issue as #644. Could you check the logs for error messages?

**Comment by samschott** [comment]
I'm afraid GitHub does not preserve email attachments, could try posting the log explicitly here?

**Comment by samschott** [comment]
v1.6.1 is now out with a fix.
