### ISSUE TITLE
on version 1.6.1 wont' start

### ISSUE THREAD

**Issue by kurokirasama** [samschott/maestral#649]
**Describe the bug**

I just upgraded maestral to latest version 1.6.1. Runing `maestral gui` gives me
`maestral-qt>=1.6.1 required but you have 1.5.2`
Trying to upgrade `maestral[gui]` gives me:
```
ERROR: Could not find a version that satisfies the requirement PyQt6-Qt6>=6.2.3 (from PyQt6->maestral-qt>=1.6.1; sys_platform == "linux" and extra == "gui"->maestral[gui]) (from versions: none)
ERROR: No matching distribution found for PyQt6-Qt6>=6.2.3 (from PyQt6->maestral-qt>=1.6.1; sys_platform == "linux" and extra == "gui"->maestral[gui])
```
Nothing happen if i try to open via application icon.
`maestral start` works just fine.

**To Reproduce**

I upgraded via:
`pip3 install --upgrade maestral`
I trying upgrading maestral[gui] in the same way.
The other steps are detailed above.

**Expected behaviour**

It should open gui icon and start syncing

**System:**

 - Maestral version: 1.6.1
 - Python version: Python 3.8.10
 - OS: [e.g. Ubuntu] Ubuntu 20.04.4
 - Desktop environment: [e.g. Gnome 3.32] GNOME Shell 3.36.9
 - PyQt version (for Linux GUI): 5.14.1

**Additional context**

will downgrading solve the issue temporarily... how do I downgrade?

**Comment by samschott** [comment]
Downgrading will solve the problem, you can can install a specific version with `pip3 install maestral==1.5.3`. Though if you already ran the sync daemon by itself, without the GUI, it will have migrated some of the database, so you may need to unlink and relink after downgrading if you see database errors.

However, before you do that, could you try to install PyQt6 individually on your machine? There should be no issue installing it on Ubuntu 20.04, this is one of the platforms which I regularly test before releases.

**Comment by kurokirasama** [comment]
I could get it working, running:
```
python3 -m pip install pip setuptools --upgrade
pip install PyQt6
```

**Comment by samschott** [comment]
Good to know, thanks! I suspect that the wheel tags from PyQt6-Qt6 are not quite compatible with older versions of pip.
