### ISSUE TITLE
1.6.1  Sync Issues

### ISSUE THREAD

**Issue by Duhkha8** [samschott/maestral#650]
Hi, is this due to emojis in file name?

<img width="360" alt="image" src="https://user-images.githubusercontent.com/87775724/160012744-e33564b2-1e69-4c39-b3a0-72966e2fe77c.png">

I'm running macOS 12.3.

Thank you.

**Comment by samschott** [comment]
Yes, it's the emojis. Unfortunately, Dropbox makes the rules here. Those are some great looking filenames though!

**Comment by Duhkha8** [comment]
Thanks for your response. I appreciate this. 

Take the life-changing LYT course to get those files yourself. 😊

https://www.linkingyourthinking.com/

Cheers,

-John

**Comment by samschott** [comment]
Thanks for the recommendation :) I'll close the issue since there is nothing we can de here.
