### ISSUE TITLE
Missing Docker Hub ARMv7 images for Maestral > 1.4

### ISSUE THREAD

**Issue by Sincasios** [samschott/maestral#651]
**Is your feature request related to a problem? Please describe.**
On Docker Hub the last version available for ARMv7 devices (like Raspberry Pi 2) is 1.4:
https://hub.docker.com/r/maestraldbx/maestral/tags

**Describe the solution you'd like**
Add updated images for ARMv7

**Describe alternatives you've considered**
Use 1.4 version 😆

**Comment by Sincasios** [comment]
Ok, I see he commit where ARMv7 was removed https://github.com/samschott/maestral/commit/0282b1731b3e4b5746470fdf131a85a3c100ba54 😭 

So I supose that i can close this request.

**Comment by samschott** [comment]
Yeah, sorry about that. There are no cryptography wheels available for musllinux on ARMv7 which makes the installation a bit more difficult.

However, it looks like the latest 3.10-alpine3.15 Docker image now should have a sufficiently new Rust v1.59 available. It should therefore be possible to build cryptography from source when creating the Docker image.

The instructions for building cryptography on Alpine: https://cryptography.io/en/latest/installation/#alpine

If you fancy trying, a PR would be welcome :)
