### ISSUE TITLE
Cannot upgrade gui from 1.5.2 to 1.6.1

### ISSUE THREAD

**Issue by bjubes** [samschott/maestral#655]
**Describe the bug**
When upgrading on linux via: `python3 -m pip install --upgrade 'maestral[gui]'`
I get the following error:
```
ERROR: Could not find a version that satisfies the requirement PyQt6-Qt6>=6.2.3 (from PyQt6->maestral-qt>=1.6.1; sys_platform == "linux" and extra == "gui"->maestral[gui]) (from versions: none)
ERROR: No matching distribution found for PyQt6-Qt6>=6.2.3 (from PyQt6->maestral-qt>=1.6.1; sys_platform == "linux" and extra == "gui"->maestral[gui])
```
**To Reproduce**
ran upgrade command above

**System:**

 - Maestral version:  1.6.1
 - Python version: 3.8.10
 - OS: Ubuntu 20.04 LTS

**Comment by peterhoeg** [comment]
It's probably a bit premature to start using qt6. Not many distributions carry it, so for linux at least, this effectively prevents people from updating.

**Comment by samschott** [comment]
This looks like a duplicate of #649. Could you try updating pip first?

**Comment by peterhoeg** [comment]
On NixOS we don't carry qt6 yet, so we will have to stay with 1.5.x for the foreseeable future.

**Comment by bjubes** [comment]
upgrading pip worked. Thanks!
