### ISSUE TITLE
Stuck at "Indexing" with low number

### ISSUE THREAD

**Issue by riesentoaster** [samschott/maestral#656]
**Describe the bug**
Maestral is stuck at `Indexing [n]...`, where `[n]` has only increased from 1 to 6 in the past 36 hours. Sometimes, shortly after the number increases, the logs show a line of `sync INFO: Syncing ↓ 1/1`. No major changes have occurred in the meantime, neither local nor remote.

**To Reproduce**
Don't know, sorry.

**Expected behaviour**
Finishes indexing, starts syncing.

**System:**

 - Maestral version: 1.6.1, both cli and GUI
 - Python version: 3.9.10
 - OS: MacOS 12.3, M1 Pro

**Additional context**
## Logs since the issue started

[logs.txt](https://github.com/samschott/maestral/files/8379753/logs.txt)

**Comment by samschott** [comment]
Oh, that is funky. Does the problem persist after restarting Maestral?

Two things that might help to debug this:

1. Set the log level do debug with `maestral log level debug`.
2. Check if it is stuck at a particular file with `maestral activity`.

**Comment by riesentoaster** [comment]
- Restarting the computer (which obviously restarts Maestral as well) does not fix the issue.
- I changed the log level and will append the output. We are now up do `Indexing 21...`.
- `maestral activity` shows `Status: Indexing 21..., Sync errors: 0`

**Comment by samschott** [comment]
Thanks, that is very helpful, though even more enigmatic. It appears that the Dropbox API keeps returning empty sets of changes while insisting that there are more changes to fetch. Therefore the log lines such as
```
2022-04-01 10:24:57 sync DEBUG: Remote changes: []
```
followed by an incremented cursor to paginate through the changes
```
2022-04-01 10:24:58 sync DEBUG: Remote cursor saved: ...
```
I suspect this is a bug the Dropbox side.

Is this happening during your initial sync or was the account already linked previously? In the second case, could you try to rebuild Maestral's index ("Rebuild Index..." in the menu bar)? This will not only rebuild the local index but also reset the cursor which is used to listen for and paginate through changes on Dropbox servers. There is a chance that this might fix the issue for you.

**Comment by riesentoaster** [comment]
So I tried rebuilding the index, and now, an hour later, it's stuck again, this time at `Indexing 4000...`.

[Logs](https://github.com/samschott/maestral/files/8400131/logs.txt)

**Comment by riesentoaster** [comment]
@samschott I deleted the app (initially installed with the dmg), deleted all related files from `~/Library`, reinstalled the app (again from the dmg), and I'm still stuck at `Indexing 4008...`. Before the whole uninstall/install process, it went up to `Indexing 4021...`, I think.

Any other handles on what I could do here?

**Comment by riesentoaster** [comment]
Update:

- I deleted
  - maestral from `Applications`
  - everything connected to maestral from `Library`
  - my local dropbox copy (moved it to an other folder)
- I then reinstalled maestral and started the sync. After about 10min, it is now stuck again at `Indexing...`.
- I compared the newly downloaded files to the old copy, the only differences seemed to be the files I changed during this issue.
- I also compared the newly downloaded files to a download of all files from the Dropbox website (downloaded all files as a zip), and found no differences(!)

So it seems that the download works fine, it just finds an issue somewhere and ends up in a more or less endless loop. 

- `maestral activity` shows only `Status: Indexing 3867..., Sync errors: 0`
- [`maestral log show` output](https://github.com/samschott/maestral/files/8450879/out.txt)

**Comment by samschott** [comment]
Do you mean that all files are actually downloaded, despite the indexing apparently stalling around 4000 items? How many files do you have in your Dropbox? Pressing `CMD+I` on the fully downloaded folder should give you that information.

**Comment by riesentoaster** [comment]
Exactly. All files were downloaded and then the app got stuck at indexing, which seems strange even to me.

My backup tells me that there were about 3.2k files in that Dropbox at that time, although I'm not super confident that this number is correct. It might be larger than the file count, but the issue appeared with a very low counter as well (see very top of issue) and I'm not quite sure what to make of this.

I had to switch to the original app about a week ago because I needed it to just work for now. I'm unsure when I will find time to test this again. (Or when the constant nagging for root access by the Dropbox app gets on my nerves too much. Man, this app is terrible, and there are good reasons why I usually use Maestral.)

**Comment by riesentoaster** [comment]
Update:
- Deleted Dropbox app again
- removed all Maestral data from `~/Library`
- reinstalled Maestral from the `.dmg`

It seems to work for now, so I'll close this issue. I have no idea what made Maestral hang. Feel free to ask me some more questions if you would like to investigate this issue further. I'll reopen if the issue reappears.
