### ISSUE TITLE
The CLI has issues with correctly displaying time

### ISSUE THREAD

**Issue by TheUnscarred** [samschott/maestral#665]
The latest update (1.6.1) seems to have caused certain CLI issues with displaying time.
For example, the GUI _correctly_ states that the time a certain file has been last modified is `06 Apr 2022 at 17:01`.
The command `maestral history` displays the time as `1649257319.762771`. This particular issue did not occur prior to 1.6.1, and `maestral history` used to display the correct time before (with no timezone discrepancies).
However, while writing this bug report I have also noticed that the command `maestral ls -l` displays the time as `06 Apr 2022 at 15:01`. I had not noticed this timezone discrepancy before, but I don't know for a fact that it has been caused by the latest update.

The operating system is Manjaro (XFCE edition). Python is version 3.10.2. Maestral has been reinstalled* via `pip` in its own virtual environment. All required packages have also been updated.

*Upgrading to 1.6.1 via `pip` did not go smoothly (I assume because of the switch to PyQt6), so I just deleted the virtual environment and installed Maestral again in a new one. I am writing this to clarify that the issues in this report pertain to a fresh installation of Maestral.

**Comment by samschott** [comment]
Thanks for the detailed writeup! The datetime conversion apparently got a bit muddled up in the API changes for v1.6.0.
