### ISSUE TITLE
error attempting to update to latest version from linux 1.5.3

### ISSUE THREAD

**Issue by dhdurgee** [samschott/maestral#687]
I started getting the version errors reported in another issue and in case it was due to a back level on my system I attempted to upgrade.  I failed.  attached please find a log of what happened.

[maestral-update.log](https://github.com/samschott/maestral/files/8810571/maestral-update.log)

How do I get the update applied?

**Comment by samschott** [comment]
Alas, Maestral now requires PyQt6 for it's Linux GUI. The most common cause for the installation error is an older version of pip. However, I can see that you updated pip as well in the logs.

PyQt6 wheels are available for all common platforms, I'm therefore surprised by the installation error. What platform are running on? And which processor type?

In any case, if you are affected by #683, updating Maestral won't help. This is server-side bug on the Dropbox side. They are aware of the issue and working on a fix.

**Comment by dhdurgee** [comment]
Yes, I am seeing issue #683, which lead to my attempted update of maestral.

I am running linux mint x64 20.3 here.  Further details:

`dhdurgee@z560:~/Downloads$ uname -a
Linux z560 5.4.0-113-generic #127-Ubuntu SMP Wed May 18 14:30:56 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
dhdurgee@z560:~/Downloads$ 
`

Let me know if you need more information.  For example, how can I provide you with details on qt support?

Can I continue to run the 1.5.3 GUI while updating the rest of the package?  If so, how can this be done?

**Comment by samschott** [comment]
Of course, you can always run the daemon without a GUI..

**Comment by dhdurgee** [comment]
I just did the upgrade of setuptools:

`dhdurgee@z560:~/Downloads$ pip3 install setuptools -t /usr/local/lib/python3.8/dist-packages/ --upgrade
/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py:122: PkgResourcesDeprecationWarning: 0.23ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py:122: PkgResourcesDeprecationWarning: 0.1.36ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
Collecting setuptools
  Using cached setuptools-62.3.2-py3-none-any.whl (1.2 MB)
ERROR: launchpadlib 1.10.13 requires testresources, which is not installed.
Installing collected packages: setuptools
Successfully installed setuptools-62.3.2
dhdurgee@z560:~/Downloads$`

Unfortunately still get the same error attempting to update maestral.

**Comment by dhdurgee** [comment]
In case it makes a difference, this is the cinnamon version:

`dhdurgee@z560:~/Downloads$ cinnamon --version
Cinnamon 5.2.7
dhdurgee@z560:~/Downloads$ 
`

**Comment by dhdurgee** [comment]
I like the GUI showing what is going on with maestral and would miss it.  Am I missing any important updates running my current version?  I guess I will live with it until we get this sorted.

**Comment by dhdurgee** [comment]
Just did a bit of looking in Synaptic package manager this morning and from what I see it doesn't look like QT 6 is even an option in the repositories.  I see various QT 5 libraries listed and installed, but looking for QT 6 comes up empty except for version 6 of various QT based packages.

This is the current release of Linux mint cinnamon, so perhaps you are a bit premature in migrating to QT 6?  Any possibility of offering both QT 5 and QT 6 for a transition period?

**Comment by samschott** [comment]
See #657 for my motivation for that move. In hindsight, I agree, it was a bit premature. I am hoping to support both Qt5 and Qt6 for a transition period but did not have the time yet to make the changes.

That being said, you should theoretically be able to install PyQt6 on your system from PyPI (as you are trying...), even if Qt6 is not available through your platform's native package manager. I do have reports of the installation succeeding without problems on Mint.

**Comment by dhdurgee** [comment]
So I guess I would need to issue a command to install PyQt6 first and then try upgrading maestral again?  What specific command should I use to install PyQt6?

**Comment by dhdurgee** [comment]
I just thought to check and it appears that Qt5 will be fully supported until 26 May 2023 and by subscription until 2025.

Given this, should you not continue to support Qt5 until such time as it reaches end of free support?

**Comment by samschott** [comment]
Free Qt5 support is indeed no longer available now, so I'm closing this. Ideally, it would be great to support both Qt5 and Qt6, but this is unfortunately beyond the scope of a hobby project.
