### ISSUE TITLE
Being able to pipe output of `ls` to another shell command

### ISSUE THREAD

**Issue by elmimmo** [samschott/maestral#691]
**Is your feature request related to a problem? Please describe.**
It is difficult to batch add exclusions with the command line.

**Describe the solution you'd like**
The output of the command `maestral ls` should be pipeable to other commands, such as `maestral excluded add`.

**Describe alternatives you've considered**
Copy & paste into a text editor, which is inconvenient.

**Additional context**
So whenever I want to remove the exclusion of a directory which is itself a subfolder of an already excluded directory, I need to first remove the exclusion of the later, and then add the exclusion of all the subfolders but the one I want to have locally. What I would have gone for would be something along the lines of:

```shell
$ maestral pause
$ maestral excluded remove "$parent_folder"
$ maestral ls "$parent_folder" | \
   grep -v "$subfolder" | \
   while read this_dir
   do
       maestral excluded add "${parent_folder}/${this_dir}"
   do
$ maestral resume
```

but each entry of `maestral ls` seemingly cannot be piped individually to another command, as it comes out as a single line.

**Comment by samschott** [comment]
Indeed, `maestral ls` will print its output in a grid adjusted to the terminal width (or in a single line if there appears to be no limit to the width).

I believe the shell command `ls` has special logic to print output on separate lines if it's not attached to a terminal, allowing commands such as `ls | grep`. This is probably something we can replicate.
