### ISSUE TITLE
Unable to use Maestral Docker image on Raspberry Pi OS 64bit

### ISSUE THREAD

**Issue by mh166** [samschott/maestral#696]
**Describe the bug**
I tried using the Maestral Docker image on my freshly installed Raspberry Pi. While the linking of the Dropbox account did work, starting Maestral after that in order to start syncing, was not successful.

**To Reproduce**
1. Install [Raspberry Pi OS (64-bit)](https://www.raspberrypi.com/software/operating-systems/#raspberry-pi-os-64-bit)
2. Install Docker using `curl -sSL https://get.docker.com | sh`
3. Enter the Docker container: `docker run --rm -it -v /mnt/usb-stick/dropbox-c-nord:/dropbox maestraldbx/maestral:1.6.2 ash`
4. _Within that container_, link the account: `maestral auth link`
5. Try starting sync
  a. Either _still within_ the previously used container: `maestral start -fv`
  b. Or _from outside_: `docker run --rm -it -v /mnt/usb-stick/dropbox-c-nord:/dropbox maestraldbx/maestral:1.6.2 maestral start -fv`
6. Experience the following error:
  ```
root@docker-krs:~# docker run --rm -it -v /mnt/usb-stick/dropbox-c-nord:/dropbox maestraldbx/maestral:1.6.2 maestral start -fv
2022-06-03 22:19:37 daemon INFO: Starting daemon
2022-06-03 22:19:37 daemon ERROR: 1
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/maestral/daemon.py", line 478, in start_maestral_daemon
    with Daemon(unixsocket=sockpath) as daemon:
  File "/usr/local/lib/python3.10/site-packages/Pyro5/server.py", line 233, in __init__
    self.transportServer.init(self, host, port, unixsocket)
  File "/usr/local/lib/python3.10/site-packages/Pyro5/svr_threads.py", line 124, in init
    self.sock = socketutil.create_socket(bind=bind_location,
  File "/usr/local/lib/python3.10/site-packages/Pyro5/socketutil.py", line 278, in create_socket
    sock.bind(bind)
PermissionError: [Errno 1] Operation not permitted
root@docker-krs:~#
  ``` 

**Expected behavior**
It should be possible to run Maestral with the provided Docker image, even on a Raspberry Pi.

**System:**

 - Maestral version: 1.6.2
 - Python version: 3.10.1
 - OS: Docker version 20.10.16, build aa7e414 on Raspberry Pi OS (64-bit)
 - Desktop environment: N/A
 - PyQt version (for Linux GUI): N/A

**Additional context**
I also tried the same thing on a freshly installed Debian 11 machine and followed the above steps to reproduce. There it did work. Unfortunately, while the Docker version is the same, the system's parameters differ quite a bit: Debian 11 instead of Raspberry Pi OS and using an `x86_64` platform instead of `aarch64`.

So I suppose something might be odd with the Raspberry Pi's configuration. But unfortunately, I don't have any ideas how to mitigate that. I even tried spinning up the Docker image using Portainer and enabling privileged mode as well as almost any capabilities available. But still, the error message remained the same.

Your help in finding the root cause for this is very much appreciated. Should you require any other logs or debug steps, just let me know.

**Comment by samschott** [comment]
@mh166, I don't have any experience with aarch64 cannot really help out here.

However, the first thing to check would be permissions inside the Docker image where the socket is supposed to be created. You can find out the path by spinning up a Python interpreter inside Docker and running:
```Python
from maestral.daemon import sockpath_for_config

print(sockpath_for_config("maestral"))
```
On Linux, this should typically return `~/.cache/maestral/maestral.sock`, depending on the value of `$XDG_RUNTIME_DIR`. You can then either ensure that you proper permissions for the returned path, or set `$XDG_RUNTIME_DIR` to another path which you (the user inside the Docker container) own.

Let me know if you are able to resolve this and I can tweak the Docker container to set up the proper environment variables in the first place.

**Comment by mh166** [comment]
Thanks for the quick response, it helped me find the root cause. I checked permissions, as per your suggestion and everything seemed fine. Btw, `$XDG_RUNTIME_DIR` is not set within the container, so apparently it uses the current working directory, which in the case of this container is `/dropbox`:

```
~ $ python
Python 3.10.1 (main, Dec  8 2021, 03:36:29) [GCC 10.3.1 20211027] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from maestral.daemon import sockpath_for_config
>>> print(sockpath_for_config("maestral"))
/dropbox/.cache/maestral/maestral.sock
>>>
~ $ ls -la /dropbox/.cache/maestral/
total 384
drwxr-xr-x    2 dropbox  dropbox     131072 Jun  4 14:50 .
drwxr-xr-x    3 dropbox  dropbox     131072 Jun  3 21:18 ..
-rwxr-xr-x    1 dropbox  dropbox          0 Jun  3 21:18 maestral.lock
-rwxr-xr-x    1 dropbox  dropbox       1520 Jun  3 22:19 maestral.log
~ $ id
uid=1000(dropbox) gid=1000(dropbox)
~ $ echo $XDG_RUNTIME_DIR

~ $ env | grep XDG
~ $ pwd
/dropbox
~ $
```

But knowing that it tries to create a socket on that bind-volume, was key in solving this problem. First, I wondered why it wouldn't work despite the permissions seeming fine. But then I remembered: for compatibility reasons, that mount is on an exFAT-formatted thumbdrive. So effectively it tries to create a socket on an exFAT filesystem which - to no ones surprise - is not supported.

After quickly testing with an ext4 FS, everything shows okay. 😊 So if nothing else, I could continue with having just ext4 as the filesystem and everything working fine.

But I'm wondering: is there any reason or benefit to having the socket within that specific directory? Or could the socket be produced somewhere within the bounds of the container (e.g. `/`, `/run`, `/var/run` or whatever might look suitable)? If so, I'd be able to keep the exFAT file system and still make use of Maestral within Docker.

**Comment by samschott** [comment]
Ok, that explains things! 

> But I'm wondering: is there any reason or benefit to having the socket within that specific directory? Or could the socket be produced somewhere within the bounds of the container (e.g. /, /run, /var/run or whatever might look suitable)?

No specific reason. The socket location should be `$XDG_RUNTIME_DIR/maestral` and falls back to `~/.cache/maestral` if `XDG_RUNTIME_DIR` is not set. `/run/user/$UID` would probably be the better fallback location.

In fact, reading through the spec [here](https://specifications.freedesktop.org/basedir-spec/basedir-spec-0.8.html), it sounds like abusing `~/.cache` as a runtime directory for sockets and PID files is a bad idea. However, Maestral does not rely on any cleanup of its runtime files to be performed after a user session ends, so it does not really matter. I'd rather make sure that the directory exists than start guessing about what a good runtime directory should be if its not specified by the system...

**Comment by samschott** [comment]
Im closing this since it's not really an issue with the Docker image. However, I will check if it's worth setting XDG_RUNTIME_DIR explicitly in the image.
