### ISSUE TITLE
Default permissions on Dropbox folder less than ideal

### ISSUE THREAD

**Issue by jonathanlang** [samschott/maestral#701]
**Describe the bug**
When setting up Maestral, the app asks for a save-location for the "Dropbox (Maestral)" folder. By default this is in the user's home directory. Regardless of whether the app creates the folder, or the user choses to create it on their own, in both cases the folder ends up with a permission set of "drwxr-xr-x", while all other top-level folders are "drwx------" by default. This means that everyone on the machine has read permissions to the Dropbox folder. 
I discovered this while searching for something in another user account and files from my Dropbox showed up in their Spotlight results. 
By default, I would support Maestral changing permissions to match the other top level folders in the user's home directory. 

**To Reproduce**
Set up Maestral on a new machine. Use the default directory suggestion in the home folder. After the folder has been created, compare folder permissions between Documents and Dropbox folder for example. 

**Expected behaviour**
The Dropbox folder should only be accessible by the current user. 

**System:**

 - Maestral version: 1.6.3
 - Python version: 3.10
 - OS: [e.g. Ubuntu] macOS 12.4 
 - Desktop environment: [e.g. Gnome 3.32]
 - PyQt version (for Linux GUI):

**Additional context**
I guess the current behavior is the default, because creating a folder manually also applies read permissions for everyone by default. But I don't remember the official Dropbox app exposing all my files to other users...

**Comment by samschott** [comment]
I don't like messing with permissions if a user selects an existing folder, this could lead to unintended consequences. Similarly, Maestral does not make any assumptions about where the Dropbox folder is located, it may well be deliberately in a shared location. In this case, we do want to follow the permissions set up already for that location. Therefore, respecting the default permissions for the user and the location makes sense to me.
