### ISSUE TITLE
[Cocoa] Not implemented: ScrollContainer.set_on_scroll()

### ISSUE THREAD

**Issue by houchin** [samschott/maestral#702]
**Describe the bug**
Running "maestral gui" with version 1.6.3 on macOS 12.3.1 results in the error "[Cocoa] Not implemented: ScrollContainer.set_on_scroll()"

**To Reproduce**
Install the command line tool on macOS
Open a shell and run "maestro gui"
The GUI does start, but the above error is printed to stdout and the maestro command does not exit

**Expected behaviour**
The GUI should start without error, and the maestral command should exit without error

**System:**
 - Maestral version: 1.6.3 updated by Maestral itself from 1.6.2
 - Python version: 3.8.6
 - OS: macOS Monterey 12.3.1
 - Desktop environment: macOS

**Additional context**

**Comment by samschott** [comment]
1. The command will keep running until the GUI is closed. It literally runs it from the Terminal. This is the default for the command line. If you want to keep using the terminal afterwards, `maestral gui &` will work (the `&` starts the process in the background).
2. `[Cocoa] Not implemented: ScrollContainer.set_on_scroll()` is a message from the underlying widget toolkit [toga](https://github.com/beeware/toga) saying that callbacks on scroll have not yet been implemented. It's not an error but just an informational message. It will hopefully be implemented soon, at which point you won't see this anymore.

It's not a bug, it's feature :)
