### ISSUE TITLE
Cannot access the Maestral GUI on Macbook Pro M1 Max after installation and setup (app bundle).

### ISSUE THREAD

**Issue by andreimoment** [samschott/maestral#705]
**Describe the bug**

I have installed the app bundle of version 1.6.3, on Macbook Pro M1 Max running MacOS 12.4.
On my first run of the app (via Applications folder icon) I was asked for the dropbox api key which I provided and then presented with folder selection which I confirmed.

After closing the setup window, I am unable to access the GUI.  I double click on the app icon and nothing appears on the screen or in the list of apps accessible via command+tab or in the app bar at the top of the screen. 

If I run `/Applications/Maestral.app/Contents/MacOS/maestral gui` I get this error: 

`[Cocoa] Not implemented: ScrollContainer.set_on_scroll()`

**To Reproduce**
Install app bundle on MacOS 12.4 running on M1 Max.

Start the app and set the dropbox api token, set folders to sync, close the app window.

Try to start the GUI again by clicking on the icon. The current window loses focus, but the Maestral GUI window does not appear.

If I run `/Applications/Maestral.app/Contents/MacOS/maestral gui` I get this error: 

`[Cocoa] Not implemented: ScrollContainer.set_on_scroll()`

and I need to end the process (Ctrl+c) in order to return to the terminal session.

**Expected behaviour**

I expected that the GUI open would open.

**System:**

 - Maestral version: 1.6.3
 - Python version: Python 3.9.12 (main, Mar 26 2022, 15:44:31) / [Clang 13.1.6 (clang-1316.0.21.2)] on darwin
 - OS: MacOS 12.4
 - Desktop environment: [e.g. Gnome 3.32] n/a
 - PyQt version (for Linux GUI): n/a

**Additional context**

In the Activity Monitor, I see two maestral processes, one with an icon.

After the setup, neither maestral nor maestral-cli were available in my path.

**Comment by samschott** [comment]
@andreimoment, it looks like Maestral is starting fine (and probably syncing your folder). However, it typically only appears as a status bar icon when running does not show a settings window unless you open it from the status bar menu.

If you can't see the icon, could it possibly be hidden by the notch?

**Comment by andreimoment** [comment]
@samschott, thank you for your quick response.

You are right, the issue was with the icon being behind the notch, despite there being vacant space enough for 2-3 icons in the top bar.

I installed bartender and now I have access to the GUI.
