### ISSUE TITLE
How to change top bar icon (Pop!-OS 19.10)

### ISSUE THREAD

**Issue by Shogu** [SamSchott/maestral#71]
**Describe the bug**
Not a bug cause everything runs so fine! I'd just like to change the default icon in the Ubuntu/POP!_OS 19.10 topbar, which is too big. 

Otherwise running Maestral without GUI could be a decent solution, does the following command good enough: maestral start --config-name='maestral'
?

Thanks a lot for this great tool (62 MB of memory without GUI Oo!), i am happy to get rid off official Dropbox software!

Ogu  -FRANCE

**Comment by SamSchott** [comment]
Hi Ogu, I'm glad you like Maestral.

> I'd just like to change the default icon in the Ubuntu/POP!_OS 19.10 topbar, which is too big.

On Gnome 3, system tray icons will be installed to "/usr/local/share/icons/hicolor/scalable/status/" or "~/.local/share/icons/hicolor/scalable/status/" for system wide or user installations, respectively. You can simply replace the SVG icons with alternatives of your choice.

What does "too big" mean? Could you post a screenshot, just to see if it is the intended size or indeed a bug?

> does the following command good enough: maestral start --config-name='maestral'

Yes, this will work. In fact, `maestral start` will be enough, as long as you only have a single configuration. If you haven't run the GUI yet, it will also walk you through linking your account in the command line.

You can always attach a GUI to the existing daemon by running `maestral gui`. If you then close the GUI, the daemon will keep running.

**Comment by Shogu** [comment]
Hi Sam and many thanks for your answer.

Here si the screenshot :+1: 
[url=https://ibb.co/D5znJMx][img]https://i.ibb.co/QrpGgH2/Capture-d-cran-du-2019-11-24-17-14-47.png[/img][/url]
[url=https://fr.imgbb.com/]photo sharing[/url]
It is not "so big" indeed !

I did'nt manage to replace status icon but no-gui running and maestrom-gui command if necessary is really good  for my usage!

**Comment by SamSchott** [comment]
The icon does stand out a little, especially in combination with your icon theme. But it is working as it should...

Regarding replacing the icons: My previous advice should work but is actually the wrong approach. Icons stored in the "hicolor" will be overwritten when you update Maestral. Instead, it is better to create icon files with the same names ("maestral-icon-idle-symbolic", ...) in the folder which your current icon theme is using (e.g., "ubuntu-mono-dark/scalable/status"). They will take priority over the "hicolor" theme.

Also, changes to icons will only become effective after a restart. Gnome typically caches the icons for a desktop session.
