### ISSUE TITLE
Enable Maestral as a TrueNAS iocage plugin

### ISSUE THREAD

**Issue by leocb** [samschott/maestral#717]
TrueNAS Core is an excellent solution for Home NAS. But it lacks realtime, two-way synchronization with cloud providers, such as Dropbox.
While searching for a solution on this, and failing using out-of-the-box supported features or dropbox own official client. I ended up installing Maestral on a Linux VM inside TrueNAS, giving it a virtual network access to my NAS Files, this way i have real-time two way sync with my dropbox.

However, this solution comes at the added overhead of running a vm and having to share files through a virtual network. it would be less resource intensive to run maestral directly as a iocage plugin on TrueNAS.

This forum topic has a lot of resources on how to create a plugin for TrueNAS: https://www.truenas.com/community/resources/create-an-unofficial-iocage-plugin.99/

I'd feel more secure if the owner of this repo could do it, as it's obvious they have more experience than I do when it comes to linux-related stuff and it would mean it's officially supported. But I could attempt to do it myself in the future.

**Comment by leocb** [comment]
I took a stab at this, apparently this project isn't compatible with FreeBSD, which means it can't run natively on TrueNAS Core as an iocage plugin. I decided to upgrade my setup to TrueNAS Scale, which is linux/debian based and run maestral as a docker container, works like a charm!

ty for this awesome project.

**Comment by samschott** [comment]
Yeah, I'm not aware of a good way to subscribe to local file system changes in FreeBSD. The kqueue system is limited and only allows monitoring existing files - it does not notify users of new files.

Glad you found another solution!
