### ISSUE TITLE
Maestral.app opens with "Welcome" window despite having been configured

### ISSUE THREAD

**Issue by stysedo** [samschott/maestral#732]
So, today when the Maestral.app launched at login it presented us with the "Welcome to Maestral ... Link Dropbox Account" window.  This feels odd since we did configure Maestral several months ago in the macOS gui and have been using it without much difficulty ever since...

This is on macOS 10.13.6 with Maestral.app 1.5.2

Should I just go ahead and follow the prompts to link the dropbox account again?
Maybe my maestral.plist or Application Support files just became corrupted?

**Comment by samschott** [comment]
Apologies for not getting back to this earlier. It does appear like the config file getting lost or moved somehow. Relinking should do the job, and hopefully it should not occur again.

Actual corruption of the config file, or Dropbox access being revoked, should result in an explicit error message instead.
