### ISSUE TITLE
.ignore file for ignoring local files during sync

### ISSUE THREAD

**Issue by AbstractGeek** [samschott/maestral#738]
**Is your feature request related to a problem? Please describe.**
I use symlinks inside my dropbox folder for convenience, even though it is not synced. Often, this helps me keep preferences (dotfiles) for apps in a separate folder. Maestral throws an error when a symlink is found.

**Describe the solution you'd like**
Look through an .ignore list and do not syn through files (i.e ignore files and do not through out errors for them)

**Describe alternatives you've considered**
I am not sure if there are any alternatives - I would love to try them out if there are.

**Comment by samschott** [comment]
That feature already exists :) See https://maestral.app/docs/mignore.

**Comment by AbstractGeek** [comment]
Nice! I tried it out and works well. Thanks for the awesome alternative to dropbox 🤓

**Comment by theboyler** [comment]
Hi Sam - I'm having trouble getting this to work.

My Dropbox folder is:

`/Users/jobloggs/Bloggs Dropbox`

I've placed a file called .mignore here:

`/Users/jobloggs/Bloggs Dropbox/.mignore`

I want to stop this file being synced:

`/Users/jobloggs/Bloggs Dropbox/Jo Bloggs/Downloads/Torrents`

I've tried putting these in .mignore

```
/Users/jobloggs/Bloggs\ Dropbox/Jo\ Bloggs/Downloads/Torrents 
**Torrents

```
But everytime I create a fodler called Torrents in Downloads, it gets synced :-(

**Comment by samschott** [comment]
@theboyler, as discussed in #818, the second line will work if you remove the backward slashes. So therefore:
```
Jo Bloggs/Downloads/Torrents
```
will exclude any files or folders matching "Jo Bloggs/Downloads/Torrents" inside your Dropbox. If you want to explicitly exclude folders only, append a training "/".

I've added a couple of examples to the documentation at https://maestral.app/docs/mignore, hopefully they will be helpful.
