### ISSUE TITLE
What's the difference in the two release bundles?

### ISSUE THREAD

**Issue by chrismanderson** [samschott/maestral#739]
Apologies for the basic question - but what's the difference in the two release bundle files?

I see [Maestral-1.6.3-macOS_10_12_build.dmg](https://github.com/samschott/maestral/releases/download/v1.6.3/Maestral-1.6.3-macOS_10_12_build.dmg) and [Maestral-1.6.3.dmg](https://github.com/samschott/maestral/releases/download/v1.6.3/Maestral-1.6.3.dmg).

It looks like the Homebrew cask installs `Maestral-1.6.3.dmg` - so I'm assuming that's the one for general use? What is the `macOS_10_12_build.dmg` intended for then?

Again, dumb question, but want to make sure I'm installing the right client for Monterey.

**Comment by samschott** [comment]
Yes, Maestral-1.6.3.dmg is for general use but requires macOS 10.13 or later. I did not properly communicate this new minimum requirement in advance so decided to build a special release for macOS 10.12 (Sierra). There is no difference in functionality, only in binary compatibility.
