### ISSUE TITLE
maestral sharelink list cuts links

### ISSUE THREAD

**Issue by jarkkojs** [samschott/maestral#742]
Longer sharelinks cannot be supplied to `maestral sharelink revoke` because they are cut by the formatter, which makes impossible to revoke them.

**Comment by samschott** [comment]
Do you mean that the argument passed to `sharelink revoke` is truncated? Or that you can't get the url in the first place from `sharelink list`?

**Comment by jarkkojs** [comment]
If the URL is long enough it is truncated in the list, which means that you cannot pass it to sharelink revoke.

**Comment by samschott** [comment]
Ah, yes. That is indeed a known issue, which will be resolved in the next release. Sorry about that!

**Comment by jarkkojs** [comment]
NP :-)
