### ISSUE TITLE
maestral overwrote local changes when connecting to Dropbox

### ISSUE THREAD

**Issue by mariusa** [samschott/maestral#746]
**Describe the bug**

maestral overwrote local changes when connecting to Dropbox

**To Reproduce**

1. Use official Dropbox client
2. Remove it
3. make changes to an existing file, say test.txt
4. Install maestral[gui]
5. Connect to Dropbox
6. changes to test.txt are lost (!)

**Expected behaviour**

 test.txt should preserve changes and be uplaoded to dropbox

**System:**

 - Maestral version: maestral-1.6.3 maestral-qt-1.6.3 
 - Python version: 3
 - OS: Fedora 37 new install
 - Desktop environment:  Gnome 43
 - PyQt version (for Linux GUI): ?

**Additional context**

**Comment by n13** [comment]
Did you point maestral to the existing Dropbox folder? That may not work. 

I think it needs to have its own sync folder since it stores metadata for syncing.

**Comment by mariusa** [comment]
> Did you point maestral to the existing Dropbox folder?

Yes. 
I understand the tech reason now, but as a new user, I wouldn't know this.

In this case, the fix should be: if the folder is not empty, show a warning saying what you mentioned, with 2 options: Use selected / Choose another

THanks

**Comment by mariusa** [comment]
Or even better: if the selected folder is not empty, and does NOT have maestral metadata, don't allow to continue.

**Comment by samschott** [comment]
> In this case, the fix should be: if the folder is not empty, show a warning saying what you mentioned, with 2 options: Use selected / Choose another

I believe there is a warning shown when initially selecting the folder if it is not empty, with an option to "merge". If file contents differ locally and on the server, Maestral will create a conflicting copy of the file.

@mariusa, did neither of this happen in your case?

**Comment by samschott** [comment]
Ahh, I just realised that this issue is from 2022, and the behaviour described by me was added more recently. Marking this as closed.
