### ISSUE TITLE
Crash on launch of gui

### ISSUE THREAD

**Issue by dpawson** [samschott/maestral#758]
**Describe the bug**

Installed maestral, OK
installed gui ?
>pip install maestral[gui]

**To Reproduce**

ran
>maestral gui

**Expected behaviour**

Expected gui to open

Instead
> maestral gui & 
[1] 5525
~ 10:45 >  QImage::pixel: coordinate (0,0) out of range
QImage::pixel: coordinate (0,0) out of range
QImage::pixel: coordinate (0,0) out of range
.....
>  libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
Opening in existing browser session.

**System:**

5.15.6

 - Maestral version:

1.6.3

 - Python version: 
Python 3.11.0

 - OS: [e.g. Ubuntu]

Fedora 37

 - Desktop environment: [e.g. Gnome 3.32]
GNOME 43.1

 - PyQt version (for Linux GUI):

??? How to find it please

**Additional context**

First use of maestral after failure of Dropbox on Fedora 37.

Link to dropbox seemed to work well.

**Comment by samschott** [comment]
I don't currently have access to a Linux machine or to a Gnome 43 desktop environment, so I'm afraid there is not much I can do to debug this.

> Link to dropbox seemed to work well.

Maybe the following questions will provide useful pointers though:

1. I assume you used the CLI to link Maestral if the GUI crashes?
2. Do see ever see a system tray icon before the crash, or does it not even get this far?
