### ISSUE TITLE
maestral is not connecting to Dropbox

### ISSUE THREAD

**Issue by rayzorben** [samschott/maestral#764]
It was working and syncing. I attached to the docker to check status, and it just shows Connecting... I tried to relink and it cannot connect to dropbox.

Dropbox seems to be up and working at least the UI and my local client.

```
~ $ maestral auth link
Maestral is already linked. Use '-r' to relink to the same account or specify a new config name with '-c'.
~ $ maestral status

Account:      @gmail.com (Pro)
Usage:        35.6% of 2.3 TB used
Status:       Connecting...
Sync errors:  0

~ $ maestral auth link -r
- Linking new account for 'maestral' config
- Retrieving auth code from Dropbox
? How would you like to you link your account? Print auth URL to console
- Open the URL below to retrieve an auth code:
- https://www.dropbox.com/oauth2/authorize?response_type=code&client_id=2jmbq42w7vof78h&token_access_type=offline&code_challengehidden&code_challenge_method=S256
? Enter the auth code: JlFxsvQpYyUAchangedqq8c0vnH-qY
! Could not connect to Dropbox, please try again
? Enter the auth code:
```

**Comment by samschott** [comment]
Can you check the logs for a more detailed error message?

**Comment by samschott** [comment]
Since there has been no update to Maestral for some time, I suspect something in your local setup must have changed to cause connection issues. It might a bug with Maestral, i.e., a change in setup that is supposed to be able to handle, or in fact an unrelated issue.

**Comment by rayzorben** [comment]
Closing, it works now. Could have been a temporary dropbox issue.
