### ISSUE TITLE
maestral gui - error - entry_points() got an unexpected keyword argument 'group'

### ISSUE THREAD

**Issue by ryuuzaki42** [samschott/maestral#767]
**First of all, thanks for the great application.
Obs.: maestral and maestral_qt runs OK.
Maybe  the error is only in my system.**
Package created: https://t.me/SlackwarePackages/1117

**Describe the bug**
Error when start maestral gui

**To Reproduce**
#### Create a virtual environment - in this case maestral_venv
    python3 -m venv maestral_venv

#### Load the venv
    source maestral_venv/bin/activate

#### Install the program and dependencies
    python3 -m pip install --upgrade 'maestral[gui]'

Collecting maestral[gui]
  Downloading maestral-1.6.4-py3-none-any.whl (433 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 433.4/433.4 KB 3.1 MB/s eta 0:00:00
Collecting fasteners>=0.15
  Downloading fasteners-0.18-py3-none-any.whl (18 kB)
Collecting dropbox<12.0,>=11.28.0
  Downloading dropbox-11.36.0-py3-none-any.whl (594 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 594.0/594.0 KB 5.0 MB/s eta 0:00:00
Collecting click>=8.0.2
  Downloading click-8.1.3-py3-none-any.whl (96 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.6/96.6 KB 9.3 MB/s eta 0:00:00
Collecting desktop-notifier>=3.3.0
  Downloading desktop_notifier-3.4.2-py3-none-any.whl (31 kB)
Collecting keyrings.alt>=3.1.0
  Downloading keyrings.alt-4.2.0-py3-none-any.whl (20 kB)
Collecting survey<4.0,>=3.4.3
  Downloading survey-3.4.3-py3-none-any.whl (24 kB)
Collecting keyring>=22
  Downloading keyring-23.11.0-py3-none-any.whl (36 kB)
Collecting Pyro5>=5.10
  Downloading Pyro5-5.14-py3-none-any.whl (79 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.1/79.1 KB 8.4 MB/s eta 0:00:00
Collecting requests>=2.16.2
  Downloading requests-2.28.1-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 KB 8.0 MB/s eta 0:00:00
Collecting rich
  Downloading rich-12.6.0-py3-none-any.whl (237 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 237.5/237.5 KB 5.7 MB/s eta 0:00:00
Collecting typing-extensions
  Downloading typing_extensions-4.4.0-py3-none-any.whl (26 kB)
Collecting pathspec>=0.5.8
  Downloading pathspec-0.10.2-py3-none-any.whl (28 kB)
Collecting watchdog>=2.0.1
  Downloading watchdog-2.1.9-py3-none-manylinux2014_x86_64.whl (78 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.4/78.4 KB 9.8 MB/s eta 0:00:00
Collecting packaging
  Downloading packaging-21.3-py3-none-any.whl (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.8/40.8 KB 6.8 MB/s eta 0:00:00
Requirement already satisfied: setuptools in ./lib/python3.9/site-packages (from maestral[gui]) (58.1.0)
Collecting maestral-qt>=1.6.3
  Downloading maestral_qt-1.6.4-py3-none-any.whl (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 6.5 MB/s eta 0:00:00
Collecting dbus-next
  Downloading dbus_next-0.2.3-py3-none-any.whl (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.9/57.9 KB 10.0 MB/s eta 0:00:00
Collecting stone>=2.*
  Downloading stone-3.3.1-py3-none-any.whl (162 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 162.3/162.3 KB 9.0 MB/s eta 0:00:00
Collecting six>=1.12.0
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting importlib-metadata>=4.11.4
  Downloading importlib_metadata-5.1.0-py3-none-any.whl (21 kB)
Collecting jaraco.classes
  Downloading jaraco.classes-3.2.3-py3-none-any.whl (6.0 kB)
Collecting jeepney>=0.4.2
  Downloading jeepney-0.8.0-py3-none-any.whl (48 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.4/48.4 KB 5.9 MB/s eta 0:00:00
Collecting SecretStorage>=3.2
  Downloading SecretStorage-3.3.3-py3-none-any.whl (15 kB)
Collecting markdown2
  Downloading markdown2-2.4.6-py2.py3-none-any.whl (37 kB)
Collecting PyQt6
  Downloading PyQt6-6.4.0-cp37-abi3-manylinux_2_28_x86_64.whl (8.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.0/8.0 MB 7.1 MB/s eta 0:00:00
Collecting serpent>=1.41
  Downloading serpent-1.41-py3-none-any.whl (9.6 kB)
Collecting idna<4,>=2.5
  Downloading idna-3.4-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.5/61.5 KB 12.0 MB/s eta 0:00:00
Collecting charset-normalizer<3,>=2
  Downloading charset_normalizer-2.1.1-py3-none-any.whl (39 kB)
Collecting certifi>=2017.4.17
  Downloading certifi-2022.9.24-py3-none-any.whl (161 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 161.1/161.1 KB 8.3 MB/s eta 0:00:00
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.13-py2.py3-none-any.whl (140 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.6/140.6 KB 4.5 MB/s eta 0:00:00
Collecting wrapio>=1.0.0
  Downloading wrapio-2.0.0-py3-none-any.whl (5.8 kB)
Collecting pyparsing!=3.0.5,>=2.0.2
  Downloading pyparsing-3.0.9-py3-none-any.whl (98 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.3/98.3 KB 10.6 MB/s eta 0:00:00
Collecting pygments<3.0.0,>=2.6.0
  Downloading Pygments-2.13.0-py3-none-any.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 7.5 MB/s eta 0:00:00
Collecting commonmark<0.10.0,>=0.9.0
  Downloading commonmark-0.9.1-py2.py3-none-any.whl (51 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.1/51.1 KB 11.7 MB/s eta 0:00:00
Collecting zipp>=0.5
  Downloading zipp-3.11.0-py3-none-any.whl (6.6 kB)
Collecting cryptography>=2.0
  Downloading cryptography-38.0.4-cp36-abi3-manylinux_2_28_x86_64.whl (4.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 8.7 MB/s eta 0:00:00
Collecting ply>=3.4
  Downloading ply-3.11-py2.py3-none-any.whl (49 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.6/49.6 KB 13.6 MB/s eta 0:00:00
Collecting more-itertools
  Downloading more_itertools-9.0.0-py3-none-any.whl (52 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.8/52.8 KB 13.0 MB/s eta 0:00:00
Collecting PyQt6-Qt6>=6.4.0
  Downloading PyQt6_Qt6-6.4.1-py3-none-manylinux_2_28_x86_64.whl (56.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.6/56.6 MB 7.2 MB/s eta 0:00:00
Collecting PyQt6-sip<14,>=13.4
  Downloading PyQt6_sip-13.4.0-cp39-cp39-manylinux1_x86_64.whl (307 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 307.7/307.7 KB 9.9 MB/s eta 0:00:00
Collecting cffi>=1.12
  Downloading cffi-1.15.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (441 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 441.2/441.2 KB 10.4 MB/s eta 0:00:00
Collecting pycparser
  Downloading pycparser-2.21-py2.py3-none-any.whl (118 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.7/118.7 KB 14.7 MB/s eta 0:00:00
Installing collected packages: PyQt6-Qt6, ply, commonmark, zipp, wrapio, watchdog, urllib3, typing-extensions, six, serpent, PyQt6-sip, pyparsing, pygments, pycparser, pathspec, more-itertools, markdown2, jeepney, idna, fasteners, dbus-next, click, charset-normalizer, certifi, survey, stone, rich, requests, Pyro5, PyQt6, packaging, jaraco.classes, importlib-metadata, cffi, keyrings.alt, dropbox, desktop-notifier, cryptography, SecretStorage, keyring, maestral, maestral-qt
Successfully installed PyQt6-6.4.0 PyQt6-Qt6-6.4.1 PyQt6-sip-13.4.0 Pyro5-5.14 SecretStorage-3.3.3 certifi-2022.9.24 cffi-1.15.1 charset-normalizer-2.1.1 click-8.1.3 commonmark-0.9.1 cryptography-38.0.4 dbus-next-0.2.3 desktop-notifier-3.4.2 dropbox-11.36.0 fasteners-0.18 idna-3.4 importlib-metadata-5.1.0 jaraco.classes-3.2.3 jeepney-0.8.0 keyring-23.11.0 keyrings.alt-4.2.0 maestral-1.6.4 maestral-qt-1.6.4 markdown2-2.4.6 more-itertools-9.0.0 packaging-21.3 pathspec-0.10.2 ply-3.11 pycparser-2.21 pygments-2.13.0 pyparsing-3.0.9 requests-2.28.1 rich-12.6.0 serpent-1.41 six-1.16.0 stone-3.3.1 survey-3.4.3 typing-extensions-4.4.0 urllib3-1.26.13 watchdog-2.1.9 wrapio-2.0.0 zipp-3.11.0
WARNING: You are using pip version 22.0.4; however, version 22.3.1 is available.
You should consider upgrading via the '/media/sda2/home/j/maestral_venv/bin/python3 -m pip install --upgrade pip' command.
>
#### Run maestral gui
    maestral gui
Traceback (most recent call last):
  File "/media/sda2/home/j/maestral_venv/bin/maestral", line 8, in <module>
    sys.exit(main())
  File "/media/sda2/home/j/maestral_venv/lib64/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/media/sda2/home/j/maestral_venv/lib64/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/media/sda2/home/j/maestral_venv/lib64/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/media/sda2/home/j/maestral_venv/lib64/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/media/sda2/home/j/maestral_venv/lib64/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/media/sda2/home/j/maestral_venv/lib64/python3.9/site-packages/maestral/cli/cli_core.py", line 275, in gui
    gui_entry_points = entry_points(group="maestral_gui")
TypeError: entry_points() got an unexpected keyword argument 'group'

**Expected behaviour**

Expected gui to open

**System:**

 - Maestral version: 1.6.4
 - Python version: 3.9.15
 - OS: Slackware 15.0 64 bits
 - Desktop environment: KDE Plasma 5.23.5
 - PyQt version (for Linux GUI): 6.4.0
 
    $ bin/python3 -c "from PyQt6.QtCore import QT_VERSION_STR; print(QT_VERSION_STR)"
6.4.0

**Additional context**

Looks like some importlib_metadata.entry_points or importlib.metadata.entry_points error, but I couldn't find how to solve.
https://github.com/python/importlib_metadata/issues/331

**Have a nice day!**

**Comment by neugrin** [comment]
Hamelinto samscott: Your app is great for me. Thanks. I use Linuxmint 20.3 Cinnamon.
Meanwhile I installed the new update and got the same error, as noted by ryuuzaki42, when using the gui. I rolled back to 1.6.3 
Greetings from Germany/Hamelin

**Comment by samschott** [comment]
Thanks for the detailed report! It appears that the `groups` parameter to `entry_points()` is only supported from Python 3.10 and upwards. I'll need to fix that.

**Comment by neugrin** [comment]
@samschott: Thank you for the new update 1.6.5.  Everything runs fine for me.
