### ISSUE TITLE
Cannot load keyring keyring.backends.SecretService.Keyring

### ISSUE THREAD

**Issue by schoettl** [samschott/maestral#789]
**Describe the bug**
I did install and `maestral auth link` successfully on NixOS 22.11.
When I call `maestral start` I get this error message:

```
Cannot load keyring keyring.backends.SecretService.Keyring. Please relink Maestral to get a new access token.
```

Maestral does not start nor sync files.

**To Reproduce**
```
nix-env -iA nixos.maestral
maestral auth link
maestral start
```

**Expected behaviour**
No error.

**System:**

 - Maestral version: 1.5.1
 - OS: NixOS 22.11 (x86_64-linux)
 - Python version: 3.9.6
 - Desktop environment: --
 - PyQt version (for Linux GUI): --

**Additional context**

It's strange, on a different laptop also with NixOS 22.11 it works.

Can anyone reproduce or provide an idea to get it running? @peterhoeg

**Comment by peterhoeg** [comment]
See https://github.com/samschott/maestral/issues/734. I'm guessing that some impurity on your system picks up whatever package is needed for secretservice support.

Please don't use `nix-env` - manage the system through =configuration.nix= to ensure reproducibility.

**Comment by schoettl** [comment]
Does that mean that this issue also has to be fixed downstream in the NixOS repo?

Actually, I also put maestral in configuration.nix. When I start a new shell, the correct version should be picked. But still the same issue. `nixos-rebuild switch --upgrade` didn't help.

**Comment by peterhoeg** [comment]
There are 2 things at play here:

1. maestral doesn’t specify all the dependencies in requirements.txt since some are optional.
2. maestral is able on one of your machines to unlock the wallet, but not the other.

The first one is by choice/design and why we add in dbus-python downstream.

The second one can be due to multiple factors. I’m guessing it’s one of the following:

a. Either there is an impurity somewhere in maestral that makes it pick up python dependencies from some other, global location where you happen to have installed it manually through pip or similar, *or*
b. The working device is *not* using the kwallet SecretService interface but instead the “normal” kwallet dbus interface which we do support on NixOS (see <https://github.com/NixOS/nixpkgs/pull/194165>)

**Comment by schoettl** [comment]
Thank you. I just checked the maestral.ini on the machine where it works. It uses `keyrings.alt.file.PlaintextKeyring`. While SecretService on the other machine does not work.

I tried to reproduce. Now, both machines use SecretService and fail to start. I tested auth link and start in an SSH session as well as in the Gnome desktop.

Both machines now give the same error.

I found the [documentation on keyrings](https://maestral.app/docs/keyring) but it looks like it's always automatically chosen. @samschott can I force a certain key storage method?

**Comment by schoettl** [comment]
Maybe the [SecretStorage](https://pypi.org/project/SecretStorage/) is also an optional dependency (it's not in requirements.txt). Maybe that should also be added downstream in nix? I never did something like that before.

**Comment by peterhoeg** [comment]
> can I force a certain key storage method?

Sure, <https://github.com/samschott/maestral/issues/734>

**Comment by schoettl** [comment]
> can I force a certain key storage method?
> Sure, <#734>

OK, thanks. I thought the ini file is ignored because it's also deleted on unlink and created on link but I haven't tested it. Maestral also falls back to plain text storage if auth link is called in an SSH session but only if the user was not already logged in in the Gnome desktop.

**Comment by peterhoeg** [comment]
Since you're on nixos - I handle the maestral config file with home manager
so it definitely uses it.

**Comment by schoettl** [comment]
Closing because the reason probably was that I [confused my NixOS version](https://discourse.nixos.org/t/thunderbird-102-on-nixos-22-11/24465). I thought I was on 22.11 but it was 21.11.

Thanks everybody for trying to help!
