### ISSUE TITLE
500 errors uploading changed files with ')' in filename

### ISSUE THREAD

**Issue by ideabucket** [samschott/maestral#823]
**Describe the bug**
When Maestral tries to sync changes to a file containing the character `)`, the Dropbox API endpoint throws back a 500 error. 

**To Reproduce**
1. Create a folder on Dropbox containing two files:
   - `01)file_with_right_paren.txt`
   - `file_without_right_paren.txt`
2. Sync it down using Maestral (this works)
3. Run `touch file_without_right_paren.txt`; this should work.
4. Run `touch 01)file_with_right_paren.txt`; this will generate a sync error.

**Expected behaviour**
Files with `)` characters in them should sync normally, since they're not on the [list of prohibited characters][1].

[1]: https://maestral.app/docs/sync-issues

**System:**
 - Maestral version: 1.6.4
 - Python version: 3.10.8
 - OS: macOS Ventura 13.1

**Additional context**
The file can be renamed, including to a different filename containing a `)` character (e.g. `01)file` → `02)file`), without triggering a sync error. Looking at [the logs](https://github.com/samschott/maestral/files/10606695/maestral_excerpt.log), it appears this issue only manifests when Maestral tries to use the `files/upload` endpoint; renames seem to use `files/move_v2`.

I cannot reproduce this issue with the official client, so I'm not sure if this is an issue with the Dropbox API endpoint or Maestral.

**Comment by samschott** [comment]
Thanks for the report! Looks like an issue with the API endpoint, though interestingly I cannot reproduce this myself.

Thanks for providing the logs output, I'll file a bug with Dropbox including the request id.

**Comment by ideabucket** [comment]
I came back to this to investigate it further and couldn't reproduce it with my own reproduction instructions—but could reproduce it on the original file I was having problems with. After completely recreating that file from scratch, I can no longer reproduce it with it either. So I think that specific file must have had something weird in it that Dropbox didn't like and the issue was never with the filename at all.
