### ISSUE TITLE
Cannot get authorization link from KDE

### ISSUE THREAD

**Issue by LorenzoBettini** [samschott/maestral#838]
When I run Maestral GUI from KDE, when I click on the link "here" to get the authorization token, I get the KDE dialog asking me to choose the application to open the URL (this should not be needed since KDE already knows how to open a URL). Nothing happens, no matter what I select on that dialog, and the dialog keeps asking me the application to open the URL. I can only get the authorization link from the command line with `maestral auth link` and select the option "Print auth URL to console".

Is anyone else experiencing this?

Thanks in advance.
Great program, by the way :)

**Comment by samschott** [comment]
That is indeed strange. Maestral pretty much just run `xdg-open $URL` in a subprocess. Can you check if this works when you run it manually from a terminal, for any URL?

If `xdg-open` is not available, it will use Python's [webbrowser](https://docs.python.org/3.11/library/webbrowser.html) module which also aims to use the default web browser for the platform.

**Comment by samschott** [comment]
Closing due to missing follow up.
