### ISSUE TITLE
Since 1.7.1: `NotImplementedError: chmod: follow_symlinks unavailable on this platform` on Ubuntu 20.04

### ISSUE THREAD

**Issue by jeanmonet** [samschott/maestral#845]
**Describe the bug**

Hi - it appears that Maestral stops syncing since update to 1.7.1 (enters "pause" mode). The log show the following error:

```
2023-02-28 20:46:00 manager ERROR: Unexpected error
Traceback (most recent call last):
  File "/opt/miniconda_py39/envs/py39/lib/python3.9/site-packages/maestral/manager.py", line 802, in _handle_sync_thread_errors
    yield
  File "/opt/miniconda_py39/envs/py39/lib/python3.9/site-packages/maestral/manager.py", line 660, in download_worker
    self.sync.download_sync_cycle()
  File "/opt/miniconda_py39/envs/py39/lib/python3.9/site-packages/maestral/sync.py", line 2876, in download_sync_cycle
    downloaded = self.apply_remote_changes(changes)
  File "/opt/miniconda_py39/envs/py39/lib/python3.9/site-packages/maestral/sync.py", line 3025, in apply_remote_changes
    results.extend(res)
  File "/opt/miniconda_py39/envs/py39/lib/python3.9/site-packages/maestral/sync.py", line 3751, in do_parallel
    yield f.result()
  File "/opt/miniconda_py39/envs/py39/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/opt/miniconda_py39/envs/py39/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/opt/miniconda_py39/envs/py39/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/miniconda_py39/envs/py39/lib/python3.9/site-packages/maestral/sync.py", line 3352, in _create_local_entry
    res = self._on_remote_file(event)
  File "/opt/miniconda_py39/envs/py39/lib/python3.9/site-packages/maestral/sync.py", line 3501, in _on_remote_file
    move(
  File "/opt/miniconda_py39/envs/py39/lib/python3.9/site-packages/maestral/utils/path.py", line 378, in move
    os.chmod(dest_path, orig_mode, follow_symlinks=False)
NotImplementedError: chmod: follow_symlinks unavailable on this platform
2023-02-28 20:46:00 manager INFO: Shutting down threads...
2023-02-28 20:46:01 sync INFO: Sync aborted
2023-02-28 20:46:01 manager INFO: Paused

```
**System:**

 - Maestral version: 1.7.1

```
maestral                  1.7.1                    pypi_0    pypi
maestral-qt               1.7.1                    pypi_0    pypi
```

 - Python version:  3.9
 - OS: Ubuntu 20.04
 - PyQt version (for Linux GUI):

```
pyqt                      5.12.3           py39hf3d152e_8    conda-forge
pyqt-impl                 5.12.3           py39hde8b62d_8    conda-forge
pyqt5-sip                 4.19.18          py39he80948d_8    conda-forge
pyqt6                     6.4.2                    pypi_0    pypi
pyqt6-qt6                 6.4.2                    pypi_0    pypi
pyqt6-sip                 13.4.1                   pypi_0    pypi
pyqtchart                 5.12             py39h0fcd23e_8    conda-forge
pyqtwebengine             5.12.1           py39h0fcd23e_8    conda-forge

```

**Comment by samschott** [comment]
Thanks for the report! This is very surprising, tests are regularly run on Ubuntu in CI and the `follow_symlinks` option should be supported on almost all Linux distros with a somewhat modern glibc.

How did you install Python? From the official installer from https://python.org, from the distros repo, anaconda Python, or something else entirely?

**Comment by jeanmonet** [comment]
Hi, thanks for the quick reply. Python is also installed via conda (in a
conda env). I was wondering if that error could be related to a file
permission?

Is it otherwise possible to disable follow symlink?

Le mar. 28 févr. 2023 à 23:20, samschott ***@***.***> a
écrit :

**Comment by samschott** [comment]
This is not a file permission issue but likely indicates that Anaconda Python was compiled for a relatively old version glibc (which extends support to older distros).

Out of interest, does the `os.lchmod` work with this version of Python?

**Comment by jeanmonet** [comment]
For more background information, maestral is being launched on startup (Xfce) as follows:

```
dbus-run-session -- /opt/miniconda_py39/envs/py39/bin/python3.9 -m maestral_qt -c maestral
```

I ran `os.chwon` via the py39 environment and it appears to run correctly:

![image](https://user-images.githubusercontent.com/15112920/222067542-822d1e18-fd45-42d3-b3c0-6301e20dee01.png)

`os.lchwon` also worked. Hmm

**Comment by jeanmonet** [comment]
For more background information, maestral is being launched on startup (Xfce) as follows:

```
dbus-run-session -- /opt/miniconda_py39/envs/py39/bin/python3.9 -m maestral_qt -c maestral
```

I ran `os.chwon` on a more recent environment py10 and it appears to not run either (lchmod doesn't exist):

![image](https://user-images.githubusercontent.com/15112920/222070153-86df9204-0bd2-440c-a86e-fcd179b13d5c.png)

**Comment by samschott** [comment]
Thanks, this is very helpful! Missing support for `chmod` with `follow_symlinks = False` is a shame, and can possibly be handled better by Maestral, for example with a warning, instead of refusing to work.

Support for `stat` with `follow_symlinks = False` on the other hand will be required for sync to function correctly, but should also be more generally available.

**Comment by jeanmonet** [comment]
Many thanks for the fix! Will revert if any issue remains once update becomes available.

**Comment by ddebin** [comment]
@samschott 

FYI, I have the same problem on the latest Debian 11, default Python 3.9 install, crashing and then pausing.

```
NotImplementedError: chmod: follow_symlinks unavailable on this platform
```

```
Python 3.9.2 (default, Feb 28 2021, 17:03:44)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.supports_follow_symlinks
{<built-in function chown>, <built-in function link>, <built-in function time>,
<built-in function stat>, <built-in function access>}
```

**Comment by dmusican** [comment]
I'm also having this same problem. Is there a recommended workaround until the next version is released? Maestral keeps crashing for me.

**Comment by ddebin** [comment]
> I'm also having this same problem. Is there a recommended workaround until the next version is released? Maestral keeps crashing for me.

@dmusican `pip install --upgrade git+https://github.com/samschott/maestral.git`
