### ISSUE TITLE
More Conflicting Copy Info

### ISSUE THREAD

**Issue by DaAwesomeP** [samschott/maestral#861]
**Is your feature request related to a problem? Please describe.**
It is not clear by the filename `myfile (conflicting copy).pdf` when the conflict was created.

It is also not always clear when there is a conflict unless you are looking at that folder.

**Describe the solution you'd like**
The official syncer will rename files with something like `myfile (My Name's conflicted copy 2022-08-30).pdf`. This is a nice way to deal with many conflicts stacking up (and not losing any changes). I think including the hour:minutes:seconds would also be good.

Additionally, there should be a notification that tells you there is a new conflict and allows you to jump to that folder. The current notification is simply "myfile.pdf was synced."

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by samschott** [comment]
Thanks for the suggestion, I like the idea.
