### ISSUE TITLE
Duplicate menubar icons

### ISSUE THREAD

**Issue by jdsimcoe** [samschott/maestral#876]
**Describe the bug**
I have an entry in Login Items to run Maestral on system startup. It works but I have two Maestral menubar icons at all times:
<img width="342" alt="image" src="https://user-images.githubusercontent.com/275617/231855976-38ece6af-c1f1-4e45-a6fe-921707f3f78e.png">

**To Reproduce**
- Restart computer
- Observe two Maestral icons in menubar
- 
**Expected behaviour**
Only one Maestral menubar icon should show in the top menu.

**System:**
 - Maestral version: 1.7.1
 - Python version: 3.11.3
 - OS: macOS Ventura 13.4

**Comment by samschott** [comment]
@jdsimcoe, this might be a side-effect of recently renaming the bundle identifier. Can you check in `~/Library/Launch Agents` if you have multiple entries starting with `com.samchott.maestral`? In particular, any entries starting with `com.samchott.maestral-cocoa` are from a previous version and can be removed.

**Comment by jdsimcoe** [comment]
I can only find a single entry in LaunchAgents: `com.samschott.maestral.maestral.plist`

**Comment by jdsimcoe** [comment]
@samschott But I also had it added here:

<img width="475" alt="image" src="https://user-images.githubusercontent.com/275617/231903711-010263d9-608f-4d9a-b3a9-54c028ff4f54.png">

I removed it from the `Login Items` in `Settings.app` to see if that solves it.

**Comment by ronabop** [comment]
Seeing the same thing after a recent upgrade (of a machine that had been off for a few weeks, if that is relevant), with only one com.samschott.maestral.maestral.plist

![Screenshot 2023-05-07 at 11 51 46 AM](https://user-images.githubusercontent.com/76779/236697039-a18d2096-0199-42a3-a89e-7263a5a799d0.png)

**Comment by smellymoo** [comment]
this is related, you can open maestral multiple times, and it adds new menubar icons, which shouldn't be possible.

**Comment by samschott** [comment]
> this is related, you can open maestral multiple times, and it adds new menubar icons, which shouldn't be possible.

It's possible, but all GUI instances will talk to the same sync process.

The original issue seems to have come from a migration of login items in macOS. If you see a Maestral entry in "Settings > General > Login Items > Open at login", please go ahead and delete that.
