### ISSUE TITLE
after upgrading to kubuntu 23.04 maestral stop working

### ISSUE THREAD

**Issue by asenler** [samschott/maestral#886]
$ maestral
Traceback (most recent call last):
File "/home/user/.local/bin/maestral", line 5, in
from maestral.cli import main
ModuleNotFoundError: No module named 'maestral'

Operating System: Kubuntu 23.04
KDE Plasma Version: 5.27.4
KDE Frameworks Version: 5.104.0
Qt Version: 5.15.8
Kernel Version: 6.2.0-20-generic (64-bit)
Graphics Platform: X11
Processors: 4 × Intel® Core™ i5-5250U CPU @ 1.60GHz
Memory: 15.5 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 6000

When I tried to install maestral to newly installed kubuntu :
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.

**Comment by walterheisenberg** [comment]
I got the same error, after upgrading today to 23.04 on Kubuntu.

After some searching, I found that adding _--break-system-packages_ solved the issue.
e.g.:
`python3 -m pip install --upgrade maestral --break-system-packages`

If there is a better solution, please let us know.

Maybe @samschott has one for us

**Comment by samschott** [comment]
Looks like some Linux distros are moving away from allowing regular pip-installs of Python packages outside of a virtual environment. See https://peps.python.org/pep-0668/ for the reasoning behind this. This means that either:

1. Maestral needs to be specifically packaged for each distro and / or package manager.
2. You'll need to install Maestral in a separate virtual environment, as recommended by the error message that you are seeing. I'm not sure if regular auto-start functionality (using systemd) will continue working with this.
3. You'll need to enforce the previous behaviour by specifying the `--break-system-packages` flag.

**Comment by asenler** [comment]
Thank you for the tip. However I chose the venv method suggested in  "/usr/share/doc/python3.11/README.venv" . It works as well.  I hope  @samschott modifies the installation section anyway.

**Comment by asenler** [comment]
Thank you for your help. I used the suggested venv method and it worked. Auto-start function through systemd service appears to be working as well.
