### ISSUE TITLE
unexpected error and sync stops

### ISSUE THREAD

**Issue by kurokirasama** [samschott/maestral#890]
**Describe the bug**

Since a while now I'm getting a notification with the message:
```
Unexpected error
Please restart to continue syncing
```
Which I did and it usually goes away, but since today the problem persists.

**To Reproduce**

I'm using maestral gui, so that's why I have a notification

**Expected behaviour**

It hould synchronize without stopping
**System:**

 - Maestral version: 1.7.1
 - Python version: Python 3.8.10
 - OS: [e.g. Ubuntu] Ubuntu 20.04.6 LTS
 - Desktop environment: [e.g. Gnome 3.32] GNOME Shell 3.36.9
 - PyQt version (for Linux GUI): 5.15.7

**Additional context**

log attached.
[log.txt](https://github.com/samschott/maestral/files/11323559/log.txt)

**Comment by samschott** [comment]
Thanks for the report, and sorry for the slow response time! It appears that the issue lies with trying not to follow symlinks. The file system API used for this doesn't seem to be available on your system.

I'll update this for Maestral to fall back to non-symlink aware calls in such cases.
