### ISSUE TITLE
Renaming folder on remote

### ISSUE THREAD

**Issue by raffaem** [samschott/maestral#913]
If you rename a folder on remote, maestral will re-download it.

It does not recognize that it is the same folder, but renamed, and just rename it locally without re-downloading it.

**Comment by raffaem** [comment]
Actually it is not re-downloading, just checking file-by-file whether they are still the same:

```
2023-05-18 18:48:27 sync DEBUG: Local item "ABRIDGED" has no unsynced changes: remote item is newer
```

Is this check really necessary? Why not just rename the local folder?

**Comment by samschott** [comment]
Yeah, that's a limitation of the Dropbox API. It will report moved events as deletions at the old path and creations at the new path. Maestral makes sure that the content hash of the 'created' file indeed matches the local file and will then skip the download. This processes should be sufficiently fast but unfortunately is necessary. Most of the time, the comparison will be directly against Maestral's index, not even requiring any CPU to calculate content hashes.
