### ISSUE TITLE
Expected behavior for `upload=False` accounts?

### ISSUE THREAD

**Issue by sprig** [samschott/maestral#916]
Hi and thanks for your continued work on this!

I have a machine set up to mirror my dropbox, and as such I set it up in `download = true, upload = false` mode. At some point, when adding a new windows machine to dropbox, unexpectedly some files were automatically renamed to uppercase by said machine. I'm not sure how; 
* I might have also been in the process of syncing maestral when this happened.
* maestral now has both the uppercase and the lowercase files registered - `maestral filestatus filename` and `maestral filestatus FILENAME` both report `up to date` for all the files that were renamed.
* Only `FILENAME` is actually in dropbox now, as reported by the webui but also by maestral when doing `maestral ls`.
* Even more strangely, a few of the files have diverged since, and maestral still reports both versions as `up to date`.
* I tried to reindex, this didn't help.

I understand the fact that the account has `upload=False` complicates matters somewhat and must allow for some divergence, since otherwise any local edits should be immediately overwritten. However, I'm not sure exactly what would be the preferred way of getting the local version in line with the remote, and keeping it that way.

**To Reproduce**
Not sure that this is the same as my issue, since in my case files were renamed only on the windows machine, but the result is similar enough; 

1. Create file `/test.org` in dropbox, have it sync to maestral where 'upload=False'.
2. Rename locally `/test.org` => `/TEST.org`. `maestral filestatus TEST.org` => `Up to date`
3. Rename in dropbox `/test.org` => `/test1.org`. `maestral filestatus TEST.org` => `Unwatched`.
4. Rename in dropbox `/test1.org` => `/test.org`. `maestral filestatus TEST.org` => `Up to date". `maestral filestatus test.org` => `Up to date`.
5. `echo "boop" > test.org` in dropbox. `maestral filestatus TEST.org` => `Up to date". `maestral filestatus test.org` => `Up to date`. `cat TEST.org` => "". `cat test.org` => "boop".

After the above test, a simplified test occurred to me; 
* On the machine with maestral, `cp test.org TEST.org`. `maestral filestatus TEST.org` => `Up to date". `maestral filestatus test.org` => `Up to date`.
* On the remote machine `echo "boop beep" > test.org`. `maestral filestatus TEST.org` => `Up to date". `maestral filestatus test.org` => `Up to date`. `maestral filestatus test.org` => `Up to date`. `cat TEST.org` => "". `cat test.org` => "boop beep".

**Expected behaviour**
I would expect maestral to disown one of the files rather than claiming ownership for both, while actually syncing only one.
It would probably be a good idea to have a standard way of finding extraneous files in the repo, since `maestral filestatus` is fairly slow to run on a per-file basis, though I'm not sure how hard that would be to implement.

**System:**
 - Maestral version: 1.7.1
 - Python version: 3.11.3
 - OS: Gentoo Linux
 - Desktop environment: N/A
 - PyQt version (for Linux GUI): N/A

**Comment by samschott** [comment]
> However, I'm not sure exactly what would be the preferred way of getting the local version in line with the remote, and keeping it that way.

The preferred way - in fact the only way - is to enable both upload and download sync. Setting `upload = False` will inevitably lead to divergence if you ever make local changes.

That being said, your report is a bit special because the `filestatus` command is case-insensitive. I.e., it will find matches in Maestral's index even if the matching entry exists only with a different case.

This is definitely an oversight, coming from the fact that Dropbox storage itself is case-insensitive. Renaming to uppercase is purely cosmetic, determining how the file name is displayed, as far as Dropbox (and macOS) is concerned. I'll change this behaviour on case-sensitive file systems, leading to hopefully more consistent results.

**Comment by sprig** [comment]
APFS is case sensitive. Even NTFS on windows can be set to be case sensitive, in recent versions of windows. That aside, case sensitivity can be broken into two different issues; 
1. Whether there can be two filenames of different capitalization but otherwise different names and,
2. Whether the capitalization is remembered in the first place, by the filesystem.

2 is definitely supported by most filesystems as well as by dropbox itself. The issue stops being cosmetic as soon as you have any kind of tool relying on specific paths being present in the dropbox directory, which I believe is a rather common use case.

```
The preferred way - in fact the only way - is to enable both upload and download sync. Setting upload = False will inevitably lead to divergence if you ever make local changes.
```
My specific use case, is keeping a local, live, backup of dropbox, on a system which has enough storage to not be affected by the new push of all cloud vendor for lock-in by keeping most of your files in the cloud. The system itself never intentionally modifies any files. My hope was to implement this with e.g. maestral rather than the native client specifically to make sure any accidental local accidental changes never make it back, but also the additional benefit of a much smaller memory and cpu footprint compared to the native client, and likewise the "live" and small cpu footprint compared to rclone.

The currently doubled up files were certainly not modified on /that/ system - they were capitalized on a windows remote, probably while doing reindexing or initial sync, which is my current guess as to how they got doubled up.

Would you support a pull request for a "cleanup" operation, removing extraneous files and bringing diverged paths? Perhaps in combination with reindexing. Do you perceive it as complicated to implement? I'm not jumping in to do that just yet :-) - considering the options.

**Comment by sprig** [comment]
Also, thanks for the quick response and the quick fix!

**Comment by samschott** [comment]
> 2 is definitely supported by most filesystems as well as by dropbox itself. The issue stops being cosmetic as soon as you have any kind of tool relying on specific paths being present in the dropbox directory, which I believe is a rather common use case.

Agreed, case preserving is definitely the default. With that in mind, file systems that are (configured to be) case-insensitive do allow you to use arbitrarily cased versions of a path. E.g., on macOS, the following will all be operations on the same file that succeed consecutively:

```
touch example.txt
ls -l ExAmPlE.tXt
rm EXAMPLE.txt
```

The same holds for Dropbox APIs which accept paths in arbitrary casing to operate on the same file. I'm aiming to be consistent with the local file APIs for Maestral's own APIs.

> The currently doubled up files were certainly not modified on /that/ system - they were capitalized on a windows remote, probably while doing reindexing or initial sync, which is my current guess as to how they got doubled up.

Ah, but reading through your report, I don't think the files are actually doubled up. There is a single, correct, entry in the local DB for each file. It's just that the `filestatus` command will currently always find this entry, regardless of which casing you pass to it, and return 'up to date'. I don't believe that any cleanup work is actually necessary here.

> Would you support a pull request for a "cleanup" operation, removing extraneous files and bringing diverged paths? Perhaps in combination with reindexing. Do you perceive it as complicated to implement? I

Not sure how difficult it would be. Could you outline what exactly such a cleanup operation would do? "removing extraneous files" seems clear to me, "bringing diverged paths" less so. If this would be useful only for the selective upload or download only flags, I am less inclines.

**Comment by sprig** [comment]
```
With that in mind, file systems that are (configured to be) case-insensitive do allow you to use arbitrarily cased versions of a path. E.g., on macOS, the following will all be operations on the same file that succeed consecutively:
```
Really! This is news to me, thanks teaching me something new! I tested with simple things like `touch` and `rm` and this seems to hold, even on 13.3.1, on APFS which I knew to be case sensitive.

```
The same holds for Dropbox APIs which accept paths in arbitrary casing to operate on the same file. I'm aiming to be consistent with the local file APIs for Maestral's own APIs.
```
Seems like the right choice, I agree.

```
Ah, but reading through your report, I don't think the files are actually doubled up. There is a single, correct, entry in the local DB for each file. It's just that the filestatus command will currently always find this entry, regardless of which casing you pass to it, and return 'up to date'. I don't believe that any cleanup work is actually necessary here.
```

The files are definitely doubled up /locally/ in my case - probably not in the maestral DB. I found this out initially by looking at the FS, not at `maestral filestatus`:

```
-rw-r--r--  1 USER USER 1.5K Feb 18  2021  e.txt
-rw-r--r--  1 USER users 1.5K Feb 18  2021  E.txt
```

the second one is the one dropbox and supposedly maestral knows about. Both my reproduction examples cause 2 files with the same name but different capitalization to eventually exist on the local FS.

```
Not sure how difficult it would be. Could you outline what exactly such a cleanup operation would do? "removing extraneous files" seems clear to me, "bringing diverged paths" less so. If this would be useful only for the selective upload or download only flags, I am less inclines.
```

I'm not entirely sure what the right approach would be either. I guess it depends on the usage scenarios for the upload only/download only options. Deleting extra files is somewhat obvious. regarding diverged paths, I simply mean files that exist in both locations but are different. 

Probably the simplest option in line with the previous approach would likely be to simply overwrite the change. Probably something safer could be offered, e.g. a flag to simply report the list of "bad" files instead of actually deleting/overwriting. 

Actually, Perhaps the simplest/cleanest thing would be to just list all those and let the user deal with them.

Today I had to delete thousands of `(conflicting copy)` files from a maestral repository that `rclone` reported not to exist in dropbox. At least for the few that I checked, maestral agreed. I assume that maestral performs the periodic database rebuild to ensure consistency with the online version, because sometimes these can diverge for unexpected reasons? Looks like  this (divergence) happened in my case, but because I am using a download only option, the extra files were neither uploaded nor deleted. I'm certainly happy they weren't uploaded, but since they were not edited locally, I'm not thrilled by the fact that some extra stuff stayed there, either. Luckily, they were rather easy to identify this time. I think this is the model scenario I'm trying to resolve.

**Comment by samschott** [comment]
> Both my reproduction examples cause 2 files with the same name but different capitalization to eventually exist on the local FS.

I'm trying to reproduce this myself now but got a bit confused by your examples. They all seem to involve local copying or renaming on the machine where Maestral is running. Could you provide a minimum reproducible example where you end up with two local files with different casing after making remote changes only?

**Comment by samschott** [comment]
In my own tests on a case-sensitive file system on Linux, changing the casing of the remote file is successfully synced by renaming the local file. This is also covered by integration tests:

https://github.com/samschott/maestral/blob/6f39dfa67658da67103eb104aa71e36d3bf5a91f/tests/linked/integration/test_sync.py#L260-L264

**Comment by sprig** [comment]
‘’’
I'm trying to reproduce this myself now but got a bit confused by your examples. They all seem to involve local copying or renaming on the machine where Maestral is running. Could you provide a minimum reproducible example where you end up with two local files with different casing after making remote changes only?
‘’’

I’ll attempt, but will be hard pressed to do so, frankly - the examples were meant to demonstrate the ‘filestatus’ issue. My guess is that that the change would need to occur while reindexing is happening. 

It is also possible that I tried to prepopulate the repo with an existing local copy - I have for at least one of them, before reading that this is unsupported, but I’m not sure whether Ive done that for both. 

I also had another issue where two copies of maestral ended up running for a short while against the same repo, due to issues with session folders on linux. It is possible that this happened during that time. It would be helpful to be able to reach a working state when there are mishaps.

Ill make a new DB account for testing this scenario and report back whether I was able to reproduce.

**Comment by sprig** [comment]
I was not able to test with a fresh dropbox account yet. 

However, I do notice that that on one of the repos with `upload = False`, new, `conflicting copy` files are ever present (which is not the case in dropbox itself). I'm not entirely sure why/when those get created - I could not find anything in the log relating to them. It is likely that they were created by a past execution of `maestral`, which could explain the absence of mention in the live log - I will start saving it. However, I do know that there's absolutely nothing writing to that repo other than maestral itself.

This is part of the reason I wanted to test `upload=False` first, since this is a shared folder and I wanted to be certain that I will not be uploading large amounts of conflicting copies, which did happen in the past. 

I suspect they were created when files were changed during a reindex, but I'm not 100% certain. Is this a possibility? If this is indeed the case, is there any way of avoiding this scenario?

**Comment by sprig** [comment]
Much appreciated;

The renaming issue was almost certainly caused by files being renamed (on the remote) during a reindex run, along with the previous `filestatus` logic. I'm not sure there's much use in attempting to reproduce at this point, unless I see this reappearing. The reindex was indeed problematic for me and I had to revert to doing a periodic `rclone sync` in order to avoid conflicting files in a multi-user, frequently-changing repo. I will give this another try now that it's been addressed. 

Thanks!
