### ISSUE TITLE
`maestral autostart -Y` issue with systemd

### ISSUE THREAD

**Issue by TheUnscarred** [samschott/maestral#930]
### The Issue
When running `maestral autostart -Y` I get the following error:
```
Invalid unit name "maestral-daemon@%i.service" escaped as "maestral-daemon@\x25i.service" (maybe you should use systemd-escape?).
Created symlink /home/<User>/.config/systemd/user/default.target.wants/maestral-daemon@\x25i.service → /home/<User>/.local/share/systemd/user/maestral-daemon@.service.
```
Maestral does not automatically start up on the next restart of the system. By running `maestral config-files` you can also see that an empty configuration by the name of `\x25i` is created.

### System
The operating system is EndeavourOS, a distribution derivative of Arch Linux. I installed Maestral in its own Python virtual environment with `pip`. Maestral is version `1.7.3`, the latest at the time of writing. Python is version `3.11.3`.

### The Fix
I deleted the faulty symbolic link `maestral autostart -Y` created and ran the following command:
```
ln -s ~/.local/share/systemd/user/maestral-daemon@service ~/.config/systemd/user/default.target.wants/maestral-daemon@maestral.service
```
This seems to fix the issue and Maestral starts up automatically as it should.

**Comment by haagensen** [comment]
Yup, same here, on Ubuntu 23.04 and Maestral 1.7.3 in a venv; although the configuration file was created without any problems:

```
christian@HPZ820:~$ /comum/venvs/maestral/bin/python -m maestral config-files
Config name  Account                                Path                                           
maestral     <my account>@gmail.com                 /home/christian/.config/maestral/maestral.ini
```

**Comment by TheUnscarred** [comment]
With regards to the configuration file, it creates the default configuration file (`maestral`) just fine, it just happens to create a second unnecessary one if I run `maestral autostart -Y`.

**Comment by samschott** [comment]
Thanks for the report! This was an oversight when updating the autostart code to play nice with venvs.
