### ISSUE TITLE
Maestral 1.7.3 randomly crashes on MBP

### ISSUE THREAD

**Issue by teeetw0** [samschott/maestral#932]
**Describe the bug**
- Maestral 1.7.3 randomly crashes
- Seems to be related to MBP sleep, noticed it happening after closing MBP lid and then re-opening it after an extended period of time (ie. hours)

**To Reproduce**
1. Start Maestral
2. It'll crash

**Expected behaviour**
It doesn't crash :)

**System:**

 - Maestral version: 1.7.3
 - Python version: ?
 - OS: [e.g. Ubuntu] MacOS
 - Desktop environment: MacOS Ventura 13.4 (22F66)
 - PyQt version (for Linux GUI):

**Additional context**
There's no error message and I can't see any log files - it's almost as if I had manually quit it. I'll try to find better repro steps.

**Comment by kareila** [comment]
I came here to report the same problem. Happens on both macOS 12 and 13, and I believe I also saw it happen with 1.7.2 before updating to 1.7.3. No error message indicating that the program has crashed - the menu bar icon just disappears. I also have an iMac running macOS 13 which doesn't have the problem, presumably because it doesn't sleep.

**Comment by gabriel-roth** [comment]
Same issue here. I've got Keyboard Maestro set to check on Maestral every two minutes and relaunch if it's not running. It happens a few times a day. MacBook Pro, macOS 13.4, Maestral 1.7.3.

**Comment by wwform** [comment]
Same issue here, Macbook Pro, macOS 13.2.1, 1.7.3.

**Comment by shailottem** [comment]
I also am having the same issue every time the MacBook wakes from sleep. MacBook Pro, macOS 13.4, Maestral 1.7.3.

**Comment by digitalSaj** [comment]
I am also facing this same issue.
MacBook Pro, MacOS : 12.6.6. Maestral 1.7.3.

**Comment by bjoreman** [comment]
Same issue here. Mac Mini M1, MacBook Pro M1, MacBook Air M2, all running latest Maestral and Ventura.

**Comment by thousandsofthem** [comment]
Same here
MacBook Pro M1 Pro, MacOS 12.6.6, Maestral 1.7.3

**Comment by digitalSaj** [comment]
> I am also facing this same issue. MacBook Pro, MacOS : 12.6.6. Maestral 1.7.3.

I had to add a hourly cron for maestral. Please Devs, fix this.

**Comment by samschott** [comment]
Closing since macOS bundling was changed in v1.9.1. Please post in #808 if this persists.
