### ISSUE TITLE
Maestral.app shows no GUI and no tray icon

### ISSUE THREAD

**Issue by gitsnaf** [samschott/maestral#933]
**Describe the bug**
I have a new MBP-M2 with Ventura 13.4. I did a fresh install, using the latest app bundle: 1.7.3
On the very first start I was able to link my drop box account and then the GUI disappeared. Even no tray icon. In the backgroud I see two maestral processes and I can see that it's syncing my dropbox folder in the background.

**To Reproduce**
Killing the app in the background and then starting via double click again always leads to no gui and no tray icon. But the app is running in the background.
Starting the app via command line also leads to no gui and no tray icon but shows this error:
`[Cocoa] Not implemented: ScrollContainer.set_on_scroll()`

**Expected behaviour**
The gui and a tray icon should appear.

**System:**
 - Maestral version: 1.7.3
 - OS: macOS 13.4

**Comment by gitsnaf** [comment]
After a few reboots, I now have my tray icon back.  I don't know why, but it seems to work now.

**Comment by samschott** [comment]
Could this be a case of "hidden by the notch"?

**Comment by gitsnaf** [comment]
Maybe. I had already thought of that. That's why I closed all applications with a tray icon, so there should have been enough room for the Maestral tray icon. However, I could not check this because I did not have an external monitor during the installation.
