### ISSUE TITLE
maestral history returns changes made in the future bug 

### ISSUE THREAD

**Issue by 12elotro** [samschott/maestral#971]
**"Show Recent Changes"**  shows changes in the files in the future year 2038, and those changes always appear first as they are the most recent.

I execute the order:

`sqlite3 ~/Library/Application\ Support/maestral/maestral.db "DROP TABLE history;"
`

But it shows the following result:

`Error: unable to open database "/home/david/Library/Application Support/maestral/maestral.db": unable to open database file`

My knowledge is limited, I am writing to you how I installed Maestro on Linux Mint 20.3

```
$ apt install python3.8-venv

$ python3 -m venv maestral-venv

$ source maestral-venv/bin/activate

(maestral-venv)$ pip install --upgrade pip

(maestral-venv)$ python3 -m pip install --upgrade 'maestral[gui]'

(maestral-venv)$ sudo apt-get install '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev

(maestral-venv)$ maestral gui

```

**Comment by 12elotro** [comment]
I think that the order: `sqlite3 ~/Library/Application\ Support/maestral/maestral.db "DROP TABLE history;"`

, gives the error because my **maestrol.db** file is located in **/home/david/.local/share/maestral/maestral.db**

amd the directory **/home/david/Library/Application** does not exist

How can I correct the order?

1. Create the directory **/home/david/Library/Application**

2. And execute the command `sqlite3 ~/Library/Application\ home/david/.local/share/maestral/maestral.db "DROP TABLE history;"`

**I ask someone to confirm.**

**Comment by samschott** [comment]
Closing this seems to be resolved. Note also that the issue of changes appearing in the future should be fixed now.
