### ISSUE TITLE
Synchronize modification dates when downloading for the first time

### ISSUE THREAD

**Issue by vicmarto** [samschott/maestral#991]
**Is your feature request related to a problem? Please describe.**
Yesterday I did a full download from Dropbox to my computer, and now all the modification dates are the same: yesterday.

**Describe the solution you'd like**
It would be wonderful if Maestral would also synchronize the modification dates when downloading.

**Additional context**
Thank you very much for the development of Maestral: it is simply thousands of times better than the official client.

**Comment by vicmarto** [comment]
Seems it was reported before in #928 as a bug.

**Comment by samschott** [comment]
Closing as a duplicate of #928. This was fixed in v1.9.0.
