### ISSUE TITLE
systemd watchdog does not work by default in NixOS

### ISSUE THREAD

**Issue by bcc32** [samschott/maestral#992]
**Describe the bug**
When maestral is configured as a systemd (user) service in NixOS by translating from the suggested unit file, maestral daemon crashes every 30 seconds with SIGABRT, in particular:

```
(long backtrace omitted)
Oct 26 18:38:41 nyc systemd[2776]: maestral.service: Failed with result 'watchdog'.
Oct 26 18:38:42 nyc systemd[2776]: maestral.service: Scheduled restart job, restart counter is at 3.
```

**To Reproduce**
Use the following NixOS module to configure maestral:

```
{ config, pkgs, ... }: {
  # https://maestral.app/docs/autostart
  systemd.user.services.maestral = {
    description = "Maestral daemon";
    wantedBy = [ "default.target" ];
    script = "${pkgs.maestral}/bin/maestral start -f";
    preStop = "${pkgs.maestral}/bin/maestral stop";
    onFailure = [ "send-failure-email@%n.service" ];

    unitConfig.ConditionUser = "!@system";

    serviceConfig = {
      Type = "notify";
      NotifyAccess = "all";
      WatchdogSec = "30s";
      PrivateTmp = true;
      ProtectSystem = "full";
      Restart = "always";
    };
  };
}
```

**Expected behaviour**
Maestral daemon should start and run for a long time.

**System:**
 - Maestral version: 1.7.2
 - Python version: 3.10.13
 - OS: NixOS
 - Desktop environment: N/A, not using GUI
 - PyQt version (for Linux GUI): N/A, not using GUI

**Additional context**
I believe this is due to the fact that `IS_WATCHDOG` (daemon.py) is set by checking for `WATCHDOG_PID` to match the PID of the Python interpreter's process.  However, in NixOS, systemd ExecStart/ExecStop and similar commands are bash scripts, meaning that the "main process" PID does not match the `maestral` process's PID.

This can be worked around by changing the `script` and `preStop` attributes to use `exec`, like so:

```
{ config, pkgs, ... }: {
  # https://maestral.app/docs/autostart
  systemd.user.services.maestral = {
    description = "Maestral daemon";
    wantedBy = [ "default.target" ];
    script = "exec ${pkgs.maestral}/bin/maestral start -f";
    preStop = "exec ${pkgs.maestral}/bin/maestral stop";
    onFailure = [ "send-failure-email@%n.service" ];

    unitConfig.ConditionUser = "!@system";

    serviceConfig = {
      Type = "notify";
      NotifyAccess = "all";
      WatchdogSec = "30s";
      PrivateTmp = true;
      ProtectSystem = "full";
      Restart = "always";
    };
  };
}
```

This was pretty tricky to debug, though.  I'm not sure why Maestral checks for the `WATCHDOG_PID` value to equal the output of getpid, but if that's for a good reason, it might be worth dropping a note in Maestral's documentation to use `exec` on NixOS.

**Comment by samschott** [comment]
Thanks for the detailed writeup!

The reason why `daemon.py` checks for `WATCHDOG_PID` comes from the systemd documentation at https://www.freedesktop.org/software/systemd/man/latest/sd_watchdog_enabled.html:

> If the $WATCHDOG_USEC environment variable is set, and the $WATCHDOG_PID variable is unset or set to the PID of the current process, the service manager expects notifications from this process.

It ensures that `$WATCHDOG_USEC` was not set accidentally or from some parent process which handles notifications for us, but that notifications are actually expected from Maestral's process itself.

> However, in NixOS, systemd ExecStart/ExecStop and similar commands are bash scripts, meaning that the "main process" PID does not match the maestral process's PID.

Huh, does this mean that ExecStart actually spawns a subprocess for the daemon? Or does it mess around with environment variables? I'm just curious how `WATCHDOG_PID` ends up having an incorrect value (notifications will still be sent if it's unset).

**Comment by bcc32** [comment]
> It ensures that `$WATCHDOG_USEC` was not set accidentally or from some parent process which handles notifications for us, but that notifications are actually expected from Maestral's process itself.

Makes sense, I am not familiar with the standard but I don't suggest deviating from it.

> > However, in NixOS, systemd ExecStart/ExecStop and similar commands are bash scripts, meaning that the "main process" PID does not match the maestral process's PID.
> 
> Huh, does this mean that ExecStart actually spawns a subprocess for the daemon? Or does it mess around with environment variables? I'm just curious how `WATCHDOG_PID` ends up having an incorrect value (notifications will still be sent if it's unset).

Yes, it spawns a subprocess, implicitly: the ExecStart command line is written to a bash script on disk (in the nix store) and the systemd unit file references the path to the bash script.  So the `WATCHDOG_PID` ends up being set to the pid of the `bash` process (the parent process), instead of the `maestral` process (child process).

**Comment by samschott** [comment]
I see, thanks for the info! Closing this as "won't fix" for now since this should ideally be addressed not on the Maestral side.
