### ISSUE TITLE
Maestral suddenly says "access to your Dropbox has been revoked." and cannot relink

### ISSUE THREAD

**Issue by schoettl** [samschott/maestral#993]
**Describe the bug**

I don't know why but 2 days ago, maestral couldn't sync with Dropbox anymore.
```
$ maestral status
Account      .....@web.de (Basic)
Usage        27.8% of 4.6 GB used
Status       Paused
Sync errors  0


Authentication error
Maestral's access to your Dropbox has been revoked. Please relink to continue syncing.

$ maestral auth link -r
- Linking new account for 'maestral' config
- Retrieving auth code from Dropbox
? How would you like to you link your account? Open Dropbox website
? Enter the auth code: xxxxxxxxxxxxxxxxxxxxx
! Authentication error. Maestral's access to your Dropbox has been revoked. Please relink to continue syncing.
```

**System:**

 - Maestral version: 1.7.2
 - Python version: Python 2.7.18.6
 - OS: NixOS 23.05
 - Desktop environment: Xmonad

In my Dropbox profile settings online, Maestral is still registered as App since December 2022.

Any ideas how to resolve this?

**Comment by schoettl** [comment]
I resolved it by:
```
maestral stop
rm ~/.config/maestral/maestral.ini
maestral start
```
… then linked a new config and merged into the same Dropbox folder.

**Comment by schoettl** [comment]
Oh, it only worked to the next reboot. Now I'm at the beginning again.

**Comment by samschott** [comment]
Could you check the settings of your Dropbox account, in particular the Apps section, on their website? Does Maestral still appear there as an authorized app?

**Comment by schoettl** [comment]
Yes, I already checked. Maestral is listed. I even unlinked the app and linked it again two times. That didn't help.
![grafik](https://github.com/samschott/maestral/assets/1301843/07f526ee-3460-4119-8a0d-46f5709fb081)

**Comment by schoettl** [comment]
I just tried relink and start again. Just as documented above. This time it worked after reboot. I'll report back if it still works tomorrow...

**Comment by schoettl** [comment]
Still works after third reboot. I hope it holds.
